//---------------------------------------------------------------------------------------
//  Smile Programming Language Interpreter
//  Copyright 2004-2015 Sean Werkema
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//---------------------------------------------------------------------------------------

#include <smile/env/knownsymbols.h>

//-------------------------------------------------------------------------------------------------
//  Special symbols.

STATIC_STRING(Equals_, "=", 1);
STATIC_STRING(Op_Equals_, "op=", 3);

STATIC_STRING(If_, "if", 2);
STATIC_STRING(While_, "while", 5);
STATIC_STRING(Till_, "till", 4);
STATIC_STRING(Var_, "var", 3);
STATIC_STRING(Catch_, "catch", 5);
STATIC_STRING(Fn_, "fn", 2);
STATIC_STRING(Scope_, "scope", 5);
STATIC_STRING(Quote_, "quote", 5);
STATIC_STRING(Prog1_, "prog1", 5);
STATIC_STRING(Progn_, "progn", 5);
STATIC_STRING(New_, "new", 3);
STATIC_STRING(Return_, "return", 6);

STATIC_STRING(Not_, "not", 3);
STATIC_STRING(Or_, "or", 2);
STATIC_STRING(And_, "and", 3);

STATIC_STRING(Is_, "is", 2);
STATIC_STRING(Typeof_, "typeof", 6);
STATIC_STRING(SuperEq_, "===", 3);
STATIC_STRING(SuperNe_, "!==", 3);

STATIC_STRING(Brk_, "brk", 3);

static void KnownSymbolsInt_PreloadSpecials(SymbolTable symbolTable, KnownSymbols knownSymbols)
{
	knownSymbols->equals_ = SymbolTableInt_AddFast(symbolTable, Equals_);
	knownSymbols->op_equals_ = SymbolTableInt_AddFast(symbolTable, Op_Equals_);

	knownSymbols->if_ = SymbolTableInt_AddFast(symbolTable, If_);
	knownSymbols->while_ = SymbolTableInt_AddFast(symbolTable, While_);
	knownSymbols->till_ = SymbolTableInt_AddFast(symbolTable, Till_);
	knownSymbols->var_ = SymbolTableInt_AddFast(symbolTable, Var_);
	knownSymbols->catch_ = SymbolTableInt_AddFast(symbolTable, Catch_);
	knownSymbols->fn_ = SymbolTableInt_AddFast(symbolTable, Fn_);
	knownSymbols->scope_ = SymbolTableInt_AddFast(symbolTable, Scope_);
	knownSymbols->quote_ = SymbolTableInt_AddFast(symbolTable, Quote_);
	knownSymbols->prog1_ = SymbolTableInt_AddFast(symbolTable, Prog1_);
	knownSymbols->progn_ = SymbolTableInt_AddFast(symbolTable, Progn_);
	knownSymbols->new_ = SymbolTableInt_AddFast(symbolTable, New_);
	knownSymbols->return_ = SymbolTableInt_AddFast(symbolTable, Return_);

	knownSymbols->not_ = SymbolTableInt_AddFast(symbolTable, Not_);
	knownSymbols->or_ = SymbolTableInt_AddFast(symbolTable, Or_);
	knownSymbols->and_ = SymbolTableInt_AddFast(symbolTable, And_);

	knownSymbols->is_ = SymbolTableInt_AddFast(symbolTable, Is_);
	knownSymbols->typeof_ = SymbolTableInt_AddFast(symbolTable, Typeof_);
	knownSymbols->supereq_ = SymbolTableInt_AddFast(symbolTable, SuperEq_);
	knownSymbols->superne_ = SymbolTableInt_AddFast(symbolTable, SuperNe_);

	knownSymbols->brk_ = SymbolTableInt_AddFast(symbolTable, Brk_);
}

//-------------------------------------------------------------------------------------------------
//  Common operator symbols.

STATIC_STRING(Plus_, "+", 1);
STATIC_STRING(Minus_, "-", 1);
STATIC_STRING(Star_, "*", 1);
STATIC_STRING(Slash_, "/", 1);
STATIC_STRING(Caret_, "^", 1);

STATIC_STRING(Shift_Left_, "<<<", 3);
STATIC_STRING(Shift_Right_, ">>>", 3);
STATIC_STRING(Arithmetic_Shift_Left_, "<<", 2);
STATIC_STRING(Arithmetic_Shift_Right_, ">>", 2);
STATIC_STRING(Rotate_Left_, "<<+", 3);
STATIC_STRING(Rotate_Right_, "+>>", 3);

STATIC_STRING(Eq_, "==", 2);
STATIC_STRING(Ne_, "!=", 2);
STATIC_STRING(Lt_, "<", 1);
STATIC_STRING(Gt_, ">", 1);
STATIC_STRING(Le_, "<=", 2);
STATIC_STRING(Ge_, ">=", 2);

static void KnownSymbolsInt_PreloadCommonOperators(SymbolTable symbolTable, KnownSymbols knownSymbols)
{
	knownSymbols->plus = SymbolTableInt_AddFast(symbolTable, Plus_);
	knownSymbols->minus = SymbolTableInt_AddFast(symbolTable, Minus_);
	knownSymbols->star = SymbolTableInt_AddFast(symbolTable, Star_);
	knownSymbols->slash = SymbolTableInt_AddFast(symbolTable, Slash_);
	knownSymbols->caret = SymbolTableInt_AddFast(symbolTable, Caret_);

	knownSymbols->shift_left = SymbolTableInt_AddFast(symbolTable, Shift_Left_);
	knownSymbols->shift_right = SymbolTableInt_AddFast(symbolTable, Shift_Right_);
	knownSymbols->arithmetic_shift_left = SymbolTableInt_AddFast(symbolTable, Arithmetic_Shift_Left_);
	knownSymbols->arithmetic_shift_right = SymbolTableInt_AddFast(symbolTable, Arithmetic_Shift_Right_);
	knownSymbols->rotate_left = SymbolTableInt_AddFast(symbolTable, Rotate_Left_);
	knownSymbols->rotate_right = SymbolTableInt_AddFast(symbolTable, Rotate_Right_);

	knownSymbols->eq = SymbolTableInt_AddFast(symbolTable, Eq_);
	knownSymbols->ne = SymbolTableInt_AddFast(symbolTable, Ne_);
	knownSymbols->lt = SymbolTableInt_AddFast(symbolTable, Lt_);
	knownSymbols->gt = SymbolTableInt_AddFast(symbolTable, Gt_);
	knownSymbols->le = SymbolTableInt_AddFast(symbolTable, Le_);
	knownSymbols->ge = SymbolTableInt_AddFast(symbolTable, Ge_);
}

//-------------------------------------------------------------------------------------------------
//  Typename symbols.

STATIC_STRING(Actor_, "Actor", 5);
STATIC_STRING(Array_, "Array", 5);
STATIC_STRING(ArrayBase_, "ArrayBase", 9);
STATIC_STRING(Bool_, "Bool", 4);
STATIC_STRING(Byte_, "Byte", 4);
STATIC_STRING(ByteRange_, "ByteRange", 9);
STATIC_STRING(ByteArray_, "ByteArray", 9);
STATIC_STRING(Char_, "Char", 4);
STATIC_STRING(Closure, "Closure", 7);
STATIC_STRING(Enumerable_, "Enumerable", 10);
STATIC_STRING(Exception_, "Exception", 9);
STATIC_STRING(Facade_, "Facade", 6);
STATIC_STRING(FacadeProper_, "Façade", 6);
STATIC_STRING(_Fn_, "Fn", 2);
STATIC_STRING(Handle_, "Handle", 6);
STATIC_STRING(IntegerArrayBase_, "IntegerArrayBase", 16);
STATIC_STRING(Integer_, "Integer", 7);
STATIC_STRING(Integer16_, "Integer16", 9);
STATIC_STRING(Integer32_, "Integer32", 9);
STATIC_STRING(Integer32Array_, "Integer32Array", 14);
STATIC_STRING(Integer32Map_, "Integer32Map", 12);
STATIC_STRING(Integer32Range_, "Integer32Range", 14);
STATIC_STRING(Integer64_, "Integer64", 9);
STATIC_STRING(Integer64Array_, "Integer64Array", 14);
STATIC_STRING(Integer64Map_, "Integer64Map", 12);
STATIC_STRING(Integer64Range_, "Integer64Range", 14);
STATIC_STRING(IntegerBase_, "IntegerBase", 11);
STATIC_STRING(IntegerRange_, "IntegerRange", 12);
STATIC_STRING(IntegerRangeBase_, "IntegerRangeBase", 16);
STATIC_STRING(List_, "List", 4);
STATIC_STRING(Map_, "Map", 3);
STATIC_STRING(MapBase_, "MapBase", 7);
STATIC_STRING(MathException, "MathException", 13);
STATIC_STRING(NumericArrayBase_, "NumericArrayBase", 16);
STATIC_STRING(Number_, "Number", 6);
STATIC_STRING(Null_, "Null", 4);
STATIC_STRING(Object_, "Object", 6);
STATIC_STRING(Pair_, "Pair", 4);
STATIC_STRING(Program_, "Program", 7);
STATIC_STRING(Random_, "Random", 6);
STATIC_STRING(Range_, "Range", 5);
STATIC_STRING(Real_, "Real", 4);
STATIC_STRING(RealArrayBase_, "RealArrayBase", 13);
STATIC_STRING(Real32_, "Real32", 6);
STATIC_STRING(Real32Array_, "Real32Array", 11);
STATIC_STRING(Real32Range_, "Real32Range", 11);
STATIC_STRING(Real64_, "Real64", 6);
STATIC_STRING(Real64Array_, "Real64Array", 11);
STATIC_STRING(Real64Range_, "Real64Range", 11);
STATIC_STRING(RealBase_, "RealBase", 8);
STATIC_STRING(RealRange_, "RealRange", 9);
STATIC_STRING(RealRangeBase_, "RealRangeBase", 13);
STATIC_STRING(Regex_, "Regex", 5);
STATIC_STRING(String_, "String", 6);
STATIC_STRING(StringMap_, "StringMap", 9);
STATIC_STRING(Symbol_, "Symbol", 6);
STATIC_STRING(SymbolMap_, "SymbolMap", 9);
STATIC_STRING(UChar_, "UChar", 5);
STATIC_STRING(UserObject_, "UserObject", 10);

static void KnownSymbolsInt_PreloadTypenames(SymbolTable symbolTable, KnownSymbols knownSymbols)
{
	knownSymbols->Actor_ = SymbolTableInt_AddFast(symbolTable, Actor_);
	knownSymbols->Array_ = SymbolTableInt_AddFast(symbolTable, Array_);
	knownSymbols->ArrayBase_ = SymbolTableInt_AddFast(symbolTable, ArrayBase_);
	knownSymbols->Bool_ = SymbolTableInt_AddFast(symbolTable, Bool_);
	knownSymbols->Byte_ = SymbolTableInt_AddFast(symbolTable, Byte_);
	knownSymbols->ByteRange_ = SymbolTableInt_AddFast(symbolTable, ByteRange_);
	knownSymbols->ByteArray_ = SymbolTableInt_AddFast(symbolTable, ByteArray_);
	knownSymbols->Char_ = SymbolTableInt_AddFast(symbolTable, Char_);
	knownSymbols->Closure = SymbolTableInt_AddFast(symbolTable, Closure);
	knownSymbols->Enumerable_ = SymbolTableInt_AddFast(symbolTable, Enumerable_);
	knownSymbols->Exception_ = SymbolTableInt_AddFast(symbolTable, Exception_);
	knownSymbols->Facade_ = SymbolTableInt_AddFast(symbolTable, Facade_);
	knownSymbols->FacadeProper_ = SymbolTableInt_AddFast(symbolTable, FacadeProper_);
	knownSymbols->Fn_ = SymbolTableInt_AddFast(symbolTable, _Fn_);
	knownSymbols->Handle_ = SymbolTableInt_AddFast(symbolTable, Handle_);
	knownSymbols->IntegerArrayBase_ = SymbolTableInt_AddFast(symbolTable, IntegerArrayBase_);
	knownSymbols->Integer_ = SymbolTableInt_AddFast(symbolTable, Integer_);
	knownSymbols->Integer16_ = SymbolTableInt_AddFast(symbolTable, Integer16_);
	knownSymbols->Integer32_ = SymbolTableInt_AddFast(symbolTable, Integer32_);
	knownSymbols->Integer32Array_ = SymbolTableInt_AddFast(symbolTable, Integer32Array_);
	knownSymbols->Integer32Map_ = SymbolTableInt_AddFast(symbolTable, Integer32Map_);
	knownSymbols->Integer32Range_ = SymbolTableInt_AddFast(symbolTable, Integer32Range_);
	knownSymbols->Integer64_ = SymbolTableInt_AddFast(symbolTable, Integer64_);
	knownSymbols->Integer64Array_ = SymbolTableInt_AddFast(symbolTable, Integer64Array_);
	knownSymbols->Integer64Map_ = SymbolTableInt_AddFast(symbolTable, Integer64Map_);
	knownSymbols->Integer64Range_ = SymbolTableInt_AddFast(symbolTable, Integer64Range_);
	knownSymbols->IntegerBase_ = SymbolTableInt_AddFast(symbolTable, IntegerBase_);
	knownSymbols->IntegerRange_ = SymbolTableInt_AddFast(symbolTable, IntegerRange_);
	knownSymbols->IntegerRangeBase_ = SymbolTableInt_AddFast(symbolTable, IntegerRangeBase_);
	knownSymbols->List_ = SymbolTableInt_AddFast(symbolTable, List_);
	knownSymbols->Map_ = SymbolTableInt_AddFast(symbolTable, Map_);
	knownSymbols->MapBase_ = SymbolTableInt_AddFast(symbolTable, MapBase_);
	knownSymbols->MathException = SymbolTableInt_AddFast(symbolTable, MathException);
	knownSymbols->NumericArrayBase_ = SymbolTableInt_AddFast(symbolTable, NumericArrayBase_);
	knownSymbols->Number_ = SymbolTableInt_AddFast(symbolTable, Number_);
	knownSymbols->Null_ = SymbolTableInt_AddFast(symbolTable, Null_);
	knownSymbols->Object_ = SymbolTableInt_AddFast(symbolTable, Object_);
	knownSymbols->Pair_ = SymbolTableInt_AddFast(symbolTable, Pair_);
	knownSymbols->Program_ = SymbolTableInt_AddFast(symbolTable, Program_);
	knownSymbols->Random_ = SymbolTableInt_AddFast(symbolTable, Random_);
	knownSymbols->Range_ = SymbolTableInt_AddFast(symbolTable, Range_);
	knownSymbols->Real_ = SymbolTableInt_AddFast(symbolTable, Real_);
	knownSymbols->RealArrayBase_ = SymbolTableInt_AddFast(symbolTable, RealArrayBase_);
	knownSymbols->Real32_ = SymbolTableInt_AddFast(symbolTable, Real32_);
	knownSymbols->Real32Array_ = SymbolTableInt_AddFast(symbolTable, Real32Array_);
	knownSymbols->Real32Range_ = SymbolTableInt_AddFast(symbolTable, Real32Range_);
	knownSymbols->Real64_ = SymbolTableInt_AddFast(symbolTable, Real64_);
	knownSymbols->Real64Array_ = SymbolTableInt_AddFast(symbolTable, Real64Array_);
	knownSymbols->Real64Range_ = SymbolTableInt_AddFast(symbolTable, Real64Range_);
	knownSymbols->RealBase_ = SymbolTableInt_AddFast(symbolTable, RealBase_);
	knownSymbols->RealRange_ = SymbolTableInt_AddFast(symbolTable, RealRange_);
	knownSymbols->RealRangeBase_ = SymbolTableInt_AddFast(symbolTable, RealRangeBase_);
	knownSymbols->Regex_ = SymbolTableInt_AddFast(symbolTable, Regex_);
	knownSymbols->String_ = SymbolTableInt_AddFast(symbolTable, String_);
	knownSymbols->StringMap_ = SymbolTableInt_AddFast(symbolTable, StringMap_);
	knownSymbols->Symbol_ = SymbolTableInt_AddFast(symbolTable, Symbol_);
	knownSymbols->SymbolMap_ = SymbolTableInt_AddFast(symbolTable, SymbolMap_);
	knownSymbols->UChar_ = SymbolTableInt_AddFast(symbolTable, UChar_);
	knownSymbols->UserObject_ = SymbolTableInt_AddFast(symbolTable, UserObject_);
}

//-------------------------------------------------------------------------------------------------
//  General symbols.

STATIC_STRING(a, "a", 1);
STATIC_STRING(abs_, "abs", 3);
STATIC_STRING(acos_, "acos", 4);
STATIC_STRING(add_c_slashes, "add-c-slashes", 13);
STATIC_STRING(alnum_q, "alnum?", 6);
STATIC_STRING(alpha_q, "alpha?", 6);
STATIC_STRING(apply, "apply", 5);
STATIC_STRING(apply_method, "apply-method", 12);
STATIC_STRING(arguments, "arguments", 9);
STATIC_STRING(asin_, "asin", 4);
STATIC_STRING(assertions, "assertions", 10);
STATIC_STRING(assigned_name, "assigned-name", 13);
STATIC_STRING(atan_, "atan", 4);
STATIC_STRING(atan2_, "atan2", 5);
STATIC_STRING(base_, "base", 4);
STATIC_STRING(bit_not, "~", 1);
STATIC_STRING(bit_and, "band", 4);
STATIC_STRING(bit_or, "bor", 3);
STATIC_STRING(bit_xor, "bxor", 4);
STATIC_STRING(body, "body", 4);
STATIC_STRING(bool_, "bool", 4);
STATIC_STRING(byte_, "byte", 4);
STATIC_STRING(byte_array, "byte-array", 10);
STATIC_STRING(call, "call", 4);
STATIC_STRING(call_method, "call-method", 11);
STATIC_STRING(camelCase, "camelCase", 9);
STATIC_STRING(CamelCase, "CamelCase", 9);
STATIC_STRING(case_fold, "case-fold", 9);
STATIC_STRING(case_insensitive, "case-insensitive", 16);
STATIC_STRING(case_sensitive, "case-sensitive", 14);
STATIC_STRING(category, "category", 8);
STATIC_STRING(ceil_, "ceil", 4);
STATIC_STRING(char_, "char", 4);
STATIC_STRING(chip, "chip", 4);
STATIC_STRING(chop, "chop", 4);
STATIC_STRING(cident_q, "cident?", 7);
STATIC_STRING(clip, "clip", 4);
STATIC_STRING(clone, "clone", 5);
STATIC_STRING(code_at, "code-at", 7);
STATIC_STRING(code_length, "code-length", 11);
STATIC_STRING(compare, "compare", 7);
STATIC_STRING(compare_i, "compare-i", 9);
STATIC_STRING(compose, "compose", 7);
STATIC_STRING(composed_q, "composed?", 9);
STATIC_STRING(cons, "cons", 4);
STATIC_STRING(contains, "contains", 8);
STATIC_STRING(contains_i, "contains-i", 10);
STATIC_STRING(context, "context", 7);
STATIC_STRING(control_q, "control?", 8);
STATIC_STRING(cos_, "cos", 3);
STATIC_STRING(count, "count", 5);
STATIC_STRING(count64, "count64", 7);
STATIC_STRING(count_left_ones, "count-left-ones", 15);
STATIC_STRING(count_left_zeros, "count-left-zeros", 16);
STATIC_STRING(count_of, "count-of", 8);
STATIC_STRING(count_of_i, "count-of-i", 10);
STATIC_STRING(count_ones, "count-ones", 10);
STATIC_STRING(count_right_ones, "count-right-ones", 16);
STATIC_STRING(count_right_zeros, "count-right-zeros", 17);
STATIC_STRING(count_zeros, "count-zeros", 11);
STATIC_STRING(crc32, "crc32", 5);
STATIC_STRING(create, "create", 6);
STATIC_STRING(create_child_closure, "create-child-closure", 20);
STATIC_STRING(d, "d", 1);
STATIC_STRING(decompose, "decompose", 9);
STATIC_STRING(diacritic_q, "diacritic?", 10);
STATIC_STRING(digit_q, "digit?", 6);
STATIC_STRING(div, "div", 3);
STATIC_STRING(divide_by_zero, "divide-by-zero", 14);
STATIC_STRING(does_not_understand, "does-not-understand", 19);
STATIC_STRING(each, "each", 4);
STATIC_STRING(end, "end", 3);
STATIC_STRING(ends_with, "ends-with", 9);
STATIC_STRING(ends_with_i, "ends-with-i", 11);
STATIC_STRING(escape, "escape", 6);
STATIC_STRING(even_q, "even?", 5);
STATIC_STRING(eval, "eval", 4);
STATIC_STRING(exit_, "exit", 4);
STATIC_STRING(extend_object, "extend-object", 13);
STATIC_STRING(extend_where_new, "extend-where-new", 16);
STATIC_STRING(exp_, "exp", 3);
STATIC_STRING(false_, "false", 5);
STATIC_STRING(filename_mode, "filename-mode", 13);
STATIC_STRING(first, "first", 5);
STATIC_STRING(floor_, "floor", 5);
STATIC_STRING(fn, "fn", 2);
STATIC_STRING(fold, "fold", 4);
STATIC_STRING(from_seed, "from-seed", 9);
STATIC_STRING(get_member, "get-member", 10);
STATIC_STRING(get_object_security, "get-object-security", 19);
STATIC_STRING(get_property, "get-property", 12);
STATIC_STRING(handle_kind, "handle-kind", 11);
STATIC_STRING(hash, "hash", 4);
STATIC_STRING(has_property, "has-property", 12);
STATIC_STRING(hex_string, "hex-string", 10);
STATIC_STRING(hex_string_pretty, "hex-string-pretty", 17);
STATIC_STRING(html_decode, "html-decode", 11);
STATIC_STRING(html_encode, "html-encode", 11);
STATIC_STRING(hyphenize, "hyphenize", 9);
STATIC_STRING(id, "id", 2);
STATIC_STRING(in_, "in", 2);
STATIC_STRING(include, "include", 7);
STATIC_STRING(index_of, "index-of", 8);
STATIC_STRING(index_of_i, "index-of-i", 10);
STATIC_STRING(int_, "int", 3);
STATIC_STRING(int16_, "int16", 5);
STATIC_STRING(int32_, "int32", 5);
STATIC_STRING(int64_, "int64", 5);
STATIC_STRING(int_lg, "int-lg", 6);
STATIC_STRING(last_index_of, "last-index-of", 13);
STATIC_STRING(last_index_of_i, "last-index-of-i", 15);
STATIC_STRING(latin1_to_utf8, "latin1-to-utf8", 14);
STATIC_STRING(left, "left", 4);
STATIC_STRING(length, "length", 6);
STATIC_STRING(letter, "letter", 6);
STATIC_STRING(letter_q, "letter?", 7);
STATIC_STRING(letter_lowercase, "letter-lowercase", 16);
STATIC_STRING(letter_modifier, "letter-modifier", 15);
STATIC_STRING(letter_other, "letter-other", 12);
STATIC_STRING(letter_titlecase, "letter-titlecase", 16);
STATIC_STRING(letter_uppercase, "letter-uppercase", 16);
STATIC_STRING(lg, "lg", 2);
STATIC_STRING(list, "list", 4);
STATIC_STRING(load, "load", 4);
STATIC_STRING(log_, "log", 3);
STATIC_STRING(log_domain, "log-domain", 10);
STATIC_STRING(lower, "lower", 5);
STATIC_STRING(lowercase, "lowercase", 9);
STATIC_STRING(lowercase_q, "lowercase?", 10);
STATIC_STRING(ln, "ln", 2);
STATIC_STRING(join, "join", 4);
STATIC_STRING(keys, "keys", 4);
STATIC_STRING(kind, "kind", 4);
STATIC_STRING(map, "map", 3);
STATIC_STRING(mark, "mark", 4);
STATIC_STRING(mark_enclosing, "mark-enclosing", 14);
STATIC_STRING(mark_non_spacing, "mark-non-spacing", 16);
STATIC_STRING(mark_spacing_combining, "mark-spacing-combining", 22);
STATIC_STRING(match, "match", 5);
STATIC_STRING(matches, "matches?", 8);
STATIC_STRING(max, "max", 3);
STATIC_STRING(message, "message", 7);
STATIC_STRING(mid, "mid", 3);
STATIC_STRING(min, "min", 3);
STATIC_STRING(mod, "mod", 3);
STATIC_STRING(name, "name", 4);
STATIC_STRING(neg_q, "neg?", 4);
STATIC_STRING(newline_q, "newline?", 8);
STATIC_STRING(next_pow2, "next-pow2", 9);
STATIC_STRING(normalize_diacritics, "normalize-diacritics", 20);
STATIC_STRING(nth, "nth", 3);
STATIC_STRING(nth_cell, "nth-cell", 8);
STATIC_STRING(null_, "null", 4);
STATIC_STRING(number, "number", 6);
STATIC_STRING(number_decimal_digit, "number-decimal-digit", 20);
STATIC_STRING(number_letter, "number-letter", 13);
STATIC_STRING(number_other, "number-other", 12);
STATIC_STRING(numeric_q, "numeric?", 8);
STATIC_STRING(octal_q, "octal?", 6);
STATIC_STRING(of, "of", 2);
STATIC_STRING(of_size, "of-size", 7);
STATIC_STRING(odd_q, "odd?", 4);
STATIC_STRING(one_q, "one?", 4);
STATIC_STRING(options, "options", 7);
STATIC_STRING(other, "other", 5);
STATIC_STRING(other_control, "other-control", 13);
STATIC_STRING(other_format, "other-format", 12);
STATIC_STRING(other_not_assigned, "other-not-assigned", 18);
STATIC_STRING(other_private_use, "other-private-use", 17);
STATIC_STRING(other_surrogate, "other-surrogate", 15);
STATIC_STRING(parity, "parity", 6);
STATIC_STRING(parse, "parse", 5);
STATIC_STRING(parse_and_eval, "parse-and-eval", 14);
STATIC_STRING(pos_q, "pos?", 4);
STATIC_STRING(post, "post", 4);
STATIC_STRING(pow2_q, "pow2?", 5);
STATIC_STRING(pre, "pre", 3);
STATIC_STRING(primary_category, "primary-category", 16);
STATIC_STRING(printf, "printf", 6);
STATIC_STRING(process_id, "process-id", 10);
STATIC_STRING(property_names, "property-names", 14);
STATIC_STRING(punct_q, "punct?", 6);
STATIC_STRING(punctuation, "punctuation", 11);
STATIC_STRING(punctuation_close, "punctuation-close", 17);
STATIC_STRING(punctuation_connector, "punctuation-connector", 21);
STATIC_STRING(punctuation_dash, "punctuation-dash", 16);
STATIC_STRING(punctuation_final_quote, "punctuation-final-quote", 23);
STATIC_STRING(punctuation_initial_quote, "punctuation-initial-quote", 25);
STATIC_STRING(punctuation_open, "punctuation-open", 16);
STATIC_STRING(punctuation_other, "punctuation-other", 17);
STATIC_STRING(raw_reverse, "raw-reverse", 11);
STATIC_STRING(read_append, "read-append", 11);
STATIC_STRING(read_only, "read-only", 9);
STATIC_STRING(read_write, "read-write", 10);
STATIC_STRING(read_write_append, "read-write-append", 17);
STATIC_STRING(real_, "real", 4);
STATIC_STRING(real32_, "real32", 6);
STATIC_STRING(real64_, "real64", 6);
STATIC_STRING(rem, "rem", 3);
STATIC_STRING(replace, "replace", 7);
STATIC_STRING(resize, "resize", 6);
STATIC_STRING(rest, "rest", 4);
STATIC_STRING(reverse, "reverse", 7);
STATIC_STRING(reverse_bits, "reverse-bits", 12);
STATIC_STRING(reverse_bytes, "reverse-bytes", 13);
STATIC_STRING(right, "right", 5);
STATIC_STRING(rot_13, "rot-13", 6);
STATIC_STRING(result, "result", 6);
STATIC_STRING(separator, "separator", 9);
STATIC_STRING(separator_line, "separator-line", 14);
STATIC_STRING(separator_paragraph, "separator-paragraph", 19);
STATIC_STRING(separator_space, "separator-space", 15);
STATIC_STRING(set_member, "set-member", 10);
STATIC_STRING(set_object_security, "set-object-security", 19);
STATIC_STRING(set_property, "set-property", 12);
STATIC_STRING(sign, "sign", 4);
STATIC_STRING(sin_, "sin", 3);
STATIC_STRING(space_q, "space?", 6);
STATIC_STRING(splice, "splice", 6);
STATIC_STRING(split, "split", 5);
STATIC_STRING(sprintf, "sprintf", 7);
STATIC_STRING(sqrt_, "sqrt", 4);
STATIC_STRING(sqrt_domain, "sqrt-domain", 11);
STATIC_STRING(start, "start", 5);
STATIC_STRING(starts_with, "starts-with", 11);
STATIC_STRING(starts_with_i, "starts-with-i", 13);
STATIC_STRING(step, "step", 4);
STATIC_STRING(stepping, "stepping", 8);
STATIC_STRING(strip_c_slashes, "strip-c-slashes", 15);
STATIC_STRING(string_, "string", 6);
STATIC_STRING(studied_, "studied?", 8);
STATIC_STRING(study, "study", 5);
STATIC_STRING(substr, "substr", 6);
STATIC_STRING(substring, "substring", 9);
STATIC_STRING(symbol, "symbol", 6);
STATIC_STRING(symbol_currency, "symbol-currency", 15);
STATIC_STRING(symbol_math, "symbol-math", 11);
STATIC_STRING(symbol_modifier, "symbol-modifier", 15);
STATIC_STRING(symbol_other, "symbol-other", 12);
STATIC_STRING(tan_, "tan", 3);
STATIC_STRING(text, "text", 4);
STATIC_STRING(this_, "this", 4);
STATIC_STRING(this_closure, "this-closure", 12);
STATIC_STRING(throw_, "throw", 5);
STATIC_STRING(title, "title", 5);
STATIC_STRING(titlecase, "titlecase", 9);
STATIC_STRING(titlecase_q, "titlecase?", 10);
STATIC_STRING(trim, "trim", 4);
STATIC_STRING(trim_end, "trim-end", 8);
STATIC_STRING(trim_start, "trim-start", 10);
STATIC_STRING(true_, "true", 4);
STATIC_STRING(type, "type", 4);
STATIC_STRING(uchar, "uchar", 5);
STATIC_STRING(underscorize, "underscorize", 12);
STATIC_STRING(unknown, "unknown", 7);
STATIC_STRING(upper, "upper", 5);
STATIC_STRING(uppercase, "uppercase", 9);
STATIC_STRING(uppercase_q, "uppercase?", 10);
STATIC_STRING(url_decode, "url-decode", 10);
STATIC_STRING(url_encode, "url-encode", 10);
STATIC_STRING(url_query_encode, "url-query-encode", 16);
STATIC_STRING(utf8_to_latin1, "utf8-to-latin1", 14);
STATIC_STRING(values, "values", 6);
STATIC_STRING(where_, "where", 5);
STATIC_STRING(whitespace_q, "whitespace?", 11);
STATIC_STRING(wildcard_matches, "wildcard-matches?", 17);
STATIC_STRING(without, "without", 7);
STATIC_STRING(xdigit_q, "xdigit?", 7);
STATIC_STRING(xor, "xor", 3);
STATIC_STRING(zero_q, "zero?", 5);

static void KnownSymbolsInt_PreloadGeneralSymbols(SymbolTable symbolTable, KnownSymbols knownSymbols)
{
	knownSymbols->a = SymbolTableInt_AddFast(symbolTable, a);
	knownSymbols->abs = SymbolTableInt_AddFast(symbolTable, abs_);
	knownSymbols->acos = SymbolTableInt_AddFast(symbolTable, acos_);
	knownSymbols->add_c_slashes = SymbolTableInt_AddFast(symbolTable, add_c_slashes);
	knownSymbols->alnum_q = SymbolTableInt_AddFast(symbolTable, alnum_q);
	knownSymbols->alpha_q = SymbolTableInt_AddFast(symbolTable, alpha_q);
	knownSymbols->apply = SymbolTableInt_AddFast(symbolTable, apply);
	knownSymbols->apply_method = SymbolTableInt_AddFast(symbolTable, apply_method);
	knownSymbols->arguments = SymbolTableInt_AddFast(symbolTable, arguments);
	knownSymbols->asin = SymbolTableInt_AddFast(symbolTable, asin_);
	knownSymbols->assertions = SymbolTableInt_AddFast(symbolTable, assertions);
	knownSymbols->assigned_name = SymbolTableInt_AddFast(symbolTable, assigned_name);
	knownSymbols->atan = SymbolTableInt_AddFast(symbolTable, atan_);
	knownSymbols->atan2 = SymbolTableInt_AddFast(symbolTable, atan2_);
	knownSymbols->base_ = SymbolTableInt_AddFast(symbolTable, base_);
	knownSymbols->bit_not = SymbolTableInt_AddFast(symbolTable, bit_not);
	knownSymbols->bit_and = SymbolTableInt_AddFast(symbolTable, bit_and);
	knownSymbols->bit_or = SymbolTableInt_AddFast(symbolTable, bit_or);
	knownSymbols->bit_xor = SymbolTableInt_AddFast(symbolTable, bit_xor);
	knownSymbols->body = SymbolTableInt_AddFast(symbolTable, body);
	knownSymbols->bool_ = SymbolTableInt_AddFast(symbolTable, bool_);
	knownSymbols->byte_ = SymbolTableInt_AddFast(symbolTable, byte_);
	knownSymbols->byte_array = SymbolTableInt_AddFast(symbolTable, byte_array);
	knownSymbols->call = SymbolTableInt_AddFast(symbolTable, call);
	knownSymbols->call_method = SymbolTableInt_AddFast(symbolTable, call_method);
	knownSymbols->camelCase = SymbolTableInt_AddFast(symbolTable, camelCase);
	knownSymbols->CamelCase = SymbolTableInt_AddFast(symbolTable, CamelCase);
	knownSymbols->case_fold = SymbolTableInt_AddFast(symbolTable, case_fold);
	knownSymbols->case_insensitive = SymbolTableInt_AddFast(symbolTable, case_insensitive);
	knownSymbols->case_sensitive = SymbolTableInt_AddFast(symbolTable, case_sensitive);
	knownSymbols->category = SymbolTableInt_AddFast(symbolTable, category);
	knownSymbols->ceil = SymbolTableInt_AddFast(symbolTable, ceil_);
	knownSymbols->char_ = SymbolTableInt_AddFast(symbolTable, char_);
	knownSymbols->chip = SymbolTableInt_AddFast(symbolTable, chip);
	knownSymbols->chop = SymbolTableInt_AddFast(symbolTable, chop);
	knownSymbols->cident_q = SymbolTableInt_AddFast(symbolTable, cident_q);
	knownSymbols->clip = SymbolTableInt_AddFast(symbolTable, clip);
	knownSymbols->clone = SymbolTableInt_AddFast(symbolTable, clone);
	knownSymbols->code_at = SymbolTableInt_AddFast(symbolTable, code_at);
	knownSymbols->code_length = SymbolTableInt_AddFast(symbolTable, code_length);
	knownSymbols->compare = SymbolTableInt_AddFast(symbolTable, compare);
	knownSymbols->compare_i = SymbolTableInt_AddFast(symbolTable, compare_i);
	knownSymbols->compose = SymbolTableInt_AddFast(symbolTable, compose);
	knownSymbols->composed_q = SymbolTableInt_AddFast(symbolTable, composed_q);
	knownSymbols->cons = SymbolTableInt_AddFast(symbolTable, cons);
	knownSymbols->contains = SymbolTableInt_AddFast(symbolTable, contains);
	knownSymbols->contains_i = SymbolTableInt_AddFast(symbolTable, contains_i);
	knownSymbols->context = SymbolTableInt_AddFast(symbolTable, context);
	knownSymbols->control_q = SymbolTableInt_AddFast(symbolTable, control_q);
	knownSymbols->cos = SymbolTableInt_AddFast(symbolTable, cos_);
	knownSymbols->count = SymbolTableInt_AddFast(symbolTable, count);
	knownSymbols->count64 = SymbolTableInt_AddFast(symbolTable, count64);
	knownSymbols->count_left_ones = SymbolTableInt_AddFast(symbolTable, count_left_ones);
	knownSymbols->count_left_zeros = SymbolTableInt_AddFast(symbolTable, count_left_zeros);
	knownSymbols->count_of = SymbolTableInt_AddFast(symbolTable, count_of);
	knownSymbols->count_of_i = SymbolTableInt_AddFast(symbolTable, count_of_i);
	knownSymbols->count_ones = SymbolTableInt_AddFast(symbolTable, count_ones);
	knownSymbols->count_right_ones = SymbolTableInt_AddFast(symbolTable, count_right_ones);
	knownSymbols->count_right_zeros = SymbolTableInt_AddFast(symbolTable, count_right_zeros);
	knownSymbols->count_zeros = SymbolTableInt_AddFast(symbolTable, count_zeros);
	knownSymbols->crc32 = SymbolTableInt_AddFast(symbolTable, crc32);
	knownSymbols->create = SymbolTableInt_AddFast(symbolTable, create);
	knownSymbols->create_child_closure = SymbolTableInt_AddFast(symbolTable, create_child_closure);
	knownSymbols->d = SymbolTableInt_AddFast(symbolTable, d);
	knownSymbols->decompose = SymbolTableInt_AddFast(symbolTable, decompose);
	knownSymbols->diacritic_q = SymbolTableInt_AddFast(symbolTable, diacritic_q);
	knownSymbols->digit_q = SymbolTableInt_AddFast(symbolTable, digit_q);
	knownSymbols->div = SymbolTableInt_AddFast(symbolTable, div);
	knownSymbols->divide_by_zero = SymbolTableInt_AddFast(symbolTable, divide_by_zero);
	knownSymbols->does_not_understand = SymbolTableInt_AddFast(symbolTable, does_not_understand);
	knownSymbols->each = SymbolTableInt_AddFast(symbolTable, each);
	knownSymbols->end = SymbolTableInt_AddFast(symbolTable, end);
	knownSymbols->ends_with = SymbolTableInt_AddFast(symbolTable, ends_with);
	knownSymbols->ends_with_i = SymbolTableInt_AddFast(symbolTable, ends_with_i);
	knownSymbols->escape = SymbolTableInt_AddFast(symbolTable, escape);
	knownSymbols->even_q = SymbolTableInt_AddFast(symbolTable, even_q);
	knownSymbols->eval = SymbolTableInt_AddFast(symbolTable, eval);
	knownSymbols->exit = SymbolTableInt_AddFast(symbolTable, exit_);
	knownSymbols->extend_object = SymbolTableInt_AddFast(symbolTable, extend_object);
	knownSymbols->extend_where_new = SymbolTableInt_AddFast(symbolTable, extend_where_new);
	knownSymbols->exp = SymbolTableInt_AddFast(symbolTable, exp_);
	knownSymbols->false_ = SymbolTableInt_AddFast(symbolTable, false_);
	knownSymbols->filename_mode = SymbolTableInt_AddFast(symbolTable, filename_mode);
	knownSymbols->first = SymbolTableInt_AddFast(symbolTable, first);
	knownSymbols->floor = SymbolTableInt_AddFast(symbolTable, floor_);
	knownSymbols->fn = SymbolTableInt_AddFast(symbolTable, fn);
	knownSymbols->fold = SymbolTableInt_AddFast(symbolTable, fold);
	knownSymbols->from_seed = SymbolTableInt_AddFast(symbolTable, from_seed);
	knownSymbols->get_member = SymbolTableInt_AddFast(symbolTable, get_member);
	knownSymbols->get_object_security = SymbolTableInt_AddFast(symbolTable, get_object_security);
	knownSymbols->get_property = SymbolTableInt_AddFast(symbolTable, get_property);
	knownSymbols->handle_kind = SymbolTableInt_AddFast(symbolTable, handle_kind);
	knownSymbols->hash = SymbolTableInt_AddFast(symbolTable, hash);
	knownSymbols->has_property = SymbolTableInt_AddFast(symbolTable, has_property);
	knownSymbols->hex_string = SymbolTableInt_AddFast(symbolTable, hex_string);
	knownSymbols->hex_string_pretty = SymbolTableInt_AddFast(symbolTable, hex_string_pretty);
	knownSymbols->html_decode = SymbolTableInt_AddFast(symbolTable, html_decode);
	knownSymbols->html_encode = SymbolTableInt_AddFast(symbolTable, html_encode);
	knownSymbols->hyphenize = SymbolTableInt_AddFast(symbolTable, hyphenize);
	knownSymbols->id = SymbolTableInt_AddFast(symbolTable, id);
	knownSymbols->in_ = SymbolTableInt_AddFast(symbolTable, in_);
	knownSymbols->include = SymbolTableInt_AddFast(symbolTable, include);
	knownSymbols->index_of = SymbolTableInt_AddFast(symbolTable, index_of);
	knownSymbols->index_of_i = SymbolTableInt_AddFast(symbolTable, index_of_i);
	knownSymbols->int_ = SymbolTableInt_AddFast(symbolTable, int_);
	knownSymbols->int16_ = SymbolTableInt_AddFast(symbolTable, int16_);
	knownSymbols->int32_ = SymbolTableInt_AddFast(symbolTable, int32_);
	knownSymbols->int64_ = SymbolTableInt_AddFast(symbolTable, int64_);
	knownSymbols->int_lg = SymbolTableInt_AddFast(symbolTable, int_lg);
	knownSymbols->last_index_of = SymbolTableInt_AddFast(symbolTable, last_index_of);
	knownSymbols->last_index_of_i = SymbolTableInt_AddFast(symbolTable, last_index_of_i);
	knownSymbols->latin1_to_utf8 = SymbolTableInt_AddFast(symbolTable, latin1_to_utf8);
	knownSymbols->left = SymbolTableInt_AddFast(symbolTable, left);
	knownSymbols->length = SymbolTableInt_AddFast(symbolTable, length);
	knownSymbols->letter = SymbolTableInt_AddFast(symbolTable, letter);
	knownSymbols->letter_q = SymbolTableInt_AddFast(symbolTable, letter_q);
	knownSymbols->letter_lowercase = SymbolTableInt_AddFast(symbolTable, letter_lowercase);
	knownSymbols->letter_modifier = SymbolTableInt_AddFast(symbolTable, letter_modifier);
	knownSymbols->letter_other = SymbolTableInt_AddFast(symbolTable, letter_other);
	knownSymbols->letter_titlecase = SymbolTableInt_AddFast(symbolTable, letter_titlecase);
	knownSymbols->letter_uppercase = SymbolTableInt_AddFast(symbolTable, letter_uppercase);
	knownSymbols->lg = SymbolTableInt_AddFast(symbolTable, lg);
	knownSymbols->list = SymbolTableInt_AddFast(symbolTable, list);
	knownSymbols->load = SymbolTableInt_AddFast(symbolTable, load);
	knownSymbols->log = SymbolTableInt_AddFast(symbolTable, log_);
	knownSymbols->log_domain = SymbolTableInt_AddFast(symbolTable, log_domain);
	knownSymbols->lower = SymbolTableInt_AddFast(symbolTable, lower);
	knownSymbols->lowercase = SymbolTableInt_AddFast(symbolTable, lowercase);
	knownSymbols->lowercase_q = SymbolTableInt_AddFast(symbolTable, lowercase_q);
	knownSymbols->ln = SymbolTableInt_AddFast(symbolTable, ln);
	knownSymbols->join = SymbolTableInt_AddFast(symbolTable, join);
	knownSymbols->keys = SymbolTableInt_AddFast(symbolTable, keys);
	knownSymbols->kind = SymbolTableInt_AddFast(symbolTable, kind);
	knownSymbols->map = SymbolTableInt_AddFast(symbolTable, map);
	knownSymbols->mark = SymbolTableInt_AddFast(symbolTable, mark);
	knownSymbols->mark_enclosing = SymbolTableInt_AddFast(symbolTable, mark_enclosing);
	knownSymbols->mark_non_spacing = SymbolTableInt_AddFast(symbolTable, mark_non_spacing);
	knownSymbols->mark_spacing_combining = SymbolTableInt_AddFast(symbolTable, mark_spacing_combining);
	knownSymbols->match = SymbolTableInt_AddFast(symbolTable, match);
	knownSymbols->matches = SymbolTableInt_AddFast(symbolTable, matches);
	knownSymbols->max = SymbolTableInt_AddFast(symbolTable, max);
	knownSymbols->message = SymbolTableInt_AddFast(symbolTable, message);
	knownSymbols->mid = SymbolTableInt_AddFast(symbolTable, mid);
	knownSymbols->min = SymbolTableInt_AddFast(symbolTable, min);
	knownSymbols->mod = SymbolTableInt_AddFast(symbolTable, mod);
	knownSymbols->name = SymbolTableInt_AddFast(symbolTable, name);
	knownSymbols->neg_q = SymbolTableInt_AddFast(symbolTable, neg_q);
	knownSymbols->newline_q = SymbolTableInt_AddFast(symbolTable, newline_q);
	knownSymbols->next_pow2 = SymbolTableInt_AddFast(symbolTable, next_pow2);
	knownSymbols->normalize_diacritics = SymbolTableInt_AddFast(symbolTable, normalize_diacritics);
	knownSymbols->nth = SymbolTableInt_AddFast(symbolTable, nth);
	knownSymbols->nth_cell = SymbolTableInt_AddFast(symbolTable, nth_cell);
	knownSymbols->null_ = SymbolTableInt_AddFast(symbolTable, null_);
	knownSymbols->number = SymbolTableInt_AddFast(symbolTable, number);
	knownSymbols->number_decimal_digit = SymbolTableInt_AddFast(symbolTable, number_decimal_digit);
	knownSymbols->number_letter = SymbolTableInt_AddFast(symbolTable, number_letter);
	knownSymbols->number_other = SymbolTableInt_AddFast(symbolTable, number_other);
	knownSymbols->numeric_q = SymbolTableInt_AddFast(symbolTable, numeric_q);
	knownSymbols->octal_q = SymbolTableInt_AddFast(symbolTable, octal_q);
	knownSymbols->of = SymbolTableInt_AddFast(symbolTable, of);
	knownSymbols->of_size = SymbolTableInt_AddFast(symbolTable, of_size);
	knownSymbols->odd_q = SymbolTableInt_AddFast(symbolTable, odd_q);
	knownSymbols->one_q = SymbolTableInt_AddFast(symbolTable, one_q);
	knownSymbols->options = SymbolTableInt_AddFast(symbolTable, options);
	knownSymbols->other = SymbolTableInt_AddFast(symbolTable, other);
	knownSymbols->other_control = SymbolTableInt_AddFast(symbolTable, other_control);
	knownSymbols->other_format = SymbolTableInt_AddFast(symbolTable, other_format);
	knownSymbols->other_not_assigned = SymbolTableInt_AddFast(symbolTable, other_not_assigned);
	knownSymbols->other_private_use = SymbolTableInt_AddFast(symbolTable, other_private_use);
	knownSymbols->other_surrogate = SymbolTableInt_AddFast(symbolTable, other_surrogate);
	knownSymbols->parity = SymbolTableInt_AddFast(symbolTable, parity);
	knownSymbols->parse = SymbolTableInt_AddFast(symbolTable, parse);
	knownSymbols->parse_and_eval = SymbolTableInt_AddFast(symbolTable, parse_and_eval);
	knownSymbols->pos_q = SymbolTableInt_AddFast(symbolTable, pos_q);
	knownSymbols->post = SymbolTableInt_AddFast(symbolTable, post);
	knownSymbols->pow2_q = SymbolTableInt_AddFast(symbolTable, pow2_q);
	knownSymbols->pre = SymbolTableInt_AddFast(symbolTable, pre);
	knownSymbols->primary_category = SymbolTableInt_AddFast(symbolTable, primary_category);
	knownSymbols->printf = SymbolTableInt_AddFast(symbolTable, printf);
	knownSymbols->process_id = SymbolTableInt_AddFast(symbolTable, process_id);
	knownSymbols->property_names = SymbolTableInt_AddFast(symbolTable, property_names);
	knownSymbols->punct_q = SymbolTableInt_AddFast(symbolTable, punct_q);
	knownSymbols->punctuation = SymbolTableInt_AddFast(symbolTable, punctuation);
	knownSymbols->punctuation_close = SymbolTableInt_AddFast(symbolTable, punctuation_close);
	knownSymbols->punctuation_connector = SymbolTableInt_AddFast(symbolTable, punctuation_connector);
	knownSymbols->punctuation_dash = SymbolTableInt_AddFast(symbolTable, punctuation_dash);
	knownSymbols->punctuation_final_quote = SymbolTableInt_AddFast(symbolTable, punctuation_final_quote);
	knownSymbols->punctuation_initial_quote = SymbolTableInt_AddFast(symbolTable, punctuation_initial_quote);
	knownSymbols->punctuation_open = SymbolTableInt_AddFast(symbolTable, punctuation_open);
	knownSymbols->punctuation_other = SymbolTableInt_AddFast(symbolTable, punctuation_other);
	knownSymbols->raw_reverse = SymbolTableInt_AddFast(symbolTable, raw_reverse);
	knownSymbols->read_append = SymbolTableInt_AddFast(symbolTable, read_append);
	knownSymbols->read_only = SymbolTableInt_AddFast(symbolTable, read_only);
	knownSymbols->read_write = SymbolTableInt_AddFast(symbolTable, read_write);
	knownSymbols->read_write_append = SymbolTableInt_AddFast(symbolTable, read_write_append);
	knownSymbols->real_ = SymbolTableInt_AddFast(symbolTable, real_);
	knownSymbols->real32_ = SymbolTableInt_AddFast(symbolTable, real32_);
	knownSymbols->real64_ = SymbolTableInt_AddFast(symbolTable, real64_);
	knownSymbols->rem = SymbolTableInt_AddFast(symbolTable, rem);
	knownSymbols->replace = SymbolTableInt_AddFast(symbolTable, replace);
	knownSymbols->resize = SymbolTableInt_AddFast(symbolTable, resize);
	knownSymbols->rest = SymbolTableInt_AddFast(symbolTable, rest);
	knownSymbols->reverse = SymbolTableInt_AddFast(symbolTable, reverse);
	knownSymbols->reverse_bits = SymbolTableInt_AddFast(symbolTable, reverse_bits);
	knownSymbols->reverse_bytes = SymbolTableInt_AddFast(symbolTable, reverse_bytes);
	knownSymbols->right = SymbolTableInt_AddFast(symbolTable, right);
	knownSymbols->rot_13 = SymbolTableInt_AddFast(symbolTable, rot_13);
	knownSymbols->result = SymbolTableInt_AddFast(symbolTable, result);
	knownSymbols->separator = SymbolTableInt_AddFast(symbolTable, separator);
	knownSymbols->separator_line = SymbolTableInt_AddFast(symbolTable, separator_line);
	knownSymbols->separator_paragraph = SymbolTableInt_AddFast(symbolTable, separator_paragraph);
	knownSymbols->separator_space = SymbolTableInt_AddFast(symbolTable, separator_space);
	knownSymbols->set_member = SymbolTableInt_AddFast(symbolTable, set_member);
	knownSymbols->set_object_security = SymbolTableInt_AddFast(symbolTable, set_object_security);
	knownSymbols->set_property = SymbolTableInt_AddFast(symbolTable, set_property);
	knownSymbols->sign = SymbolTableInt_AddFast(symbolTable, sign);
	knownSymbols->sin = SymbolTableInt_AddFast(symbolTable, sin_);
	knownSymbols->space_q = SymbolTableInt_AddFast(symbolTable, space_q);
	knownSymbols->splice = SymbolTableInt_AddFast(symbolTable, splice);
	knownSymbols->split = SymbolTableInt_AddFast(symbolTable, split);
	knownSymbols->sprintf = SymbolTableInt_AddFast(symbolTable, sprintf);
	knownSymbols->sqrt = SymbolTableInt_AddFast(symbolTable, sqrt_);
	knownSymbols->sqrt_domain = SymbolTableInt_AddFast(symbolTable, sqrt_domain);
	knownSymbols->start = SymbolTableInt_AddFast(symbolTable, start);
	knownSymbols->starts_with = SymbolTableInt_AddFast(symbolTable, starts_with);
	knownSymbols->starts_with_i = SymbolTableInt_AddFast(symbolTable, starts_with_i);
	knownSymbols->step = SymbolTableInt_AddFast(symbolTable, step);
	knownSymbols->stepping = SymbolTableInt_AddFast(symbolTable, stepping);
	knownSymbols->strip_c_slashes = SymbolTableInt_AddFast(symbolTable, strip_c_slashes);
	knownSymbols->string_ = SymbolTableInt_AddFast(symbolTable, string_);
	knownSymbols->studied_ = SymbolTableInt_AddFast(symbolTable, studied_);
	knownSymbols->study = SymbolTableInt_AddFast(symbolTable, study);
	knownSymbols->substr = SymbolTableInt_AddFast(symbolTable, substr);
	knownSymbols->substring = SymbolTableInt_AddFast(symbolTable, substring);
	knownSymbols->symbol = SymbolTableInt_AddFast(symbolTable, symbol);
	knownSymbols->symbol_currency = SymbolTableInt_AddFast(symbolTable, symbol_currency);
	knownSymbols->symbol_math = SymbolTableInt_AddFast(symbolTable, symbol_math);
	knownSymbols->symbol_modifier = SymbolTableInt_AddFast(symbolTable, symbol_modifier);
	knownSymbols->symbol_other = SymbolTableInt_AddFast(symbolTable, symbol_other);
	knownSymbols->tan = SymbolTableInt_AddFast(symbolTable, tan_);
	knownSymbols->text = SymbolTableInt_AddFast(symbolTable, text);
	knownSymbols->this_ = SymbolTableInt_AddFast(symbolTable, this_);
	knownSymbols->this_closure = SymbolTableInt_AddFast(symbolTable, this_closure);
	knownSymbols->throw_ = SymbolTableInt_AddFast(symbolTable, throw_);
	knownSymbols->title = SymbolTableInt_AddFast(symbolTable, title);
	knownSymbols->titlecase = SymbolTableInt_AddFast(symbolTable, titlecase);
	knownSymbols->titlecase_q = SymbolTableInt_AddFast(symbolTable, titlecase_q);
	knownSymbols->trim = SymbolTableInt_AddFast(symbolTable, trim);
	knownSymbols->trim_end = SymbolTableInt_AddFast(symbolTable, trim_end);
	knownSymbols->trim_start = SymbolTableInt_AddFast(symbolTable, trim_start);
	knownSymbols->true_ = SymbolTableInt_AddFast(symbolTable, true_);
	knownSymbols->type = SymbolTableInt_AddFast(symbolTable, type);
	knownSymbols->uchar = SymbolTableInt_AddFast(symbolTable, uchar);
	knownSymbols->underscorize = SymbolTableInt_AddFast(symbolTable, underscorize);
	knownSymbols->unknown = SymbolTableInt_AddFast(symbolTable, unknown);
	knownSymbols->upper = SymbolTableInt_AddFast(symbolTable, upper);
	knownSymbols->uppercase = SymbolTableInt_AddFast(symbolTable, uppercase);
	knownSymbols->uppercase_q = SymbolTableInt_AddFast(symbolTable, uppercase_q);
	knownSymbols->url_decode = SymbolTableInt_AddFast(symbolTable, url_decode);
	knownSymbols->url_encode = SymbolTableInt_AddFast(symbolTable, url_encode);
	knownSymbols->url_query_encode = SymbolTableInt_AddFast(symbolTable, url_query_encode);
	knownSymbols->utf8_to_latin1 = SymbolTableInt_AddFast(symbolTable, utf8_to_latin1);
	knownSymbols->values = SymbolTableInt_AddFast(symbolTable, values);
	knownSymbols->where_ = SymbolTableInt_AddFast(symbolTable, where_);
	knownSymbols->whitespace_q = SymbolTableInt_AddFast(symbolTable, whitespace_q);
	knownSymbols->wildcard_matches = SymbolTableInt_AddFast(symbolTable, wildcard_matches);
	knownSymbols->without = SymbolTableInt_AddFast(symbolTable, without);
	knownSymbols->xdigit_q = SymbolTableInt_AddFast(symbolTable, xdigit_q);
	knownSymbols->xor = SymbolTableInt_AddFast(symbolTable, xor);
	knownSymbols->zero_q = SymbolTableInt_AddFast(symbolTable, zero_q);
}

//-------------------------------------------------------------------------------------------------
//  Error symbols.

STATIC_STRING(compile_error, "compile-error", 13);
STATIC_STRING(configuration_error, "configuration-error", 19);
STATIC_STRING(eval_error, "eval-error", 10);
STATIC_STRING(exec_error, "exec-error", 10);
STATIC_STRING(json_error, "json-error", 10);
STATIC_STRING(lexer_error, "lexer-error", 11);
STATIC_STRING(load_error, "load-error", 10);
STATIC_STRING(native_method_error, "native-method-error", 19);
STATIC_STRING(object_security_error, "object-security-error", 21);
STATIC_STRING(post_condition_assertion, "post-condition-assertion", 24);
STATIC_STRING(pre_condition_assertion, "pre-condition-assertion", 23);
STATIC_STRING(property_error, "property-error", 14);
STATIC_STRING(syntax_error, "syntax-error", 12);
STATIC_STRING(system_exception, "system-exception", 16);
STATIC_STRING(type_assertion, "type-assertion", 14);
STATIC_STRING(user_exception, "user-exception", 14);

static void KnownSymbolsInt_PreloadErrorSymbols(SymbolTable symbolTable, KnownSymbols knownSymbols)
{
	knownSymbols->compile_error = SymbolTableInt_AddFast(symbolTable, compile_error);
	knownSymbols->configuration_error = SymbolTableInt_AddFast(symbolTable, configuration_error);
	knownSymbols->eval_error = SymbolTableInt_AddFast(symbolTable, eval_error);
	knownSymbols->exec_error = SymbolTableInt_AddFast(symbolTable, exec_error);
	knownSymbols->json_error = SymbolTableInt_AddFast(symbolTable, json_error);
	knownSymbols->lexer_error = SymbolTableInt_AddFast(symbolTable, lexer_error);
	knownSymbols->load_error = SymbolTableInt_AddFast(symbolTable, load_error);
	knownSymbols->native_method_error = SymbolTableInt_AddFast(symbolTable, native_method_error);
	knownSymbols->object_security_error = SymbolTableInt_AddFast(symbolTable, object_security_error);
	knownSymbols->post_condition_assertion = SymbolTableInt_AddFast(symbolTable, post_condition_assertion);
	knownSymbols->pre_condition_assertion = SymbolTableInt_AddFast(symbolTable, pre_condition_assertion);
	knownSymbols->property_error = SymbolTableInt_AddFast(symbolTable, property_error);
	knownSymbols->syntax_error = SymbolTableInt_AddFast(symbolTable, syntax_error);
	knownSymbols->system_exception = SymbolTableInt_AddFast(symbolTable, system_exception);
	knownSymbols->type_assertion = SymbolTableInt_AddFast(symbolTable, type_assertion);
	knownSymbols->user_exception = SymbolTableInt_AddFast(symbolTable, user_exception);
}

//-------------------------------------------------------------------------------------------------
//  Public API.

void KnownSymbols_PreloadSymbolTable(SymbolTable symbolTable, KnownSymbols knownSymbols)
{
	struct SymbolTableInt *table = (struct SymbolTableInt *)symbolTable;
	if (table->count != 1)
		Smile_Abort_FatalError("Cannot preload symbol table: Symbol table must be empty to be preloaded.");
	if (table->max < 1024)
		Smile_Abort_FatalError("Cannot preload symbol table: Symbol table is too small for preloading.");

	KnownSymbolsInt_PreloadSpecials(symbolTable, knownSymbols);
	KnownSymbolsInt_PreloadCommonOperators(symbolTable, knownSymbols);
	KnownSymbolsInt_PreloadTypenames(symbolTable, knownSymbols);
	KnownSymbolsInt_PreloadGeneralSymbols(symbolTable, knownSymbols);
	KnownSymbolsInt_PreloadErrorSymbols(symbolTable, knownSymbols);
}
