// THIS IS A GENERATED FILE.  DO NOT EDIT!

#define BUILD_STR_HELPER(x) #x
#define BUILD_STR(x) BUILD_STR_HELPER(x)

#define BUILDNUM 169
#define BUILDDATE "2016-10-15"
#define BUILDSTRING ("r" BUILD_STR(BUILDNUM) " / " BUILDDATE)
