//---------------------------------------------------------------------------------------
//  Smile Programming Language Interpreter
//  Copyright 2004-2019 Sean Werkema
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//---------------------------------------------------------------------------------------

//--------------------------------------------------------------
// WARNING: This file was generated automatically. Do not edit!
//
// The contents of this file are aggregated from data files
// provided by the Unicode Consortium, www.unicode.org.
//--------------------------------------------------------------

#include <smile/internal/html.h>

/// <summary>
/// Convert the given name to its HTML entity value.  This is AUTO-GENERATED, and uses an optimized
/// decision tree that runs in O(n) time to convert the string as quickly as possible.
/// </summary>
/// <param name="name">The name of the HTML entity to look up.</param>
/// <returns>The value for that entity, if it is an entity with a value, or -1 if there is no such entity.</returns>
Int32 HtmlEntityNameToValue(const Byte *src, Int length)
{
	Byte ch;

	if (src == NULL) return -1;

	if (length-- <= 0) return -1;
	switch (*src++) {
		case 'A':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'E':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 198;
					break;
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 193;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 194;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 192;
					break;
				case 'l':
					if (length-- >= 0 && *src++ == 'p')
						if (length-- >= 0 && *src++ == 'h')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 913;
					break;
				case 'r':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'n')
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 197;
					break;
				case 't':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'l')
							if (length-- >= 0 && *src++ == 'd')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 195;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 196;
					break;
			}
			break;
		case 'B':
			if (length-- >= 0 && *src++ == 'e')
				if (length-- >= 0 && *src++ == 't')
					if (length-- >= 0 && *src++ == 'a')
						if (length <= 0) return 914;
			break;
		case 'C':
			if (length-- <= 0) return -1;
			if ((ch = *src++) == 'c') {
				if (length-- >= 0 && *src++ == 'e')
					if (length-- >= 0 && *src++ == 'd')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'l')
								if (length <= 0) return 199;
			}
			else if (ch == 'h') {
				if (length-- >= 0 && *src++ == 'i')
					if (length <= 0) return 935;
			}
			break;
		case 'D':
			if (length-- <= 0) return -1;
			if ((ch = *src++) == 'a') {
				if (length-- >= 0 && *src++ == 'g')
					if (length-- >= 0 && *src++ == 'g')
						if (length-- >= 0 && *src++ == 'e')
							if (length-- >= 0 && *src++ == 'r')
								if (length <= 0) return 8225;
			}
			else if (ch == 'e') {
				if (length-- >= 0 && *src++ == 'l')
					if (length-- >= 0 && *src++ == 't')
						if (length-- >= 0 && *src++ == 'a')
							if (length <= 0) return 916;
			}
			break;
		case 'E':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'T':
					if (length-- >= 0 && *src++ == 'H')
						if (length <= 0) return 208;
					break;
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 201;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 202;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 200;
					break;
				case 'p':
					if (length-- >= 0 && *src++ == 's')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'l')
								if (length-- >= 0 && *src++ == 'o')
									if (length-- >= 0 && *src++ == 'n')
										if (length <= 0) return 917;
					break;
				case 't':
					if (length-- >= 0 && *src++ == 'a')
						if (length <= 0) return 919;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 203;
					break;
			}
			break;
		case 'G':
			if (length-- >= 0 && *src++ == 'a')
				if (length-- >= 0 && *src++ == 'm')
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'a')
							if (length <= 0) return 915;
			break;
		case 'I':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 205;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 206;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 204;
					break;
				case 'o':
					if (length-- >= 0 && *src++ == 't')
						if (length-- >= 0 && *src++ == 'a')
							if (length <= 0) return 921;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 207;
					break;
			}
			break;
		case 'K':
			if (length-- >= 0 && *src++ == 'a')
				if (length-- >= 0 && *src++ == 'p')
					if (length-- >= 0 && *src++ == 'p')
						if (length-- >= 0 && *src++ == 'a')
							if (length <= 0) return 922;
			break;
		case 'L':
			if (length-- >= 0 && *src++ == 'a')
				if (length-- >= 0 && *src++ == 'm')
					if (length-- >= 0 && *src++ == 'b')
						if (length-- >= 0 && *src++ == 'd')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 923;
			break;
		case 'M':
			if (length-- >= 0 && *src++ == 'u')
				if (length <= 0) return 924;
			break;
		case 'N':
			if (length-- <= 0) return -1;
			if ((ch = *src++) == 't') {
				if (length-- >= 0 && *src++ == 'i')
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'd')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 209;
			}
			else if (ch == 'u') {
				if (length <= 0) return 925;
			}
			break;
		case 'O':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'E':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 338;
					break;
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 211;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 212;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 210;
					break;
				case 'm':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'e') {
						if (length-- >= 0 && *src++ == 'g')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 937;
					}
					else if (ch == 'i') {
						if (length-- >= 0 && *src++ == 'c')
							if (length-- >= 0 && *src++ == 'r')
								if (length-- >= 0 && *src++ == 'o')
									if (length-- >= 0 && *src++ == 'n')
										if (length <= 0) return 927;
					}
					break;
				case 's':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 's')
								if (length-- >= 0 && *src++ == 'h')
									if (length <= 0) return 216;
					break;
				case 't':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'l')
							if (length-- >= 0 && *src++ == 'd')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 213;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 214;
					break;
			}
			break;
		case 'P':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'h':
					if (length-- >= 0 && *src++ == 'i')
						if (length <= 0) return 934;
					break;
				case 'i':
					if (length <= 0) return 928;
					break;
				case 'r':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'm')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 8243;
					break;
				case 's':
					if (length-- >= 0 && *src++ == 'i')
						if (length <= 0) return 936;
					break;
			}
			break;
		case 'R':
			if (length-- >= 0 && *src++ == 'h')
				if (length-- >= 0 && *src++ == 'o')
					if (length <= 0) return 929;
			break;
		case 'S':
			if (length-- <= 0) return -1;
			if ((ch = *src++) == 'c') {
				if (length-- >= 0 && *src++ == 'a')
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'o')
							if (length-- >= 0 && *src++ == 'n')
								if (length <= 0) return 352;
			}
			else if (ch == 'i') {
				if (length-- >= 0 && *src++ == 'g')
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'a')
							if (length <= 0) return 931;
			}
			break;
		case 'T':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'H':
					if (length-- >= 0 && *src++ == 'O')
						if (length-- >= 0 && *src++ == 'R')
							if (length-- >= 0 && *src++ == 'N')
								if (length <= 0) return 222;
					break;
				case 'a':
					if (length-- >= 0 && *src++ == 'u')
						if (length <= 0) return 932;
					break;
				case 'h':
					if (length-- >= 0 && *src++ == 'e')
						if (length-- >= 0 && *src++ == 't')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 920;
					break;
			}
			break;
		case 'U':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 218;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 219;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 217;
					break;
				case 'p':
					if (length-- >= 0 && *src++ == 's')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'l')
								if (length-- >= 0 && *src++ == 'o')
									if (length-- >= 0 && *src++ == 'n')
										if (length <= 0) return 933;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 220;
					break;
			}
			break;
		case 'X':
			if (length-- >= 0 && *src++ == 'i')
				if (length <= 0) return 926;
			break;
		case 'Y':
			if (length-- <= 0) return -1;
			if ((ch = *src++) == 'a') {
				if (length-- >= 0 && *src++ == 'c')
					if (length-- >= 0 && *src++ == 'u')
						if (length-- >= 0 && *src++ == 't')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 221;
			}
			else if (ch == 'u') {
				if (length-- >= 0 && *src++ == 'm')
					if (length-- >= 0 && *src++ == 'l')
						if (length <= 0) return 376;
			}
			break;
		case 'Z':
			if (length-- >= 0 && *src++ == 'e')
				if (length-- >= 0 && *src++ == 't')
					if (length-- >= 0 && *src++ == 'a')
						if (length <= 0) return 918;
			break;
		case 'a':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 225;
					break;
				case 'c':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'i') {
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 226;
					}
					else if (ch == 'u') {
						if (length-- >= 0 && *src++ == 't')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 180;
					}
					break;
				case 'e':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 230;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 224;
					break;
				case 'l':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'e') {
						if (length-- >= 0 && *src++ == 'f')
							if (length-- >= 0 && *src++ == 's')
								if (length-- >= 0 && *src++ == 'y')
									if (length-- >= 0 && *src++ == 'm')
										if (length <= 0) return 8501;
					}
					else if (ch == 'p') {
						if (length-- >= 0 && *src++ == 'h')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 945;
					}
					break;
				case 'm':
					if (length-- >= 0 && *src++ == 'p')
						if (length <= 0) return 38;
					break;
				case 'n':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'd') {
						if (length <= 0) return 8743;
					}
					else if (ch == 'g') {
						if (length <= 0) return 8736;
					}
					break;
				case 'p':
					if (length-- >= 0 && *src++ == 'o')
						if (length-- >= 0 && *src++ == 's')
							if (length <= 0) return 39;
					break;
				case 'r':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'n')
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 229;
					break;
				case 's':
					if (length-- >= 0 && *src++ == 'y')
						if (length-- >= 0 && *src++ == 'm')
							if (length-- >= 0 && *src++ == 'p')
								if (length <= 0) return 8776;
					break;
				case 't':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'l')
							if (length-- >= 0 && *src++ == 'd')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 227;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 228;
					break;
			}
			break;
		case 'b':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'd':
					if (length-- >= 0 && *src++ == 'q')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 'o')
								if (length <= 0) return 8222;
					break;
				case 'e':
					if (length-- >= 0 && *src++ == 't')
						if (length-- >= 0 && *src++ == 'a')
							if (length <= 0) return 946;
					break;
				case 'r':
					if (length-- >= 0 && *src++ == 'v')
						if (length-- >= 0 && *src++ == 'b')
							if (length-- >= 0 && *src++ == 'a')
								if (length-- >= 0 && *src++ == 'r')
									if (length <= 0) return 166;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 8226;
					break;
			}
			break;
		case 'c':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'p')
						if (length <= 0) return 8745;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'e')
						if (length-- >= 0 && *src++ == 'd')
							if (length-- >= 0 && *src++ == 'i')
								if (length-- >= 0 && *src++ == 'l')
									if (length <= 0) return 231;
					break;
				case 'e':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'd') {
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'l')
								if (length <= 0) return 184;
					}
					else if (ch == 'n') {
						if (length-- >= 0 && *src++ == 't')
							if (length <= 0) return 162;
					}
					break;
				case 'h':
					if (length-- >= 0 && *src++ == 'i')
						if (length <= 0) return 967;
					break;
				case 'i':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'c')
							if (length <= 0) return 710;
					break;
				case 'l':
					if (length-- >= 0 && *src++ == 'u')
						if (length-- >= 0 && *src++ == 'b')
							if (length-- >= 0 && *src++ == 's')
								if (length <= 0) return 9827;
					break;
				case 'o':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'n') {
						if (length-- >= 0 && *src++ == 'g')
							if (length <= 0) return 8773;
					}
					else if (ch == 'p') {
						if (length-- >= 0 && *src++ == 'y')
							if (length <= 0) return 169;
					}
					break;
				case 'r':
					if (length-- >= 0 && *src++ == 'a')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'r')
								if (length <= 0) return 8629;
					break;
				case 'u':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'p') {
						if (length <= 0) return 8746;
					}
					else if (ch == 'r') {
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'e')
								if (length-- >= 0 && *src++ == 'n')
									if (length <= 0) return 164;
					}
					break;
			}
			break;
		case 'd':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'A':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 8659;
					break;
				case 'a':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'g') {
						if (length-- >= 0 && *src++ == 'g')
							if (length-- >= 0 && *src++ == 'e')
								if (length-- >= 0 && *src++ == 'r')
									if (length <= 0) return 8224;
					}
					else if (ch == 'r') {
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 8595;
					}
					break;
				case 'e':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'g') {
						if (length <= 0) return 176;
					}
					else if (ch == 'l') {
						if (length-- >= 0 && *src++ == 't')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 948;
					}
					break;
				case 'i':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'a') {
						if (length-- >= 0 && *src++ == 'm')
							if (length-- >= 0 && *src++ == 's')
								if (length <= 0) return 9830;
					}
					else if (ch == 'v') {
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'd')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 247;
					}
					break;
			}
			break;
		case 'e':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 233;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 234;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 232;
					break;
				case 'm':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'p') {
						if (length-- >= 0 && *src++ == 't')
							if (length-- >= 0 && *src++ == 'y')
								if (length <= 0) return 8709;
					}
					else if (ch == 's') {
						if (length-- >= 0 && *src++ == 'p')
							if (length <= 0) return 8195;
					}
					break;
				case 'n':
					if (length-- >= 0 && *src++ == 's')
						if (length-- >= 0 && *src++ == 'p')
							if (length <= 0) return 8194;
					break;
				case 'p':
					if (length-- >= 0 && *src++ == 's')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'l')
								if (length-- >= 0 && *src++ == 'o')
									if (length-- >= 0 && *src++ == 'n')
										if (length <= 0) return 949;
					break;
				case 'q':
					if (length-- >= 0 && *src++ == 'u')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'v')
								if (length <= 0) return 8801;
					break;
				case 't':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'a') {
						if (length <= 0) return 951;
					}
					else if (ch == 'h') {
						if (length <= 0) return 240;
					}
					break;
				case 'u':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'm') {
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 235;
					}
					else if (ch == 'r') {
						if (length-- >= 0 && *src++ == 'o')
							if (length <= 0) return 8364;
					}
					break;
				case 'x':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 's')
							if (length-- >= 0 && *src++ == 't')
								if (length <= 0) return 8707;
					break;
			}
			break;
		case 'f':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'n':
					if (length-- >= 0 && *src++ == 'o')
						if (length-- >= 0 && *src++ == 'f')
							if (length <= 0) return 402;
					break;
				case 'o':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'l')
								if (length-- >= 0 && *src++ == 'l')
									if (length <= 0) return 8704;
					break;
				case 'r':
					if (length-- >= 0 && *src++ == 'a') {
						if (length-- <= 0) return -1;
						if ((ch = *src++) == 'c') {
							if (length-- <= 0) return -1;
							if ((ch = *src++) == '1') {
								if (length-- <= 0) return -1;
								if ((ch = *src++) == '2') {
									if (length <= 0) return 189;
								}
								else if (ch == '4') {
									if (length <= 0) return 188;
								}
							}
							else if (ch == '3') {
								if (length-- >= 0 && *src++ == '4')
									if (length <= 0) return 190;
							}
						}
						else if (ch == 's') {
							if (length-- >= 0 && *src++ == 'l')
								if (length <= 0) return 8260;
						}
					}
					break;
			}
			break;
		case 'g':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'm')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 947;
					break;
				case 'e':
					if (length <= 0) return 8805;
					break;
				case 't':
					if (length <= 0) return 62;
					break;
			}
			break;
		case 'h':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'A':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 8660;
					break;
				case 'a':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 8596;
					break;
				case 'e':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'a') {
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 's')
									if (length <= 0) return 9829;
					}
					else if (ch == 'l') {
						if (length-- >= 0 && *src++ == 'l')
							if (length-- >= 0 && *src++ == 'i')
								if (length-- >= 0 && *src++ == 'p')
									if (length <= 0) return 8230;
					}
					break;
			}
			break;
		case 'i':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 237;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 238;
					break;
				case 'e':
					if (length-- >= 0 && *src++ == 'x')
						if (length-- >= 0 && *src++ == 'c')
							if (length-- >= 0 && *src++ == 'l')
								if (length <= 0) return 161;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 236;
					break;
				case 'm':
					if (length-- >= 0 && *src++ == 'a')
						if (length-- >= 0 && *src++ == 'g')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 8465;
					break;
				case 'n':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'f') {
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'n')
								if (length <= 0) return 8734;
					}
					else if (ch == 't') {
						if (length <= 0) return 8747;
					}
					break;
				case 'o':
					if (length-- >= 0 && *src++ == 't')
						if (length-- >= 0 && *src++ == 'a')
							if (length <= 0) return 953;
					break;
				case 'q':
					if (length-- >= 0 && *src++ == 'u')
						if (length-- >= 0 && *src++ == 'e')
							if (length-- >= 0 && *src++ == 's')
								if (length-- >= 0 && *src++ == 't')
									if (length <= 0) return 191;
					break;
				case 's':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'n')
							if (length <= 0) return 8712;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 239;
					break;
			}
			break;
		case 'k':
			if (length-- >= 0 && *src++ == 'a')
				if (length-- >= 0 && *src++ == 'p')
					if (length-- >= 0 && *src++ == 'p')
						if (length-- >= 0 && *src++ == 'a')
							if (length <= 0) return 954;
			break;
		case 'l':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'A':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 8656;
					break;
				case 'a':
					if (length-- <= 0) return -1;
					switch (*src++) {
						case 'm':
							if (length-- >= 0 && *src++ == 'b')
								if (length-- >= 0 && *src++ == 'd')
									if (length-- >= 0 && *src++ == 'a')
										if (length <= 0) return 955;
							break;
						case 'n':
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 9001;
							break;
						case 'q':
							if (length-- >= 0 && *src++ == 'u')
								if (length-- >= 0 && *src++ == 'o')
									if (length <= 0) return 171;
							break;
						case 'r':
							if (length-- >= 0 && *src++ == 'r')
								if (length <= 0) return 8592;
							break;
					}
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'e')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'l')
								if (length <= 0) return 8968;
					break;
				case 'd':
					if (length-- >= 0 && *src++ == 'q')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 'o')
								if (length <= 0) return 8220;
					break;
				case 'e':
					if (length <= 0) return 8804;
					break;
				case 'f':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'o')
							if (length-- >= 0 && *src++ == 'o')
								if (length-- >= 0 && *src++ == 'r')
									if (length <= 0) return 8970;
					break;
				case 'o':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'w') {
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 's')
								if (length-- >= 0 && *src++ == 't')
									if (length <= 0) return 8727;
					}
					else if (ch == 'z') {
						if (length <= 0) return 9674;
					}
					break;
				case 'r':
					if (length-- >= 0 && *src++ == 'm')
						if (length <= 0) return 8206;
					break;
				case 's':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'a') {
						if (length-- >= 0 && *src++ == 'q')
							if (length-- >= 0 && *src++ == 'u')
								if (length-- >= 0 && *src++ == 'o')
									if (length <= 0) return 8249;
					}
					else if (ch == 'q') {
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 'o')
								if (length <= 0) return 8216;
					}
					break;
				case 't':
					if (length <= 0) return 60;
					break;
			}
			break;
		case 'm':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 175;
					break;
				case 'd':
					if (length-- >= 0 && *src++ == 'a')
						if (length-- >= 0 && *src++ == 's')
							if (length-- >= 0 && *src++ == 'h')
								if (length <= 0) return 8212;
					break;
				case 'i':
					if (length-- <= 0) return -1;
					switch (*src++) {
						case 'c':
							if (length-- >= 0 && *src++ == 'r')
								if (length-- >= 0 && *src++ == 'o')
									if (length <= 0) return 181;
							break;
						case 'd':
							if (length-- >= 0 && *src++ == 'd')
								if (length-- >= 0 && *src++ == 'o')
									if (length-- >= 0 && *src++ == 't')
										if (length <= 0) return 183;
							break;
						case 'n':
							if (length-- >= 0 && *src++ == 'u')
								if (length-- >= 0 && *src++ == 's')
									if (length <= 0) return 8722;
							break;
					}
					break;
				case 'u':
					if (length <= 0) return 956;
					break;
			}
			break;
		case 'n':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'b')
						if (length-- >= 0 && *src++ == 'l')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 8711;
					break;
				case 'b':
					if (length-- >= 0 && *src++ == 's')
						if (length-- >= 0 && *src++ == 'p')
							if (length <= 0) return 160;
					break;
				case 'd':
					if (length-- >= 0 && *src++ == 'a')
						if (length-- >= 0 && *src++ == 's')
							if (length-- >= 0 && *src++ == 'h')
								if (length <= 0) return 8211;
					break;
				case 'e':
					if (length <= 0) return 8800;
					break;
				case 'i':
					if (length <= 0) return 8715;
					break;
				case 'o':
					if (length-- >= 0 && *src++ == 't') {
						if (length <= 0) return 172;
					}
					break;
				case 's':
					if (length-- >= 0 && *src++ == 'u')
						if (length-- >= 0 && *src++ == 'b')
							if (length <= 0) return 8836;
					break;
				case 't':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'l')
							if (length-- >= 0 && *src++ == 'd')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 241;
					break;
				case 'u':
					if (length <= 0) return 957;
					break;
			}
			break;
		case 'o':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 243;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 244;
					break;
				case 'e':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 339;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 242;
					break;
				case 'l':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'n')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 8254;
					break;
				case 'm':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'e') {
						if (length-- >= 0 && *src++ == 'g')
							if (length-- >= 0 && *src++ == 'a')
								if (length <= 0) return 969;
					}
					else if (ch == 'i') {
						if (length-- >= 0 && *src++ == 'c')
							if (length-- >= 0 && *src++ == 'r')
								if (length-- >= 0 && *src++ == 'o')
									if (length-- >= 0 && *src++ == 'n')
										if (length <= 0) return 959;
					}
					break;
				case 'p':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 's')
								if (length <= 0) return 8853;
					break;
				case 'r':
					if (length <= 0) return 8744;
					break;
				case 's':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 's')
								if (length-- >= 0 && *src++ == 'h')
									if (length <= 0) return 248;
					break;
				case 't':
					if (length-- >= 0 && *src++ == 'i') {
						if (length-- <= 0) return -1;
						if ((ch = *src++) == 'l') {
							if (length-- >= 0 && *src++ == 'd')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 245;
						}
						else if (ch == 'm') {
							if (length-- >= 0 && *src++ == 'e')
								if (length-- >= 0 && *src++ == 's')
									if (length <= 0) return 8855;
						}
					}
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 246;
					break;
			}
			break;
		case 'p':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'r') {
						if (length-- <= 0) return -1;
						if ((ch = *src++) == 'a') {
							if (length <= 0) return 182;
						}
						else if (ch == 't') {
							if (length <= 0) return 8706;
						}
					}
					break;
				case 'e':
					if (length-- >= 0 && *src++ == 'r') {
						if (length-- <= 0) return -1;
						if ((ch = *src++) == 'm') {
							if (length-- >= 0 && *src++ == 'i')
								if (length-- >= 0 && *src++ == 'l')
									if (length <= 0) return 8240;
						}
						else if (ch == 'p') {
							if (length <= 0) return 8869;
						}
					}
					break;
				case 'h':
					if (length-- >= 0 && *src++ == 'i')
						if (length <= 0) return 966;
					break;
				case 'i':
					if (length <= 0) return 960;
					break;
				case 'l':
					if (length-- >= 0 && *src++ == 'u')
						if (length-- >= 0 && *src++ == 's')
							if (length-- >= 0 && *src++ == 'm')
								if (length-- >= 0 && *src++ == 'n')
									if (length <= 0) return 177;
					break;
				case 'o':
					if (length-- >= 0 && *src++ == 'u')
						if (length-- >= 0 && *src++ == 'n')
							if (length-- >= 0 && *src++ == 'd')
								if (length <= 0) return 163;
					break;
				case 'r':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'i') {
						if (length-- >= 0 && *src++ == 'm')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 8242;
					}
					else if (ch == 'o') {
						if (length-- <= 0) return -1;
						if ((ch = *src++) == 'd') {
							if (length <= 0) return 8719;
						}
						else if (ch == 'p') {
							if (length <= 0) return 8733;
						}
					}
					break;
				case 's':
					if (length-- >= 0 && *src++ == 'i')
						if (length <= 0) return 968;
					break;
			}
			break;
		case 'q':
			if (length-- >= 0 && *src++ == 'u')
				if (length-- >= 0 && *src++ == 'o')
					if (length-- >= 0 && *src++ == 't')
						if (length <= 0) return 34;
			break;
		case 'r':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'A':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 8658;
					break;
				case 'a':
					if (length-- <= 0) return -1;
					switch (*src++) {
						case 'd':
							if (length-- >= 0 && *src++ == 'i')
								if (length-- >= 0 && *src++ == 'c')
									if (length <= 0) return 8730;
							break;
						case 'n':
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 9002;
							break;
						case 'q':
							if (length-- >= 0 && *src++ == 'u')
								if (length-- >= 0 && *src++ == 'o')
									if (length <= 0) return 187;
							break;
						case 'r':
							if (length-- >= 0 && *src++ == 'r')
								if (length <= 0) return 8594;
							break;
					}
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'e')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'l')
								if (length <= 0) return 8969;
					break;
				case 'd':
					if (length-- >= 0 && *src++ == 'q')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 'o')
								if (length <= 0) return 8221;
					break;
				case 'e':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'a') {
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 8476;
					}
					else if (ch == 'g') {
						if (length <= 0) return 174;
					}
					break;
				case 'f':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'o')
							if (length-- >= 0 && *src++ == 'o')
								if (length-- >= 0 && *src++ == 'r')
									if (length <= 0) return 8971;
					break;
				case 'h':
					if (length-- >= 0 && *src++ == 'o')
						if (length <= 0) return 961;
					break;
				case 'l':
					if (length-- >= 0 && *src++ == 'm')
						if (length <= 0) return 8207;
					break;
				case 's':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'a') {
						if (length-- >= 0 && *src++ == 'q')
							if (length-- >= 0 && *src++ == 'u')
								if (length-- >= 0 && *src++ == 'o')
									if (length <= 0) return 8250;
					}
					else if (ch == 'q') {
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 'o')
								if (length <= 0) return 8217;
					}
					break;
			}
			break;
		case 's':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'b':
					if (length-- >= 0 && *src++ == 'q')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 'o')
								if (length <= 0) return 8218;
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'a')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'o')
								if (length-- >= 0 && *src++ == 'n')
									if (length <= 0) return 353;
					break;
				case 'd':
					if (length-- >= 0 && *src++ == 'o')
						if (length-- >= 0 && *src++ == 't')
							if (length <= 0) return 8901;
					break;
				case 'e':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 't')
							if (length <= 0) return 167;
					break;
				case 'h':
					if (length-- >= 0 && *src++ == 'y')
						if (length <= 0) return 173;
					break;
				case 'i':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'g') {
						if (length-- >= 0 && *src++ == 'm') {
							if (length-- >= 0 && *src++ == 'a') {
								if (length <= 0) return 963;
							}
						}
					}
					else if (ch == 'm') {
						if (length <= 0) return 8764;
					}
					break;
				case 'p':
					if (length-- >= 0 && *src++ == 'a')
						if (length-- >= 0 && *src++ == 'd')
							if (length-- >= 0 && *src++ == 'e')
								if (length-- >= 0 && *src++ == 's')
									if (length <= 0) return 9824;
					break;
				case 'u':
					if (length-- <= 0) return -1;
					switch (*src++) {
						case 'b':
							if (length <= 0) return 8834;
							break;
						case 'm':
							if (length <= 0) return 8721;
							break;
						case 'p':
							if (length <= 0) return 8835;
							break;
					}
					break;
				case 'z':
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'g')
								if (length <= 0) return 223;
					break;
			}
			break;
		case 't':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'u')
						if (length <= 0) return 964;
					break;
				case 'h':
					if (length-- <= 0) return -1;
					switch (*src++) {
						case 'e':
							if (length-- <= 0) return -1;
							if ((ch = *src++) == 'r') {
								if (length-- >= 0 && *src++ == 'e')
									if (length-- >= 0 && *src++ == '4')
										if (length <= 0) return 8756;
							}
							else if (ch == 't') {
								if (length-- >= 0 && *src++ == 'a') {
									if (length <= 0) return 952;
								}
							}
							break;
						case 'i':
							if (length-- >= 0 && *src++ == 'n')
								if (length-- >= 0 && *src++ == 's')
									if (length-- >= 0 && *src++ == 'p')
										if (length <= 0) return 8201;
							break;
						case 'o':
							if (length-- >= 0 && *src++ == 'r')
								if (length-- >= 0 && *src++ == 'n')
									if (length <= 0) return 254;
							break;
					}
					break;
				case 'i':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'l') {
						if (length-- >= 0 && *src++ == 'd')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 732;
					}
					else if (ch == 'm') {
						if (length-- >= 0 && *src++ == 'e')
							if (length-- >= 0 && *src++ == 's')
								if (length <= 0) return 215;
					}
					break;
				case 'r':
					if (length-- >= 0 && *src++ == 'a')
						if (length-- >= 0 && *src++ == 'd')
							if (length-- >= 0 && *src++ == 'e')
								if (length <= 0) return 8482;
					break;
			}
			break;
		case 'u':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'A':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 8657;
					break;
				case 'a':
					if (length-- <= 0) return -1;
					if ((ch = *src++) == 'c') {
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 250;
					}
					else if (ch == 'r') {
						if (length-- >= 0 && *src++ == 'r')
							if (length <= 0) return 8593;
					}
					break;
				case 'c':
					if (length-- >= 0 && *src++ == 'i')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'c')
								if (length <= 0) return 251;
					break;
				case 'g':
					if (length-- >= 0 && *src++ == 'r')
						if (length-- >= 0 && *src++ == 'a')
							if (length-- >= 0 && *src++ == 'v')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 249;
					break;
				case 'm':
					if (length-- >= 0 && *src++ == 'l')
						if (length <= 0) return 168;
					break;
				case 'p':
					if (length-- >= 0 && *src++ == 's') {
						if (length-- >= 0 && *src++ == 'i') {
							if (length-- <= 0) return -1;
							if ((ch = *src++) == 'h') {
								if (length <= 0) return 978;
							}
							else if (ch == 'l') {
								if (length-- >= 0 && *src++ == 'o')
									if (length-- >= 0 && *src++ == 'n')
										if (length <= 0) return 965;
							}
						}
					}
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 252;
					break;
			}
			break;
		case 'v':
			if (length-- >= 0 && *src++ == 'e')
				if (length-- >= 0 && *src++ == 'l')
					if (length-- >= 0 && *src++ == 'l')
						if (length-- >= 0 && *src++ == 'i')
							if (length-- >= 0 && *src++ == 'p')
								if (length <= 0) return 8942;
			break;
		case 'w':
			if (length-- >= 0 && *src++ == 'e')
				if (length-- >= 0 && *src++ == 'i')
					if (length-- >= 0 && *src++ == 'e')
						if (length-- >= 0 && *src++ == 'r')
							if (length-- >= 0 && *src++ == 'p')
								if (length <= 0) return 8472;
			break;
		case 'x':
			if (length-- >= 0 && *src++ == 'i')
				if (length <= 0) return 958;
			break;
		case 'y':
			if (length-- <= 0) return -1;
			switch (*src++) {
				case 'a':
					if (length-- >= 0 && *src++ == 'c')
						if (length-- >= 0 && *src++ == 'u')
							if (length-- >= 0 && *src++ == 't')
								if (length-- >= 0 && *src++ == 'e')
									if (length <= 0) return 253;
					break;
				case 'e':
					if (length-- >= 0 && *src++ == 'n')
						if (length <= 0) return 165;
					break;
				case 'u':
					if (length-- >= 0 && *src++ == 'm')
						if (length-- >= 0 && *src++ == 'l')
							if (length <= 0) return 255;
					break;
			}
			break;
		case 'z':
			if (length-- <= 0) return -1;
			if ((ch = *src++) == 'e') {
				if (length-- >= 0 && *src++ == 't')
					if (length-- >= 0 && *src++ == 'a')
						if (length <= 0) return 950;
			}
			else if (ch == 'w') {
				if (length-- <= 0) return -1;
				if ((ch = *src++) == 'j') {
					if (length <= 0) return 8205;
				}
				else if (ch == 'n') {
					if (length-- >= 0 && *src++ == 'j')
						if (length <= 0) return 8204;
				}
			}
			break;
	}
	return -1;
}
