//---------------------------------------------------------------------------------------
//  Smile Programming Language Interpreter
//  Copyright 2004-2016 Sean Werkema
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//---------------------------------------------------------------------------------------

//--------------------------------------------------------------
// WARNING: This file was generated automatically. Do not edit!
//
// The contents of this file are aggregated from data files
// provided by the Unicode Consortium, www.unicode.org.
//--------------------------------------------------------------

#include <smile/internal/unicode.h>

Int32 Unicode_Compose(Int32 a, Int32 b, Int32 c, Int32 d)
{
	switch (a) {
	case 60:
		return b == 824 ? 33563246 : -1;
	case 61:
		return b == 824 ? 33563232 : -1;
	case 62:
		return b == 824 ? 33563247 : -1;
	case 65:
		switch (b) {
		case 768: return 33554624;
		case 769: return 33554625;
		case 770:
			switch (c) {
			case 768: return 50339494;
			case 769: return 50339492;
			case 771: return 50339498;
			case 777: return 50339496;
			default: return 33554626;
			}
		case 771: return 33554627;
		case 772: return 33554688;
		case 774:
			switch (c) {
			case 768: return 50339504;
			case 769: return 50339502;
			case 771: return 50339508;
			case 777: return 50339506;
			default: return 33554690;
			}
		case 775:
			return c == 772 ? 50332128 : 33554982;
		case 776:
			return c == 772 ? 50332126 : 33554628;
		case 777: return 33562274;
		case 778:
			return c == 769 ? 50332154 : 33562923;
		case 780: return 33554893;
		case 783: return 33554944;
		case 785: return 33554946;
		case 803:
			switch (c) {
			case 770: return 50339500;
			case 774: return 50339510;
			default: return 33562272;
			}
		case 805: return 33562112;
		case 808: return 33554692;
		default: return -1;
		}
	case 66:
		switch (b) {
		case 775: return 33562114;
		case 803: return 33562116;
		case 817: return 33562118;
		default: return -1;
		}
	case 67:
		switch (b) {
		case 769: return 33554694;
		case 770: return 33554696;
		case 775: return 33554698;
		case 780: return 33554700;
		case 807:
			return c == 769 ? 50339336 : 33554631;
		default: return -1;
		}
	case 68:
		switch (b) {
		case 775: return 33562122;
		case 780: return 33554702;
		case 803: return 33562124;
		case 807: return 33562128;
		case 813: return 33562130;
		case 817: return 33562126;
		default: return -1;
		}
	case 69:
		switch (b) {
		case 768: return 33554632;
		case 769: return 33554633;
		case 770:
			switch (c) {
			case 768: return 50339520;
			case 769: return 50339518;
			case 771: return 50339524;
			case 777: return 50339522;
			default: return 33554634;
			}
		case 771: return 33562300;
		case 772:
			switch (c) {
			case 768: return 50339348;
			case 769: return 50339350;
			default: return 33554706;
			}
		case 774: return 33554708;
		case 775: return 33554710;
		case 776: return 33554635;
		case 777: return 33562298;
		case 780: return 33554714;
		case 783: return 33554948;
		case 785: return 33554950;
		case 803:
			return c == 770 ? 50339526 : 33562296;
		case 807:
			return c == 774 ? 50339356 : 33554984;
		case 808: return 33554712;
		case 813: return 33562136;
		case 816: return 33562138;
		default: return -1;
		}
	case 70:
		return b == 775 ? 33562142 : -1;
	case 71:
		switch (b) {
		case 769: return 33554932;
		case 770: return 33554716;
		case 772: return 33562144;
		case 774: return 33554718;
		case 775: return 33554720;
		case 780: return 33554918;
		case 807: return 33554722;
		default: return -1;
		}
	case 72:
		switch (b) {
		case 770: return 33554724;
		case 775: return 33562146;
		case 776: return 33562150;
		case 780: return 33554974;
		case 803: return 33562148;
		case 807: return 33562152;
		case 814: return 33562154;
		default: return -1;
		}
	case 73:
		switch (b) {
		case 768: return 33554636;
		case 769: return 33554637;
		case 770: return 33554638;
		case 771: return 33554728;
		case 772: return 33554730;
		case 774: return 33554732;
		case 775: return 33554736;
		case 776:
			return c == 769 ? 50339374 : 33554639;
		case 777: return 33562312;
		case 780: return 33554895;
		case 783: return 33554952;
		case 785: return 33554954;
		case 803: return 33562314;
		case 808: return 33554734;
		case 816: return 33562156;
		default: return -1;
		}
	case 74:
		return b == 770 ? 33554740 : -1;
	case 75:
		switch (b) {
		case 769: return 33562160;
		case 780: return 33554920;
		case 803: return 33562162;
		case 807: return 33554742;
		case 817: return 33562164;
		default: return 16785706;
		}
	case 76:
		switch (b) {
		case 769: return 33554745;
		case 780: return 33554749;
		case 803:
			return c == 772 ? 50339384 : 33562166;
		case 807: return 33554747;
		case 813: return 33562172;
		case 817: return 33562170;
		default: return -1;
		}
	case 77:
		switch (b) {
		case 769: return 33562174;
		case 775: return 33562176;
		case 803: return 33562178;
		default: return -1;
		}
	case 78:
		switch (b) {
		case 768: return 33554936;
		case 769: return 33554755;
		case 771: return 33554641;
		case 775: return 33562180;
		case 780: return 33554759;
		case 803: return 33562182;
		case 807: return 33554757;
		case 813: return 33562186;
		case 817: return 33562184;
		default: return -1;
		}
	case 79:
		switch (b) {
		case 768: return 33554642;
		case 769: return 33554643;
		case 770:
			switch (c) {
			case 768: return 50339538;
			case 769: return 50339536;
			case 771: return 50339542;
			case 777: return 50339540;
			default: return 33554644;
			}
		case 771:
			switch (c) {
			case 769: return 50339404;
			case 772: return 50332204;
			case 776: return 50339406;
			default: return 33554645;
			}
		case 772:
			switch (c) {
			case 768: return 50339408;
			case 769: return 50339410;
			default: return 33554764;
			}
		case 774: return 33554766;
		case 775:
			return c == 772 ? 50332208 : 33554990;
		case 776:
			return c == 772 ? 50332202 : 33554646;
		case 777: return 33562318;
		case 779: return 33554768;
		case 780: return 33554897;
		case 783: return 33554956;
		case 785: return 33554958;
		case 795:
			switch (c) {
			case 768: return 50339548;
			case 769: return 50339546;
			case 771: return 50339552;
			case 777: return 50339550;
			case 803: return 50339554;
			default: return 33554848;
			}
		case 803:
			return c == 770 ? 50339544 : 33562316;
		case 808:
			return c == 772 ? 50332140 : 33554922;
		default: return -1;
		}
	case 80:
		switch (b) {
		case 769: return 33562196;
		case 775: return 33562198;
		default: return -1;
		}
	case 82:
		switch (b) {
		case 769: return 33554772;
		case 775: return 33562200;
		case 780: return 33554776;
		case 783: return 33554960;
		case 785: return 33554962;
		case 803:
			return c == 772 ? 50339420 : 33562202;
		case 807: return 33554774;
		case 817: return 33562206;
		default: return -1;
		}
	case 83:
		switch (b) {
		case 769:
			return c == 775 ? 50339428 : 33554778;
		case 770: return 33554780;
		case 775: return 33562208;
		case 780:
			return c == 775 ? 50339430 : 33554784;
		case 803:
			return c == 775 ? 50339432 : 33562210;
		case 806: return 33554968;
		case 807: return 33554782;
		default: return -1;
		}
	case 84:
		switch (b) {
		case 775: return 33562218;
		case 780: return 33554788;
		case 803: return 33562220;
		case 806: return 33554970;
		case 807: return 33554786;
		case 813: return 33562224;
		case 817: return 33562222;
		default: return -1;
		}
	case 85:
		switch (b) {
		case 768: return 33554649;
		case 769: return 33554650;
		case 770: return 33554651;
		case 771:
			return c == 769 ? 50339448 : 33554792;
		case 772:
			return c == 776 ? 50339450 : 33554794;
		case 774: return 33554796;
		case 776:
			switch (c) {
			case 768: return 50332123;
			case 769: return 50332119;
			case 772: return 50332117;
			case 780: return 50332121;
			default: return 33554652;
			}
		case 777: return 33562342;
		case 778: return 33554798;
		case 779: return 33554800;
		case 780: return 33554899;
		case 783: return 33554964;
		case 785: return 33554966;
		case 795:
			switch (c) {
			case 768: return 50339562;
			case 769: return 50339560;
			case 771: return 50339566;
			case 777: return 50339564;
			case 803: return 50339568;
			default: return 33554863;
			}
		case 803: return 33562340;
		case 804: return 33562226;
		case 808: return 33554802;
		case 813: return 33562230;
		case 816: return 33562228;
		default: return -1;
		}
	case 86:
		switch (b) {
		case 771: return 33562236;
		case 803: return 33562238;
		default: return -1;
		}
	case 87:
		switch (b) {
		case 768: return 33562240;
		case 769: return 33562242;
		case 770: return 33554804;
		case 775: return 33562246;
		case 776: return 33562244;
		case 803: return 33562248;
		default: return -1;
		}
	case 88:
		switch (b) {
		case 775: return 33562250;
		case 776: return 33562252;
		default: return -1;
		}
	case 89:
		switch (b) {
		case 768: return 33562354;
		case 769: return 33554653;
		case 770: return 33554806;
		case 771: return 33562360;
		case 772: return 33554994;
		case 775: return 33562254;
		case 776: return 33554808;
		case 777: return 33562358;
		case 803: return 33562356;
		default: return -1;
		}
	case 90:
		switch (b) {
		case 769: return 33554809;
		case 770: return 33562256;
		case 775: return 33554811;
		case 780: return 33554813;
		case 803: return 33562258;
		case 817: return 33562260;
		default: return -1;
		}
	case 97:
		switch (b) {
		case 768: return 33554656;
		case 769: return 33554657;
		case 770:
			switch (c) {
			case 768: return 50339495;
			case 769: return 50339493;
			case 771: return 50339499;
			case 777: return 50339497;
			default: return 33554658;
			}
		case 771: return 33554659;
		case 772: return 33554689;
		case 774:
			switch (c) {
			case 768: return 50339505;
			case 769: return 50339503;
			case 771: return 50339509;
			case 777: return 50339507;
			default: return 33554691;
			}
		case 775:
			return c == 772 ? 50332129 : 33554983;
		case 776:
			return c == 772 ? 50332127 : 33554660;
		case 777: return 33562275;
		case 778:
			return c == 769 ? 50332155 : 33554661;
		case 780: return 33554894;
		case 783: return 33554945;
		case 785: return 33554947;
		case 803:
			switch (c) {
			case 770: return 50339501;
			case 774: return 50339511;
			default: return 33562273;
			}
		case 805: return 33562113;
		case 808: return 33554693;
		default: return -1;
		}
	case 98:
		switch (b) {
		case 775: return 33562115;
		case 803: return 33562117;
		case 817: return 33562119;
		default: return -1;
		}
	case 99:
		switch (b) {
		case 769: return 33554695;
		case 770: return 33554697;
		case 775: return 33554699;
		case 780: return 33554701;
		case 807:
			return c == 769 ? 50339337 : 33554663;
		default: return -1;
		}
	case 100:
		switch (b) {
		case 775: return 33562123;
		case 780: return 33554703;
		case 803: return 33562125;
		case 807: return 33562129;
		case 813: return 33562131;
		case 817: return 33562127;
		default: return -1;
		}
	case 101:
		switch (b) {
		case 768: return 33554664;
		case 769: return 33554665;
		case 770:
			switch (c) {
			case 768: return 50339521;
			case 769: return 50339519;
			case 771: return 50339525;
			case 777: return 50339523;
			default: return 33554666;
			}
		case 771: return 33562301;
		case 772:
			switch (c) {
			case 768: return 50339349;
			case 769: return 50339351;
			default: return 33554707;
			}
		case 774: return 33554709;
		case 775: return 33554711;
		case 776: return 33554667;
		case 777: return 33562299;
		case 780: return 33554715;
		case 783: return 33554949;
		case 785: return 33554951;
		case 803:
			return c == 770 ? 50339527 : 33562297;
		case 807:
			return c == 774 ? 50339357 : 33554985;
		case 808: return 33554713;
		case 813: return 33562137;
		case 816: return 33562139;
		default: return -1;
		}
	case 102:
		return b == 775 ? 33562143 : -1;
	case 103:
		switch (b) {
		case 769: return 33554933;
		case 770: return 33554717;
		case 772: return 33562145;
		case 774: return 33554719;
		case 775: return 33554721;
		case 780: return 33554919;
		case 807: return 33554723;
		default: return -1;
		}
	case 104:
		switch (b) {
		case 770: return 33554725;
		case 775: return 33562147;
		case 776: return 33562151;
		case 780: return 33554975;
		case 803: return 33562149;
		case 807: return 33562153;
		case 814: return 33562155;
		case 817: return 33562262;
		default: return -1;
		}
	case 105:
		switch (b) {
		case 768: return 33554668;
		case 769: return 33554669;
		case 770: return 33554670;
		case 771: return 33554729;
		case 772: return 33554731;
		case 774: return 33554733;
		case 776:
			return c == 769 ? 50339375 : 33554671;
		case 777: return 33562313;
		case 780: return 33554896;
		case 783: return 33554953;
		case 785: return 33554955;
		case 803: return 33562315;
		case 808: return 33554735;
		case 816: return 33562157;
		default: return -1;
		}
	case 106:
		switch (b) {
		case 770: return 33554741;
		case 780: return 33554928;
		default: return -1;
		}
	case 107:
		switch (b) {
		case 769: return 33562161;
		case 780: return 33554921;
		case 803: return 33562163;
		case 807: return 33554743;
		case 817: return 33562165;
		default: return -1;
		}
	case 108:
		switch (b) {
		case 769: return 33554746;
		case 780: return 33554750;
		case 803:
			return c == 772 ? 50339385 : 33562167;
		case 807: return 33554748;
		case 813: return 33562173;
		case 817: return 33562171;
		default: return -1;
		}
	case 109:
		switch (b) {
		case 769: return 33562175;
		case 775: return 33562177;
		case 803: return 33562179;
		default: return -1;
		}
	case 110:
		switch (b) {
		case 768: return 33554937;
		case 769: return 33554756;
		case 771: return 33554673;
		case 775: return 33562181;
		case 780: return 33554760;
		case 803: return 33562183;
		case 807: return 33554758;
		case 813: return 33562187;
		case 817: return 33562185;
		default: return -1;
		}
	case 111:
		switch (b) {
		case 768: return 33554674;
		case 769: return 33554675;
		case 770:
			switch (c) {
			case 768: return 50339539;
			case 769: return 50339537;
			case 771: return 50339543;
			case 777: return 50339541;
			default: return 33554676;
			}
		case 771:
			switch (c) {
			case 769: return 50339405;
			case 772: return 50332205;
			case 776: return 50339407;
			default: return 33554677;
			}
		case 772:
			switch (c) {
			case 768: return 50339409;
			case 769: return 50339411;
			default: return 33554765;
			}
		case 774: return 33554767;
		case 775:
			return c == 772 ? 50332209 : 33554991;
		case 776:
			return c == 772 ? 50332203 : 33554678;
		case 777: return 33562319;
		case 779: return 33554769;
		case 780: return 33554898;
		case 783: return 33554957;
		case 785: return 33554959;
		case 795:
			switch (c) {
			case 768: return 50339549;
			case 769: return 50339547;
			case 771: return 50339553;
			case 777: return 50339551;
			case 803: return 50339555;
			default: return 33554849;
			}
		case 803:
			return c == 770 ? 50339545 : 33562317;
		case 808:
			return c == 772 ? 50332141 : 33554923;
		default: return -1;
		}
	case 112:
		switch (b) {
		case 769: return 33562197;
		case 775: return 33562199;
		default: return -1;
		}
	case 114:
		switch (b) {
		case 769: return 33554773;
		case 775: return 33562201;
		case 780: return 33554777;
		case 783: return 33554961;
		case 785: return 33554963;
		case 803:
			return c == 772 ? 50339421 : 33562203;
		case 807: return 33554775;
		case 817: return 33562207;
		default: return -1;
		}
	case 115:
		switch (b) {
		case 769:
			return c == 775 ? 50339429 : 33554779;
		case 770: return 33554781;
		case 775: return 33562209;
		case 780:
			return c == 775 ? 50339431 : 33554785;
		case 803:
			return c == 775 ? 50339433 : 33562211;
		case 806: return 33554969;
		case 807: return 33554783;
		default: return -1;
		}
	case 116:
		switch (b) {
		case 775: return 33562219;
		case 776: return 33562263;
		case 780: return 33554789;
		case 803: return 33562221;
		case 806: return 33554971;
		case 807: return 33554787;
		case 813: return 33562225;
		case 817: return 33562223;
		default: return -1;
		}
	case 117:
		switch (b) {
		case 768: return 33554681;
		case 769: return 33554682;
		case 770: return 33554683;
		case 771:
			return c == 769 ? 50339449 : 33554793;
		case 772:
			return c == 776 ? 50339451 : 33554795;
		case 774: return 33554797;
		case 776:
			switch (c) {
			case 768: return 50332124;
			case 769: return 50332120;
			case 772: return 50332118;
			case 780: return 50332122;
			default: return 33554684;
			}
		case 777: return 33562343;
		case 778: return 33554799;
		case 779: return 33554801;
		case 780: return 33554900;
		case 783: return 33554965;
		case 785: return 33554967;
		case 795:
			switch (c) {
			case 768: return 50339563;
			case 769: return 50339561;
			case 771: return 50339567;
			case 777: return 50339565;
			case 803: return 50339569;
			default: return 33554864;
			}
		case 803: return 33562341;
		case 804: return 33562227;
		case 808: return 33554803;
		case 813: return 33562231;
		case 816: return 33562229;
		default: return -1;
		}
	case 118:
		switch (b) {
		case 771: return 33562237;
		case 803: return 33562239;
		default: return -1;
		}
	case 119:
		switch (b) {
		case 768: return 33562241;
		case 769: return 33562243;
		case 770: return 33554805;
		case 775: return 33562247;
		case 776: return 33562245;
		case 778: return 33562264;
		case 803: return 33562249;
		default: return -1;
		}
	case 120:
		switch (b) {
		case 775: return 33562251;
		case 776: return 33562253;
		default: return -1;
		}
	case 121:
		switch (b) {
		case 768: return 33562355;
		case 769: return 33554685;
		case 770: return 33554807;
		case 771: return 33562361;
		case 772: return 33554995;
		case 775: return 33562255;
		case 776: return 33554687;
		case 777: return 33562359;
		case 778: return 33562265;
		case 803: return 33562357;
		default: return -1;
		}
	case 122:
		switch (b) {
		case 769: return 33554810;
		case 770: return 33562257;
		case 775: return 33554812;
		case 780: return 33554814;
		case 803: return 33562259;
		case 817: return 33562261;
		default: return -1;
		}
	case 168:
		switch (b) {
		case 768: return 33562605;
		case 769: return 33562606;
		case 834: return 33562561;
		default: return -1;
		}
	case 198:
		switch (b) {
		case 769: return 33554940;
		case 772: return 33554914;
		default: return -1;
		}
	case 216:
		return b == 769 ? 33554942 : -1;
	case 230:
		switch (b) {
		case 769: return 33554941;
		case 772: return 33554915;
		default: return -1;
		}
	case 248:
		return b == 769 ? 33554943 : -1;
	case 383:
		return b == 775 ? 33562267 : -1;
	case 439:
		return b == 780 ? 33554926 : -1;
	case 658:
		return b == 780 ? 33554927 : -1;
	case 776:
		return b == 769 ? 33555268 : -1;
	case 913:
		switch (b) {
		case 768: return 33562554;
		case 769: return 33562555;
		case 772: return 33562553;
		case 774: return 33562552;
		case 787:
			switch (c) {
			case 768:
				return d == 837 ? 67116938 : 50339594;
			case 769:
				return d == 837 ? 67116940 : 50339596;
			case 834:
				return d == 837 ? 67116942 : 50339598;
			case 837: return 50339720;
			default: return 33562376;
			}
		case 788:
			switch (c) {
			case 768:
				return d == 837 ? 67116939 : 50339595;
			case 769:
				return d == 837 ? 67116941 : 50339597;
			case 834:
				return d == 837 ? 67116943 : 50339599;
			case 837: return 50339721;
			default: return 33562377;
			}
		case 837: return 33562556;
		default: return -1;
		}
	case 917:
		switch (b) {
		case 768: return 33562568;
		case 769: return 33562569;
		case 787:
			switch (c) {
			case 768: return 50339610;
			case 769: return 50339612;
			default: return 33562392;
			}
		case 788:
			switch (c) {
			case 768: return 50339611;
			case 769: return 50339613;
			default: return 33562393;
			}
		default: return -1;
		}
	case 919:
		switch (b) {
		case 768: return 33562570;
		case 769: return 33562571;
		case 787:
			switch (c) {
			case 768:
				return d == 837 ? 67116954 : 50339626;
			case 769:
				return d == 837 ? 67116956 : 50339628;
			case 834:
				return d == 837 ? 67116958 : 50339630;
			case 837: return 50339736;
			default: return 33562408;
			}
		case 788:
			switch (c) {
			case 768:
				return d == 837 ? 67116955 : 50339627;
			case 769:
				return d == 837 ? 67116957 : 50339629;
			case 834:
				return d == 837 ? 67116959 : 50339631;
			case 837: return 50339737;
			default: return 33562409;
			}
		case 837: return 33562572;
		default: return -1;
		}
	case 921:
		switch (b) {
		case 768: return 33562586;
		case 769: return 33562587;
		case 772: return 33562585;
		case 774: return 33562584;
		case 776: return 33555370;
		case 787:
			switch (c) {
			case 768: return 50339642;
			case 769: return 50339644;
			case 834: return 50339646;
			default: return 33562424;
			}
		case 788:
			switch (c) {
			case 768: return 50339643;
			case 769: return 50339645;
			case 834: return 50339647;
			default: return 33562425;
			}
		default: return -1;
		}
	case 927:
		switch (b) {
		case 768: return 33562616;
		case 769: return 33562617;
		case 787:
			switch (c) {
			case 768: return 50339658;
			case 769: return 50339660;
			default: return 33562440;
			}
		case 788:
			switch (c) {
			case 768: return 50339659;
			case 769: return 50339661;
			default: return 33562441;
			}
		default: return -1;
		}
	case 929:
		return b == 788 ? 33562604 : -1;
	case 933:
		switch (b) {
		case 768: return 33562602;
		case 769: return 33562603;
		case 772: return 33562601;
		case 774: return 33562600;
		case 776: return 33555371;
		case 788:
			switch (c) {
			case 768: return 50339675;
			case 769: return 50339677;
			case 834: return 50339679;
			default: return 33562457;
			}
		default: return -1;
		}
	case 937:
		switch (b) {
		case 768: return 33562618;
		case 769: return 33562619;
		case 787:
			switch (c) {
			case 768:
				return d == 837 ? 67116970 : 50339690;
			case 769:
				return d == 837 ? 67116972 : 50339692;
			case 834:
				return d == 837 ? 67116974 : 50339694;
			case 837: return 50339752;
			default: return 33562472;
			}
		case 788:
			switch (c) {
			case 768:
				return d == 837 ? 67116971 : 50339691;
			case 769:
				return d == 837 ? 67116973 : 50339693;
			case 834:
				return d == 837 ? 67116975 : 50339695;
			case 837: return 50339753;
			default: return 33562473;
			}
		case 837: return 33562620;
		default: return 16785702;
		}
	case 945:
		switch (b) {
		case 768:
			return c == 837 ? 50339762 : 33562480;
		case 769:
			return c == 837 ? 50339764 : 33562481;
		case 772: return 33562545;
		case 774: return 33562544;
		case 787:
			switch (c) {
			case 768:
				return d == 837 ? 67116930 : 50339586;
			case 769:
				return d == 837 ? 67116932 : 50339588;
			case 834:
				return d == 837 ? 67116934 : 50339590;
			case 837: return 50339712;
			default: return 33562368;
			}
		case 788:
			switch (c) {
			case 768:
				return d == 837 ? 67116931 : 50339587;
			case 769:
				return d == 837 ? 67116933 : 50339589;
			case 834:
				return d == 837 ? 67116935 : 50339591;
			case 837: return 50339713;
			default: return 33562369;
			}
		case 834:
			return c == 837 ? 50339767 : 33562550;
		case 837: return 33562547;
		default: return -1;
		}
	case 949:
		switch (b) {
		case 768: return 33562482;
		case 769: return 33562483;
		case 787:
			switch (c) {
			case 768: return 50339602;
			case 769: return 50339604;
			default: return 33562384;
			}
		case 788:
			switch (c) {
			case 768: return 50339603;
			case 769: return 50339605;
			default: return 33562385;
			}
		default: return -1;
		}
	case 951:
		switch (b) {
		case 768:
			return c == 837 ? 50339778 : 33562484;
		case 769:
			return c == 837 ? 50339780 : 33562485;
		case 787:
			switch (c) {
			case 768:
				return d == 837 ? 67116946 : 50339618;
			case 769:
				return d == 837 ? 67116948 : 50339620;
			case 834:
				return d == 837 ? 67116950 : 50339622;
			case 837: return 50339728;
			default: return 33562400;
			}
		case 788:
			switch (c) {
			case 768:
				return d == 837 ? 67116947 : 50339619;
			case 769:
				return d == 837 ? 67116949 : 50339621;
			case 834:
				return d == 837 ? 67116951 : 50339623;
			case 837: return 50339729;
			default: return 33562401;
			}
		case 834:
			return c == 837 ? 50339783 : 33562566;
		case 837: return 33562563;
		default: return -1;
		}
	case 953:
		switch (b) {
		case 768: return 33562486;
		case 769: return 33562487;
		case 772: return 33562577;
		case 774: return 33562576;
		case 776:
			switch (c) {
			case 768: return 50339794;
			case 769: return 50339795;
			case 834: return 50339799;
			default: return 33555402;
			}
		case 787:
			switch (c) {
			case 768: return 50339634;
			case 769: return 50339636;
			case 834: return 50339638;
			default: return 33562416;
			}
		case 788:
			switch (c) {
			case 768: return 50339635;
			case 769: return 50339637;
			case 834: return 50339639;
			default: return 33562417;
			}
		case 834: return 33562582;
		default: return 16785342;
		}
	case 959:
		switch (b) {
		case 768: return 33562488;
		case 769: return 33562489;
		case 787:
			switch (c) {
			case 768: return 50339650;
			case 769: return 50339652;
			default: return 33562432;
			}
		case 788:
			switch (c) {
			case 768: return 50339651;
			case 769: return 50339653;
			default: return 33562433;
			}
		default: return -1;
		}
	case 961:
		switch (b) {
		case 787: return 33562596;
		case 788: return 33562597;
		default: return -1;
		}
	case 965:
		switch (b) {
		case 768: return 33562490;
		case 769: return 33562491;
		case 772: return 33562593;
		case 774: return 33562592;
		case 776:
			switch (c) {
			case 768: return 50339810;
			case 769: return 50339811;
			case 834: return 50339815;
			default: return 33555403;
			}
		case 787:
			switch (c) {
			case 768: return 50339666;
			case 769: return 50339668;
			case 834: return 50339670;
			default: return 33562448;
			}
		case 788:
			switch (c) {
			case 768: return 50339667;
			case 769: return 50339669;
			case 834: return 50339671;
			default: return 33562449;
			}
		case 834: return 33562598;
		default: return -1;
		}
	case 969:
		switch (b) {
		case 768:
			return c == 837 ? 50339826 : 33562492;
		case 769:
			return c == 837 ? 50339828 : 33562493;
		case 787:
			switch (c) {
			case 768:
				return d == 837 ? 67116962 : 50339682;
			case 769:
				return d == 837 ? 67116964 : 50339684;
			case 834:
				return d == 837 ? 67116966 : 50339686;
			case 837: return 50339744;
			default: return 33562464;
			}
		case 788:
			switch (c) {
			case 768:
				return d == 837 ? 67116963 : 50339683;
			case 769:
				return d == 837 ? 67116965 : 50339685;
			case 834:
				return d == 837 ? 67116967 : 50339687;
			case 837: return 50339745;
			default: return 33562465;
			}
		case 834:
			return c == 837 ? 50339831 : 33562614;
		case 837: return 33562611;
		default: return -1;
		}
	case 978:
		switch (b) {
		case 769: return 33555411;
		case 776: return 33555412;
		default: return -1;
		}
	case 1030:
		return b == 776 ? 33555463 : -1;
	case 1040:
		switch (b) {
		case 774: return 33555664;
		case 776: return 33555666;
		default: return -1;
		}
	case 1043:
		return b == 769 ? 33555459 : -1;
	case 1045:
		switch (b) {
		case 768: return 33555456;
		case 774: return 33555670;
		case 776: return 33555457;
		default: return -1;
		}
	case 1046:
		switch (b) {
		case 774: return 33555649;
		case 776: return 33555676;
		default: return -1;
		}
	case 1047:
		return b == 776 ? 33555678 : -1;
	case 1048:
		switch (b) {
		case 768: return 33555469;
		case 772: return 33555682;
		case 774: return 33555481;
		case 776: return 33555684;
		default: return -1;
		}
	case 1050:
		return b == 769 ? 33555468 : -1;
	case 1054:
		return b == 776 ? 33555686 : -1;
	case 1059:
		switch (b) {
		case 772: return 33555694;
		case 774: return 33555470;
		case 776: return 33555696;
		case 779: return 33555698;
		default: return -1;
		}
	case 1063:
		return b == 776 ? 33555700 : -1;
	case 1067:
		return b == 776 ? 33555704 : -1;
	case 1069:
		return b == 776 ? 33555692 : -1;
	case 1072:
		switch (b) {
		case 774: return 33555665;
		case 776: return 33555667;
		default: return -1;
		}
	case 1075:
		return b == 769 ? 33555539 : -1;
	case 1077:
		switch (b) {
		case 768: return 33555536;
		case 774: return 33555671;
		case 776: return 33555537;
		default: return -1;
		}
	case 1078:
		switch (b) {
		case 774: return 33555650;
		case 776: return 33555677;
		default: return -1;
		}
	case 1079:
		return b == 776 ? 33555679 : -1;
	case 1080:
		switch (b) {
		case 768: return 33555549;
		case 772: return 33555683;
		case 774: return 33555513;
		case 776: return 33555685;
		default: return -1;
		}
	case 1082:
		return b == 769 ? 33555548 : -1;
	case 1086:
		return b == 776 ? 33555687 : -1;
	case 1091:
		switch (b) {
		case 772: return 33555695;
		case 774: return 33555550;
		case 776: return 33555697;
		case 779: return 33555699;
		default: return -1;
		}
	case 1095:
		return b == 776 ? 33555701 : -1;
	case 1099:
		return b == 776 ? 33555705 : -1;
	case 1101:
		return b == 776 ? 33555693 : -1;
	case 1110:
		return b == 776 ? 33555543 : -1;
	case 1140:
		return b == 783 ? 33555574 : -1;
	case 1141:
		return b == 783 ? 33555575 : -1;
	case 1240:
		return b == 776 ? 33555674 : -1;
	case 1241:
		return b == 776 ? 33555675 : -1;
	case 1256:
		return b == 776 ? 33555690 : -1;
	case 1257:
		return b == 776 ? 33555691 : -1;
	case 1488:
		switch (b) {
		case 1463: return 33618734;
		case 1464: return 33618735;
		case 1468: return 33618736;
		default: return -1;
		}
	case 1489:
		switch (b) {
		case 1468: return 33618737;
		case 1471: return 33618764;
		default: return -1;
		}
	case 1490:
		return b == 1468 ? 33618738 : -1;
	case 1491:
		return b == 1468 ? 33618739 : -1;
	case 1492:
		return b == 1468 ? 33618740 : -1;
	case 1493:
		switch (b) {
		case 1465: return 33618763;
		case 1468: return 33618741;
		default: return -1;
		}
	case 1494:
		return b == 1468 ? 33618742 : -1;
	case 1496:
		return b == 1468 ? 33618744 : -1;
	case 1497:
		switch (b) {
		case 1460: return 33618717;
		case 1468: return 33618745;
		default: return -1;
		}
	case 1498:
		return b == 1468 ? 33618746 : -1;
	case 1499:
		switch (b) {
		case 1468: return 33618747;
		case 1471: return 33618765;
		default: return -1;
		}
	case 1500:
		return b == 1468 ? 33618748 : -1;
	case 1502:
		return b == 1468 ? 33618750 : -1;
	case 1504:
		return b == 1468 ? 33618752 : -1;
	case 1505:
		return b == 1468 ? 33618753 : -1;
	case 1507:
		return b == 1468 ? 33618755 : -1;
	case 1508:
		switch (b) {
		case 1468: return 33618756;
		case 1471: return 33618766;
		default: return -1;
		}
	case 1510:
		return b == 1468 ? 33618758 : -1;
	case 1511:
		return b == 1468 ? 33618759 : -1;
	case 1512:
		return b == 1468 ? 33618760 : -1;
	case 1513:
		switch (b) {
		case 1468:
			switch (c) {
			case 1473: return 50395948;
			case 1474: return 50395949;
			default: return 33618761;
			}
		case 1473: return 33618730;
		case 1474: return 33618731;
		default: return -1;
		}
	case 1514:
		return b == 1468 ? 33618762 : -1;
	case 1522:
		return b == 1463 ? 33618719 : -1;
	case 1575:
		switch (b) {
		case 1619: return 33556002;
		case 1620: return 33556003;
		case 1621: return 33556005;
		default: return -1;
		}
	case 1608:
		return b == 1620 ? 33556004 : -1;
	case 1610:
		return b == 1620 ? 33556006 : -1;
	case 1729:
		return b == 1620 ? 33556162 : -1;
	case 1746:
		return b == 1620 ? 33556179 : -1;
	case 1749:
		return b == 1620 ? 33556160 : -1;
	case 2325:
		return b == 2364 ? 33556824 : -1;
	case 2326:
		return b == 2364 ? 33556825 : -1;
	case 2327:
		return b == 2364 ? 33556826 : -1;
	case 2332:
		return b == 2364 ? 33556827 : -1;
	case 2337:
		return b == 2364 ? 33556828 : -1;
	case 2338:
		return b == 2364 ? 33556829 : -1;
	case 2344:
		return b == 2364 ? 33556777 : -1;
	case 2347:
		return b == 2364 ? 33556830 : -1;
	case 2351:
		return b == 2364 ? 33556831 : -1;
	case 2352:
		return b == 2364 ? 33556785 : -1;
	case 2355:
		return b == 2364 ? 33556788 : -1;
	case 2465:
		return b == 2492 ? 33556956 : -1;
	case 2466:
		return b == 2492 ? 33556957 : -1;
	case 2479:
		return b == 2492 ? 33556959 : -1;
	case 2503:
		switch (b) {
		case 2494: return 33556939;
		case 2519: return 33556940;
		default: return -1;
		}
	case 2582:
		return b == 2620 ? 33557081 : -1;
	case 2583:
		return b == 2620 ? 33557082 : -1;
	case 2588:
		return b == 2620 ? 33557083 : -1;
	case 2603:
		return b == 2620 ? 33557086 : -1;
	case 2610:
		return b == 2620 ? 33557043 : -1;
	case 2616:
		return b == 2620 ? 33557046 : -1;
	case 2849:
		return b == 2876 ? 33557340 : -1;
	case 2850:
		return b == 2876 ? 33557341 : -1;
	case 2887:
		switch (b) {
		case 2878: return 33557323;
		case 2902: return 33557320;
		case 2903: return 33557324;
		default: return -1;
		}
	case 2962:
		return b == 3031 ? 33557396 : -1;
	case 3014:
		switch (b) {
		case 3006: return 33557450;
		case 3031: return 33557452;
		default: return -1;
		}
	case 3015:
		return b == 3006 ? 33557451 : -1;
	case 3142:
		return b == 3158 ? 33557576 : -1;
	case 3263:
		return b == 3285 ? 33557696 : -1;
	case 3270:
		switch (b) {
		case 3266:
			return c == 3285 ? 50334923 : 33557706;
		case 3285: return 33557703;
		case 3286: return 33557704;
		default: return -1;
		}
	case 3398:
		switch (b) {
		case 3390: return 33557834;
		case 3415: return 33557836;
		default: return -1;
		}
	case 3399:
		return b == 3390 ? 33557835 : -1;
	case 3545:
		switch (b) {
		case 3530: return 33557978;
		case 3535:
			return c == 3530 ? 50335197 : 33557980;
		case 3551: return 33557982;
		default: return -1;
		}
	case 3904:
		return b == 4021 ? 33558377 : -1;
	case 3906:
		return b == 4023 ? 33558339 : -1;
	case 3916:
		return b == 4023 ? 33558349 : -1;
	case 3921:
		return b == 4023 ? 33558354 : -1;
	case 3926:
		return b == 4023 ? 33558359 : -1;
	case 3931:
		return b == 4023 ? 33558364 : -1;
	case 3953:
		switch (b) {
		case 3954: return 33558387;
		case 3956: return 33558389;
		case 3968: return 33558401;
		default: return -1;
		}
	case 3984:
		return b == 4021 ? 33558457 : -1;
	case 3986:
		return b == 4023 ? 33558419 : -1;
	case 3996:
		return b == 4023 ? 33558429 : -1;
	case 4001:
		return b == 4023 ? 33558434 : -1;
	case 4006:
		return b == 4023 ? 33558439 : -1;
	case 4011:
		return b == 4023 ? 33558444 : -1;
	case 4018:
		return b == 3968 ? 33558390 : -1;
	case 4019:
		return b == 3968 ? 33558392 : -1;
	case 4133:
		return b == 4142 ? 33558566 : -1;
	case 6917:
		return b == 6965 ? 33561350 : -1;
	case 6919:
		return b == 6965 ? 33561352 : -1;
	case 6921:
		return b == 6965 ? 33561354 : -1;
	case 6923:
		return b == 6965 ? 33561356 : -1;
	case 6925:
		return b == 6965 ? 33561358 : -1;
	case 6929:
		return b == 6965 ? 33561362 : -1;
	case 6970:
		return b == 6965 ? 33561403 : -1;
	case 6972:
		return b == 6965 ? 33561405 : -1;
	case 6974:
		return b == 6965 ? 33561408 : -1;
	case 6975:
		return b == 6965 ? 33561409 : -1;
	case 6978:
		return b == 6965 ? 33561411 : -1;
	case 8127:
		switch (b) {
		case 768: return 33562573;
		case 769: return 33562574;
		case 834: return 33562575;
		default: return -1;
		}
	case 8190:
		switch (b) {
		case 768: return 33562589;
		case 769: return 33562590;
		case 834: return 33562591;
		default: return -1;
		}
	case 8592:
		return b == 824 ? 33563034 : -1;
	case 8594:
		return b == 824 ? 33563035 : -1;
	case 8596:
		return b == 824 ? 33563054 : -1;
	case 8656:
		return b == 824 ? 33563085 : -1;
	case 8658:
		return b == 824 ? 33563087 : -1;
	case 8660:
		return b == 824 ? 33563086 : -1;
	case 8707:
		return b == 824 ? 33563140 : -1;
	case 8712:
		return b == 824 ? 33563145 : -1;
	case 8715:
		return b == 824 ? 33563148 : -1;
	case 8739:
		return b == 824 ? 33563172 : -1;
	case 8741:
		return b == 824 ? 33563174 : -1;
	case 8764:
		return b == 824 ? 33563201 : -1;
	case 8771:
		return b == 824 ? 33563204 : -1;
	case 8773:
		return b == 824 ? 33563207 : -1;
	case 8776:
		return b == 824 ? 33563209 : -1;
	case 8781:
		return b == 824 ? 33563245 : -1;
	case 8801:
		return b == 824 ? 33563234 : -1;
	case 8804:
		return b == 824 ? 33563248 : -1;
	case 8805:
		return b == 824 ? 33563249 : -1;
	case 8818:
		return b == 824 ? 33563252 : -1;
	case 8819:
		return b == 824 ? 33563253 : -1;
	case 8822:
		return b == 824 ? 33563256 : -1;
	case 8823:
		return b == 824 ? 33563257 : -1;
	case 8826:
		return b == 824 ? 33563264 : -1;
	case 8827:
		return b == 824 ? 33563265 : -1;
	case 8828:
		return b == 824 ? 33563360 : -1;
	case 8829:
		return b == 824 ? 33563361 : -1;
	case 8834:
		return b == 824 ? 33563268 : -1;
	case 8835:
		return b == 824 ? 33563269 : -1;
	case 8838:
		return b == 824 ? 33563272 : -1;
	case 8839:
		return b == 824 ? 33563273 : -1;
	case 8849:
		return b == 824 ? 33563362 : -1;
	case 8850:
		return b == 824 ? 33563363 : -1;
	case 8866:
		return b == 824 ? 33563308 : -1;
	case 8872:
		return b == 824 ? 33563309 : -1;
	case 8873:
		return b == 824 ? 33563310 : -1;
	case 8875:
		return b == 824 ? 33563311 : -1;
	case 8882:
		return b == 824 ? 33563370 : -1;
	case 8883:
		return b == 824 ? 33563371 : -1;
	case 8884:
		return b == 824 ? 33563372 : -1;
	case 8885:
		return b == 824 ? 33563373 : -1;
	case 10973:
		return b == 824 ? 33565404 : -1;
	case 12358:
		return b == 12441 ? 33566868 : -1;
	case 12363:
		return b == 12441 ? 33566796 : -1;
	case 12365:
		return b == 12441 ? 33566798 : -1;
	case 12367:
		return b == 12441 ? 33566800 : -1;
	case 12369:
		return b == 12441 ? 33566802 : -1;
	case 12371:
		return b == 12441 ? 33566804 : -1;
	case 12373:
		return b == 12441 ? 33566806 : -1;
	case 12375:
		return b == 12441 ? 33566808 : -1;
	case 12377:
		return b == 12441 ? 33566810 : -1;
	case 12379:
		return b == 12441 ? 33566812 : -1;
	case 12381:
		return b == 12441 ? 33566814 : -1;
	case 12383:
		return b == 12441 ? 33566816 : -1;
	case 12385:
		return b == 12441 ? 33566818 : -1;
	case 12388:
		return b == 12441 ? 33566821 : -1;
	case 12390:
		return b == 12441 ? 33566823 : -1;
	case 12392:
		return b == 12441 ? 33566825 : -1;
	case 12399:
		switch (b) {
		case 12441: return 33566832;
		case 12442: return 33566833;
		default: return -1;
		}
	case 12402:
		switch (b) {
		case 12441: return 33566835;
		case 12442: return 33566836;
		default: return -1;
		}
	case 12405:
		switch (b) {
		case 12441: return 33566838;
		case 12442: return 33566839;
		default: return -1;
		}
	case 12408:
		switch (b) {
		case 12441: return 33566841;
		case 12442: return 33566842;
		default: return -1;
		}
	case 12411:
		switch (b) {
		case 12441: return 33566844;
		case 12442: return 33566845;
		default: return -1;
		}
	case 12445:
		return b == 12441 ? 33566878 : -1;
	case 12454:
		return b == 12441 ? 33566964 : -1;
	case 12459:
		return b == 12441 ? 33566892 : -1;
	case 12461:
		return b == 12441 ? 33566894 : -1;
	case 12463:
		return b == 12441 ? 33566896 : -1;
	case 12465:
		return b == 12441 ? 33566898 : -1;
	case 12467:
		return b == 12441 ? 33566900 : -1;
	case 12469:
		return b == 12441 ? 33566902 : -1;
	case 12471:
		return b == 12441 ? 33566904 : -1;
	case 12473:
		return b == 12441 ? 33566906 : -1;
	case 12475:
		return b == 12441 ? 33566908 : -1;
	case 12477:
		return b == 12441 ? 33566910 : -1;
	case 12479:
		return b == 12441 ? 33566912 : -1;
	case 12481:
		return b == 12441 ? 33566914 : -1;
	case 12484:
		return b == 12441 ? 33566917 : -1;
	case 12486:
		return b == 12441 ? 33566919 : -1;
	case 12488:
		return b == 12441 ? 33566921 : -1;
	case 12495:
		switch (b) {
		case 12441: return 33566928;
		case 12442: return 33566929;
		default: return -1;
		}
	case 12498:
		switch (b) {
		case 12441: return 33566931;
		case 12442: return 33566932;
		default: return -1;
		}
	case 12501:
		switch (b) {
		case 12441: return 33566934;
		case 12442: return 33566935;
		default: return -1;
		}
	case 12504:
		switch (b) {
		case 12441: return 33566937;
		case 12442: return 33566938;
		default: return -1;
		}
	case 12507:
		switch (b) {
		case 12441: return 33566940;
		case 12442: return 33566941;
		default: return -1;
		}
	case 12527:
		return b == 12441 ? 33566967 : -1;
	case 12528:
		return b == 12441 ? 33566968 : -1;
	case 12529:
		return b == 12441 ? 33566969 : -1;
	case 12530:
		return b == 12441 ? 33566970 : -1;
	case 12541:
		return b == 12441 ? 33566974 : -1;
	case 69785:
		return b == 69818 ? 33624218 : -1;
	case 69787:
		return b == 69818 ? 33624220 : -1;
	case 69797:
		return b == 69818 ? 33624235 : -1;
	case 69937:
		return b == 69927 ? 33624366 : -1;
	case 69938:
		return b == 69927 ? 33624367 : -1;
	case 119127:
		return b == 119141 ? 33673566 : -1;
	case 119128:
		return b == 119141 ? 33673567 : -1;
	case 119225:
		return b == 119141 ? 33673659 : -1;
	case 119226:
		return b == 119141 ? 33673660 : -1;
	default: return -1;
	}
}
