//---------------------------------------------------------------------------------------
//  Smile Programming Language Interpreter
//  Copyright 2004-2019 Sean Werkema
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//---------------------------------------------------------------------------------------

//--------------------------------------------------------------
// WARNING: This file was generated automatically. Do not edit!
//
// The contents of this file are aggregated from data files
// provided by the Unicode Consortium, www.unicode.org.
//--------------------------------------------------------------

#include <smile/string.h>
#include <smile/internal/unicode.h>

#ifdef _MSC_VER
	extern const SByte Unicode_GeneralCategoryData[];
	extern const UInt16 Unicode_GeneralCategoryBmpLookup[];
	extern const Unicode_ExtendedTuple Unicode_GeneralCategoryExtendedLookup[];
	extern const Int Unicode_GeneralCategoryExtendedLookupCount;
#else
	static const SByte Unicode_GeneralCategoryData[];
	static const UInt16 Unicode_GeneralCategoryBmpLookup[];
	static const Unicode_ExtendedTuple Unicode_GeneralCategoryExtendedLookup[];
	static const Int Unicode_GeneralCategoryExtendedLookupCount;
#endif

#define Cn 0x00
#define Cc 0x01
#define Cf 0x02
#define Cs 0x03
#define Co 0x04
#define Lu 0x11
#define Ll 0x12
#define Lt 0x13
#define Lm 0x19
#define Lo 0x1A
#define Mn 0x21
#define Mc 0x22
#define Me 0x23
#define Nd 0x31
#define Nl 0x32
#define No 0x33
#define Zs 0x41
#define Zl 0x42
#define Zp 0x43
#define Pc 0x59
#define Pd 0x5A
#define Ps 0x5B
#define Pe 0x5C
#define Pi 0x5D
#define Pf 0x5E
#define Po 0x5F
#define Sm 0x69
#define Sc 0x6A
#define Sk 0x6B
#define So 0x6C

// General Category values for various sets of code points.
// Each row of 16 values is indexed by the lookup tables below.
// Rows near the top are more likely to be used than rows near the bottom.
const SByte Unicode_GeneralCategoryData[8512] = {
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 0, used 67960 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 1, used 585 times
	So, So, So, So, So, So, So, So, So, So, So, So, So, So, So, So,	// Row 2, used 216 times
	Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm,	// Row 3, used 48 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll,	// Row 4, used 47 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 5, used 32 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 6, used 31 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 7, used 22 times
	Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl,	// Row 8, used 11 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 9, used 10 times
	No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No,	// Row 10, used 10 times
	Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 11, used 8 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn,	// Row 12, used 7 times
	So, So, So, So, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 13, used 7 times
	Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm,	// Row 14, used 6 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 15, used 6 times
	Lo, Lo, Mn, Mn, Cn, Cn, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd,	// Row 16, used 6 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 17, used 6 times
	Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf,	// Row 18, used 6 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn,	// Row 19, used 5 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn,	// Row 20, used 5 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn,	// Row 21, used 5 times
	So, So, So, So, So, So, So, So, So, So, So, So, So, So, So, Cn,	// Row 22, used 5 times
	Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc, Cc,	// Row 23, used 4 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 24, used 4 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn,	// Row 25, used 4 times
	So, So, So, So, So, So, So, So, So, So, So, So, Cn, Cn, Cn, Cn,	// Row 26, used 4 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 27, used 4 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn,	// Row 28, used 3 times
	Lo, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 29, used 3 times
	Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 30, used 3 times
	Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 31, used 3 times
	Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 32, used 3 times
	Mn, Mn, Mc, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 33, used 3 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lt, Lt, Lt, Lt, Lt, Lt, Lt, Lt,	// Row 34, used 3 times
	So, So, So, So, So, So, So, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 35, used 3 times
	So, So, So, So, So, So, So, So, So, So, So, Cn, Cn, Cn, Cn, Cn,	// Row 36, used 3 times
	Cn, So, So, So, So, So, So, So, So, So, So, So, So, So, So, So,	// Row 37, used 3 times
	So, So, So, So, So, So, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 38, used 3 times
	Cs, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 39, used 3 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cs,	// Row 40, used 3 times
	Co, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 41, used 3 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 42, used 3 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd,	// Row 43, used 3 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Po, Po, Sm, Sm, Sm, Po,	// Row 44, used 2 times
	Po, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 45, used 2 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Ps, Po, Pe, Sk, Pc,	// Row 46, used 2 times
	Sk, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 47, used 2 times
	Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk,	// Row 48, used 2 times
	Mn, Mn, Mn, Mc, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 49, used 2 times
	Cn, Mn, Mc, Mc, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Lo,	// Row 50, used 2 times
	Cn, Cn, Cn, Cn, Cn, Cn, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd,	// Row 51, used 2 times
	Cn, Cn, Mc, Mc, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo,	// Row 52, used 2 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Po, Po, Po, Po, Po, Po,	// Row 53, used 2 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Cn, Cn,	// Row 54, used 2 times
	Lo, Cn, Lo, Lo, Lo, Lo, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 55, used 2 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 56, used 2 times
	So, So, So, So, So, So, So, So, So, So, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 57, used 2 times
	Pd, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 58, used 2 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo,	// Row 59, used 2 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 60, used 2 times
	Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc,	// Row 61, used 2 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lm, Lm, Lm, Lm, Lm, Lm, Po, Po,	// Row 62, used 2 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 63, used 2 times
	Ll, Ll, Ll, Ll, Ll, Ll, Cn, Cn, Lu, Lu, Lu, Lu, Lu, Lu, Cn, Cn,	// Row 64, used 2 times
	No, No, No, No, No, No, No, No, No, No, So, So, So, So, So, So,	// Row 65, used 2 times
	So, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No,	// Row 66, used 2 times
	Po, Po, Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 67, used 2 times
	So, So, So, So, So, So, So, So, So, So, So, So, So, So, Cn, Cn,	// Row 68, used 2 times
	Ll, Ll, Ll, Ll, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 69, used 2 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Ll, Ll,	// Row 70, used 2 times
	Lu, Lu, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 71, used 2 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Lu, Lu, Lu,	// Row 72, used 2 times
	Lu, Lu, Lu, Lu, Lu, Lu, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 73, used 2 times
	So, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 74, used 2 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Co, Cn, Cn,	// Row 75, used 2 times
	Zs, Po, Po, Po, Sc, Po, Po, Po, Ps, Pe, Po, Sm, Po, Pd, Po, Po,	// Row 76, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ps, Sm, Pe, Sm, Cc,	// Row 77, used 1 times
	Zs, Po, Sc, Sc, Sc, Sc, So, Po, Sk, So, Lo, Pi, Sm, Cf, So, Sk,	// Row 78, used 1 times
	So, Sm, No, No, Sk, Ll, Po, Po, Sk, No, Lo, Pf, No, No, No, Po,	// Row 79, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Sm, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Ll,	// Row 80, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Sm, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 81, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu,	// Row 82, used 1 times
	Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Ll, Lu, Ll, Lu, Ll, Lu, Ll,	// Row 83, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Lu, Ll, Lu, Ll, Lu, Ll, Ll,	// Row 84, used 1 times
	Ll, Lu, Lu, Ll, Lu, Ll, Lu, Lu, Ll, Lu, Lu, Lu, Ll, Ll, Lu, Lu,	// Row 85, used 1 times
	Lu, Lu, Ll, Lu, Lu, Ll, Lu, Lu, Lu, Ll, Ll, Ll, Lu, Lu, Ll, Lu,	// Row 86, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Lu, Ll, Lu, Ll, Ll, Lu, Ll, Lu, Lu,	// Row 87, used 1 times
	Ll, Lu, Lu, Lu, Ll, Lu, Ll, Lu, Lu, Ll, Ll, Lo, Lu, Ll, Ll, Ll,	// Row 88, used 1 times
	Lo, Lo, Lo, Lo, Lu, Lt, Ll, Lu, Lt, Ll, Lu, Lt, Ll, Lu, Ll, Lu,	// Row 89, used 1 times
	Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Ll, Lu, Ll,	// Row 90, used 1 times
	Ll, Lu, Lt, Ll, Lu, Ll, Lu, Lu, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll,	// Row 91, used 1 times
	Lu, Ll, Lu, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Lu, Ll, Lu, Lu, Ll,	// Row 92, used 1 times
	Ll, Lu, Ll, Lu, Lu, Lu, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll,	// Row 93, used 1 times
	Ll, Ll, Ll, Ll, Lo, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 94, used 1 times
	Lm, Lm, Sk, Sk, Sk, Sk, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm,	// Row 95, used 1 times
	Lm, Lm, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk,	// Row 96, used 1 times
	Lm, Lm, Lm, Lm, Lm, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Lm, Sk, Lm, Sk,	// Row 97, used 1 times
	Lu, Ll, Lu, Ll, Lm, Sk, Lu, Ll, Cn, Cn, Lm, Ll, Ll, Ll, Po, Cn,	// Row 98, used 1 times
	Cn, Cn, Cn, Cn, Sk, Sk, Lu, Po, Lu, Lu, Lu, Cn, Lu, Cn, Lu, Lu,	// Row 99, used 1 times
	Ll, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 100, used 1 times
	Lu, Lu, Cn, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Ll, Ll, Ll, Ll,	// Row 101, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu,	// Row 102, used 1 times
	Ll, Ll, Lu, Lu, Lu, Ll, Ll, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll,	// Row 103, used 1 times
	Ll, Ll, Ll, Ll, Lu, Ll, Sm, Lu, Ll, Lu, Lu, Ll, Ll, Lu, Lu, Lu,	// Row 104, used 1 times
	Lu, Ll, So, Mn, Mn, Mn, Mn, Mn, Me, Me, Lu, Ll, Lu, Ll, Lu, Ll,	// Row 105, used 1 times
	Lu, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Ll,	// Row 106, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 107, used 1 times
	Cn, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 108, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Cn, Cn, Lm, Po, Po, Po, Po, Po, Po,	// Row 109, used 1 times
	Cn, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 110, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Cn, Po, Pd, Cn, Cn, Cn, Cn, Sc,	// Row 111, used 1 times
	Cn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 112, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Pd, Mn,	// Row 113, used 1 times
	Po, Mn, Mn, Po, Mn, Mn, Po, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 114, used 1 times
	Lo, Lo, Lo, Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 115, used 1 times
	Cf, Cf, Cf, Cf, Cf, Cn, Sm, Sm, Sm, Po, Po, Sc, Po, Po, So, So,	// Row 116, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Po, Cf, Cn, Po, Po,	// Row 117, used 1 times
	Lm, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Mn,	// Row 118, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Po, Po, Po, Po, Lo, Lo,	// Row 119, used 1 times
	Mn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 120, used 1 times
	Lo, Lo, Lo, Lo, Po, Lo, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cf, So, Mn,	// Row 121, used 1 times
	Mn, Mn, Mn, Mn, Mn, Lm, Lm, Mn, Mn, So, Mn, Mn, Mn, Mn, Lo, Lo,	// Row 122, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Lo, Lo, Lo, So, So, Lo,	// Row 123, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Cn, Cf,	// Row 124, used 1 times
	Lo, Mn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 125, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cn, Cn, Lo, Lo, Lo,	// Row 126, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 127, used 1 times
	Mn, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 128, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Mn,	// Row 129, used 1 times
	Mn, Mn, Mn, Mn, Lm, Lm, So, Po, Po, Po, Lm, Cn, Cn, Cn, Cn, Cn,	// Row 130, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Lm, Mn, Mn, Mn, Mn, Mn,	// Row 131, used 1 times
	Mn, Mn, Mn, Mn, Lm, Mn, Mn, Mn, Lm, Mn, Mn, Mn, Mn, Mn, Cn, Cn,	// Row 132, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Cn,	// Row 133, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Cn, Cn, Po, Cn,	// Row 134, used 1 times
	Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn,	// Row 135, used 1 times
	Cn, Cn, Cn, Cn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 136, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cn,	// Row 137, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mc, Mn, Lo, Mc, Mc,	// Row 138, used 1 times
	Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mc, Mc, Mc, Mc, Mn, Mc, Mc,	// Row 139, used 1 times
	Lo, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 140, used 1 times
	Lo, Lo, Mn, Mn, Po, Po, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd,	// Row 141, used 1 times
	Po, Lm, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 142, used 1 times
	Lo, Cn, Lo, Cn, Cn, Cn, Lo, Lo, Lo, Lo, Cn, Cn, Mn, Lo, Mc, Mc,	// Row 143, used 1 times
	Mc, Mn, Mn, Mn, Mn, Cn, Cn, Mc, Mc, Cn, Cn, Mc, Mc, Mn, Lo, Cn,	// Row 144, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Mc, Cn, Cn, Cn, Cn, Lo, Lo, Cn, Lo,	// Row 145, used 1 times
	Lo, Lo, Sc, Sc, No, No, No, No, No, No, So, Sc, Cn, Cn, Cn, Cn,	// Row 146, used 1 times
	Cn, Mn, Mn, Mc, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Lo,	// Row 147, used 1 times
	Lo, Cn, Lo, Lo, Cn, Lo, Lo, Cn, Lo, Lo, Cn, Cn, Mn, Cn, Mc, Mc,	// Row 148, used 1 times
	Mc, Mn, Mn, Cn, Cn, Cn, Cn, Mn, Mn, Cn, Cn, Mn, Mn, Mn, Cn, Cn,	// Row 149, used 1 times
	Cn, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Lo, Lo, Lo, Lo, Cn, Lo, Cn,	// Row 150, used 1 times
	Mn, Mn, Lo, Lo, Lo, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 151, used 1 times
	Cn, Mn, Mn, Mc, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo,	// Row 152, used 1 times
	Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 153, used 1 times
	Lo, Cn, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Mn, Lo, Mc, Mc,	// Row 154, used 1 times
	Mc, Mn, Mn, Mn, Mn, Mn, Cn, Mn, Mn, Mc, Cn, Mc, Mc, Mn, Cn, Cn,	// Row 155, used 1 times
	Po, Sc, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 156, used 1 times
	Lo, Cn, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Mn, Lo, Mc, Mn,	// Row 157, used 1 times
	Mc, Mn, Mn, Mn, Mn, Cn, Cn, Mc, Mc, Cn, Cn, Mc, Mc, Mn, Cn, Cn,	// Row 158, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Mn, Mc, Cn, Cn, Cn, Cn, Lo, Lo, Cn, Lo,	// Row 159, used 1 times
	So, Lo, No, No, No, No, No, No, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 160, used 1 times
	Cn, Cn, Mn, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Lo, Lo,	// Row 161, used 1 times
	Lo, Cn, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Lo, Lo, Cn, Lo, Cn, Lo, Lo,	// Row 162, used 1 times
	Cn, Cn, Cn, Lo, Lo, Cn, Cn, Cn, Lo, Lo, Lo, Cn, Cn, Cn, Lo, Lo,	// Row 163, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Mc, Mc,	// Row 164, used 1 times
	Mn, Mc, Mc, Cn, Cn, Cn, Mc, Mc, Mc, Cn, Mc, Mc, Mc, Mn, Cn, Cn,	// Row 165, used 1 times
	Lo, Cn, Cn, Cn, Cn, Cn, Cn, Mc, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 166, used 1 times
	No, No, No, So, So, So, So, So, So, Sc, So, Cn, Cn, Cn, Cn, Cn,	// Row 167, used 1 times
	Cn, Mc, Mc, Mc, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo,	// Row 168, used 1 times
	Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Lo, Mn, Mn,	// Row 169, used 1 times
	Mn, Mc, Mc, Mc, Mc, Cn, Mn, Mn, Mn, Cn, Mn, Mn, Mn, Mn, Cn, Cn,	// Row 170, used 1 times
	Cn, Cn, Cn, Cn, Cn, Mn, Mn, Cn, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 171, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, No, No, No, No, No, No, No, So,	// Row 172, used 1 times
	Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Mn, Lo, Mc, Mn,	// Row 173, used 1 times
	Mc, Mc, Mc, Mc, Mc, Cn, Mn, Mc, Mc, Cn, Mc, Mc, Mn, Mn, Cn, Cn,	// Row 174, used 1 times
	Cn, Cn, Cn, Cn, Cn, Mc, Mc, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Lo, Cn,	// Row 175, used 1 times
	Cn, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 176, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Lo, Mc, Mc,	// Row 177, used 1 times
	Mc, Mn, Mn, Mn, Mn, Cn, Mc, Mc, Mc, Cn, Mc, Mc, Mc, Mn, Lo, Cn,	// Row 178, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Mc, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 179, used 1 times
	No, No, No, No, No, No, Cn, Cn, Cn, So, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 180, used 1 times
	Cn, Cn, Mc, Mc, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 181, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 182, used 1 times
	Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Cn, Cn,	// Row 183, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Mn, Cn, Cn, Cn, Cn, Mc,	// Row 184, used 1 times
	Mc, Mc, Mn, Mn, Mn, Cn, Mn, Cn, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc,	// Row 185, used 1 times
	Cn, Cn, Mc, Mc, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 186, used 1 times
	Lo, Mn, Lo, Lo, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cn, Cn, Cn, Cn, Sc,	// Row 187, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lm, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Po,	// Row 188, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Po, Po, Cn, Cn, Cn, Cn,	// Row 189, used 1 times
	Cn, Lo, Lo, Cn, Lo, Cn, Cn, Lo, Lo, Cn, Lo, Cn, Cn, Lo, Cn, Cn,	// Row 190, used 1 times
	Cn, Cn, Cn, Cn, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 191, used 1 times
	Cn, Lo, Lo, Lo, Cn, Lo, Cn, Lo, Cn, Cn, Lo, Lo, Cn, Lo, Lo, Lo,	// Row 192, used 1 times
	Lo, Mn, Lo, Lo, Mn, Mn, Mn, Mn, Mn, Mn, Cn, Mn, Mn, Lo, Cn, Cn,	// Row 193, used 1 times
	Lo, Lo, Lo, Lo, Lo, Cn, Lm, Cn, Mn, Mn, Mn, Mn, Mn, Mn, Cn, Cn,	// Row 194, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Cn, Cn, Lo, Lo, Lo, Lo,	// Row 195, used 1 times
	Lo, So, So, So, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po,	// Row 196, used 1 times
	Po, Po, Po, So, Po, So, So, So, Mn, Mn, So, So, So, So, So, So,	// Row 197, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, No, No, No, No, No, No,	// Row 198, used 1 times
	No, No, No, No, So, Mn, So, Mn, So, Mn, Ps, Pe, Ps, Pe, Mc, Mc,	// Row 199, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 200, used 1 times
	Cn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mc,	// Row 201, used 1 times
	Mn, Mn, Mn, Mn, Mn, Po, Mn, Mn, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn,	// Row 202, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 203, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cn, So, So,	// Row 204, used 1 times
	So, So, So, So, So, So, Mn, So, So, So, So, So, So, Cn, So, So,	// Row 205, used 1 times
	Po, Po, Po, Po, Po, So, So, So, So, Po, Po, Cn, Cn, Cn, Cn, Cn,	// Row 206, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mc, Mc, Mn, Mn, Mn,	// Row 207, used 1 times
	Mn, Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mc, Mn, Mn, Mc, Mc, Mn, Mn, Lo,	// Row 208, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Mc, Mc, Mn, Mn, Lo, Lo, Lo, Lo, Mn, Mn,	// Row 209, used 1 times
	Mn, Lo, Mc, Mc, Mc, Lo, Lo, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Lo, Lo,	// Row 210, used 1 times
	Lo, Mn, Mn, Mn, Mn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 211, used 1 times
	Lo, Lo, Mn, Mc, Mc, Mn, Mn, Mc, Mc, Mc, Mc, Mc, Mc, Mn, Lo, Mc,	// Row 212, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Mc, Mc, Mc, Mn, So, So,	// Row 213, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Cn, Lu, Cn, Cn, Cn, Cn, Cn, Lu, Cn, Cn,	// Row 214, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Po, Lm, Lo, Lo, Lo,	// Row 215, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Cn, Lo, Lo, Lo, Lo, Cn, Cn,	// Row 216, used 1 times
	Lo, Cn, Lo, Lo, Lo, Lo, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn,	// Row 217, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Mn, Mn, Mn,	// Row 218, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Po, Po, No, No, No, No, No, No, No,	// Row 219, used 1 times
	No, No, No, No, No, No, No, No, No, No, No, No, No, Cn, Cn, Cn,	// Row 220, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Po, Po, Lo,	// Row 221, used 1 times
	Zs, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 222, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Ps, Pe, Cn, Cn, Cn,	// Row 223, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Po, Po, Po, Nl, Nl,	// Row 224, used 1 times
	Nl, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 225, used 1 times
	Lo, Lo, Mn, Mn, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 226, used 1 times
	Lo, Lo, Mn, Mn, Mn, Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 227, used 1 times
	Lo, Lo, Mn, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 228, used 1 times
	Lo, Cn, Mn, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 229, used 1 times
	Lo, Lo, Lo, Lo, Mn, Mn, Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mc, Mc,	// Row 230, used 1 times
	Mc, Mc, Mc, Mc, Mc, Mc, Mn, Mc, Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 231, used 1 times
	Mn, Mn, Mn, Mn, Po, Po, Po, Lm, Po, Po, Po, Sc, Lo, Mn, Cn, Cn,	// Row 232, used 1 times
	No, No, No, No, No, No, No, No, No, No, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 233, used 1 times
	Po, Po, Po, Po, Po, Po, Pd, Po, Po, Po, Po, Mn, Mn, Mn, Cf, Cn,	// Row 234, used 1 times
	Lo, Lo, Lo, Lm, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 235, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Lo, Cn, Cn, Cn, Cn, Cn,	// Row 236, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 237, used 1 times
	Mn, Mn, Mn, Mc, Mc, Mc, Mc, Mn, Mn, Mc, Mc, Mc, Cn, Cn, Cn, Cn,	// Row 238, used 1 times
	Mc, Mc, Mn, Mc, Mc, Mc, Mc, Mc, Mc, Mn, Mn, Mn, Cn, Cn, Cn, Cn,	// Row 239, used 1 times
	So, Cn, Cn, Cn, Po, Po, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd,	// Row 240, used 1 times
	Mc, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mc, Mc, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 241, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, No, Cn, Cn, Cn, So, So,	// Row 242, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mc, Mc, Mn, Cn, Cn, Po, Po,	// Row 243, used 1 times
	Lo, Lo, Lo, Lo, Lo, Mc, Mn, Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cn,	// Row 244, used 1 times
	Mn, Mc, Mn, Mc, Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mc, Mc, Mc,	// Row 245, used 1 times
	Mc, Mc, Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Cn, Cn, Mn,	// Row 246, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Lm, Po, Po, Po, Po, Po, Po, Cn, Cn,	// Row 247, used 1 times
	Mn, Mn, Mn, Mn, Mc, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 248, used 1 times
	Lo, Lo, Lo, Lo, Mn, Mc, Mn, Mn, Mn, Mn, Mn, Mc, Mn, Mc, Mc, Mc,	// Row 249, used 1 times
	Mc, Mc, Mn, Mc, Mc, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn,	// Row 250, used 1 times
	Po, So, So, So, So, So, So, So, So, So, So, Mn, Mn, Mn, Mn, Mn,	// Row 251, used 1 times
	Mn, Mn, Mn, Mn, So, So, So, So, So, So, So, So, So, Cn, Cn, Cn,	// Row 252, used 1 times
	Lo, Mc, Mn, Mn, Mn, Mn, Mc, Mc, Mn, Mn, Mc, Mn, Mc, Mc, Lo, Lo,	// Row 253, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mc, Mn, Mn, Mc, Mc, Mc, Mn, Mc, Mn,	// Row 254, used 1 times
	Mn, Mn, Mc, Mc, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Po, Po, Po, Po,	// Row 255, used 1 times
	Lo, Lo, Lo, Lo, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mn, Mn, Mn, Mn,	// Row 256, used 1 times
	Mn, Mn, Mn, Mn, Mc, Mc, Mn, Mn, Cn, Cn, Cn, Po, Po, Po, Po, Po,	// Row 257, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Cn, Cn, Cn, Lo, Lo, Lo,	// Row 258, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 259, used 1 times
	Mn, Mn, Mn, Po, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 260, used 1 times
	Mn, Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Lo, Lo, Lo, Lo, Mn, Lo, Lo,	// Row 261, used 1 times
	Lo, Lo, Mc, Mc, Mn, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 262, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lm, Lm, Lm, Lm,	// Row 263, used 1 times
	Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Ll, Ll, Ll, Ll, Ll,	// Row 264, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lm, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 265, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lm, Lm, Lm, Lm, Lm,	// Row 266, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Mn, Mn, Mn, Mn,	// Row 267, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Ll,	// Row 268, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Cn, Lu, Cn, Lu, Cn, Lu, Cn, Lu,	// Row 269, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Cn, Cn,	// Row 270, used 1 times
	Ll, Ll, Ll, Ll, Ll, Cn, Ll, Ll, Lu, Lu, Lu, Lu, Lt, Sk, Ll, Sk,	// Row 271, used 1 times
	Sk, Sk, Ll, Ll, Ll, Cn, Ll, Ll, Lu, Lu, Lu, Lu, Lt, Sk, Sk, Sk,	// Row 272, used 1 times
	Ll, Ll, Ll, Ll, Cn, Cn, Ll, Ll, Lu, Lu, Lu, Lu, Cn, Sk, Sk, Sk,	// Row 273, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Lu, Lu, Lu, Lu, Sk, Sk, Sk,	// Row 274, used 1 times
	Cn, Cn, Ll, Ll, Ll, Cn, Ll, Ll, Lu, Lu, Lu, Lu, Lt, Sk, Sk, Cn,	// Row 275, used 1 times
	Zs, Zs, Zs, Zs, Zs, Zs, Zs, Zs, Zs, Zs, Zs, Cf, Cf, Cf, Cf, Cf,	// Row 276, used 1 times
	Pd, Pd, Pd, Pd, Pd, Pd, Po, Po, Pi, Pf, Ps, Pi, Pi, Pf, Ps, Pi,	// Row 277, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Po, Zl, Zp, Cf, Cf, Cf, Cf, Cf, Zs,	// Row 278, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Po, Po, Pi, Pf, Po, Po, Po, Po, Pc,	// Row 279, used 1 times
	Pc, Po, Po, Po, Sm, Ps, Pe, Po, Po, Po, Po, Po, Po, Po, Po, Po,	// Row 280, used 1 times
	Po, Po, Sm, Po, Pc, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Zs,	// Row 281, used 1 times
	Cf, Cf, Cf, Cf, Cf, Cn, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf,	// Row 282, used 1 times
	No, Lm, Cn, Cn, No, No, No, No, No, No, Sm, Sm, Sm, Ps, Pe, Lm,	// Row 283, used 1 times
	No, No, No, No, No, No, No, No, No, No, Sm, Sm, Sm, Ps, Pe, Cn,	// Row 284, used 1 times
	Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Cn, Cn, Cn,	// Row 285, used 1 times
	Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc,	// Row 286, used 1 times
	Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Sc, Cn, Cn, Cn, Cn, Cn,	// Row 287, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Me, Me, Me,	// Row 288, used 1 times
	Me, Mn, Me, Me, Me, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 289, used 1 times
	Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 290, used 1 times
	So, So, Lu, So, So, So, So, Lu, So, So, Ll, Lu, Lu, Lu, Ll, Ll,	// Row 291, used 1 times
	Lu, Lu, Lu, Ll, So, Lu, So, So, Sm, Lu, Lu, Lu, Lu, Lu, So, So,	// Row 292, used 1 times
	So, So, So, So, Lu, So, Lu, So, Lu, So, Lu, Lu, Lu, Lu, So, Ll,	// Row 293, used 1 times
	Lu, Lu, Lu, Lu, Ll, Lo, Lo, Lo, Lo, Ll, So, So, Ll, Ll, Lu, Lu,	// Row 294, used 1 times
	Sm, Sm, Sm, Sm, Sm, Lu, Ll, Ll, Ll, Ll, So, Sm, So, So, Ll, So,	// Row 295, used 1 times
	Nl, Nl, Nl, Lu, Ll, Nl, Nl, Nl, Nl, No, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 296, used 1 times
	Sm, Sm, Sm, Sm, Sm, So, So, So, So, So, Sm, Sm, So, So, So, So,	// Row 297, used 1 times
	Sm, So, So, Sm, So, So, Sm, So, So, So, So, So, So, So, Sm, So,	// Row 298, used 1 times
	So, So, So, So, So, So, So, So, So, So, So, So, So, So, Sm, Sm,	// Row 299, used 1 times
	So, So, Sm, So, Sm, So, So, So, So, So, So, So, So, So, So, So,	// Row 300, used 1 times
	So, So, So, So, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm,	// Row 301, used 1 times
	So, So, So, So, So, So, So, So, Ps, Pe, Ps, Pe, So, So, So, So,	// Row 302, used 1 times
	Sm, Sm, So, So, So, So, So, So, So, Ps, Pe, So, So, So, So, So,	// Row 303, used 1 times
	So, So, So, So, So, So, So, So, So, So, So, So, Sm, So, So, So,	// Row 304, used 1 times
	So, So, So, So, So, So, So, So, So, So, So, Sm, Sm, Sm, Sm, Sm,	// Row 305, used 1 times
	Sm, Sm, Sm, Sm, So, So, So, So, So, So, So, So, So, So, So, So,	// Row 306, used 1 times
	So, So, So, So, So, So, So, So, So, So, So, So, Sm, Sm, Sm, Sm,	// Row 307, used 1 times
	Sm, Sm, So, So, So, So, So, So, So, So, So, So, So, So, So, So,	// Row 308, used 1 times
	No, No, No, No, No, No, No, No, No, No, No, No, So, So, So, So,	// Row 309, used 1 times
	So, So, So, So, So, So, So, So, So, So, No, No, No, No, No, No,	// Row 310, used 1 times
	So, So, So, So, So, So, So, Sm, So, So, So, So, So, So, So, So,	// Row 311, used 1 times
	So, Sm, So, So, So, So, So, So, So, So, So, So, So, So, So, So,	// Row 312, used 1 times
	So, So, So, So, So, So, So, So, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm,	// Row 313, used 1 times
	So, So, So, So, So, So, So, So, So, So, So, So, So, So, So, Sm,	// Row 314, used 1 times
	So, So, So, So, So, So, So, So, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe,	// Row 315, used 1 times
	Ps, Pe, Ps, Pe, Ps, Pe, No, No, No, No, No, No, No, No, No, No,	// Row 316, used 1 times
	No, No, No, No, So, So, So, So, So, So, So, So, So, So, So, So,	// Row 317, used 1 times
	Sm, Sm, Sm, Sm, Sm, Ps, Pe, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm,	// Row 318, used 1 times
	Sm, Sm, Sm, Sm, Sm, Sm, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe,	// Row 319, used 1 times
	Sm, Sm, Sm, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Ps,	// Row 320, used 1 times
	Pe, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Sm, Sm, Sm, Sm, Sm, Sm, Sm,	// Row 321, used 1 times
	Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Ps, Pe, Ps, Pe, Sm, Sm, Sm, Sm,	// Row 322, used 1 times
	Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Sm, Ps, Pe, Sm, Sm,	// Row 323, used 1 times
	Sm, Sm, Sm, Sm, Sm, So, So, Sm, Sm, Sm, Sm, Sm, Sm, Cn, Cn, Cn,	// Row 324, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Cn,	// Row 325, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Cn,	// Row 326, used 1 times
	Lu, Ll, Lu, Lu, Lu, Ll, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Lu, Lu,	// Row 327, used 1 times
	Lu, Ll, Lu, Ll, Ll, Lu, Ll, Ll, Ll, Ll, Ll, Ll, Lm, Lm, Lu, Lu,	// Row 328, used 1 times
	Lu, Ll, Lu, Ll, Ll, So, So, So, So, So, So, Lu, Ll, Lu, Ll, Mn,	// Row 329, used 1 times
	Mn, Mn, Lu, Ll, Cn, Cn, Cn, Cn, Cn, Po, Po, Po, Po, No, Po, Po,	// Row 330, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Cn, Ll, Cn, Cn, Cn, Cn, Cn, Ll, Cn, Cn,	// Row 331, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Lm,	// Row 332, used 1 times
	Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Mn,	// Row 333, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 334, used 1 times
	Po, Po, Pi, Pf, Pi, Pf, Po, Po, Po, Pi, Pf, Po, Pi, Pf, Po, Po,	// Row 335, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Pd, Po, Po, Pd, Po, Pi, Pf, Po, Po,	// Row 336, used 1 times
	Pi, Pf, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Po, Po, Po, Po, Po, Lm,	// Row 337, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Pd, Pd, Cn, Cn, Cn, Cn,	// Row 338, used 1 times
	So, So, So, So, So, So, So, So, So, So, Cn, So, So, So, So, So,	// Row 339, used 1 times
	Zs, Po, Po, Po, So, Lm, Lo, Nl, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe,	// Row 340, used 1 times
	Ps, Pe, So, So, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Pd, Ps, Pe, Pe,	// Row 341, used 1 times
	So, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Mn, Mn, Mn, Mn, Mc, Mc,	// Row 342, used 1 times
	Pd, Lm, Lm, Lm, Lm, Lm, So, So, Nl, Nl, Nl, Lm, Lo, Po, So, So,	// Row 343, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Mn, Mn, Sk, Sk, Lm, Lm, Lo,	// Row 344, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Po, Lm, Lm, Lm, Lo,	// Row 345, used 1 times
	Cn, Cn, Cn, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 346, used 1 times
	So, So, No, No, No, No, So, So, So, So, So, So, So, So, So, So,	// Row 347, used 1 times
	So, So, So, So, So, So, So, So, No, No, No, No, No, No, No, No,	// Row 348, used 1 times
	Cn, Cn, Cn, Cn, Cn, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 349, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Lo, Cn, Cn, Cn,	// Row 350, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lm, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 351, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lm, Po, Po, Po,	// Row 352, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Lo, Lo, Cn, Cn, Cn, Cn,	// Row 353, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lo, Mn,	// Row 354, used 1 times
	Me, Me, Me, Po, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Po, Lm,	// Row 355, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Mn,	// Row 356, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl, Nl,	// Row 357, used 1 times
	Mn, Mn, Po, Po, Po, Po, Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 358, used 1 times
	Sk, Sk, Sk, Sk, Sk, Sk, Sk, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm,	// Row 359, used 1 times
	Sk, Sk, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll,	// Row 360, used 1 times
	Ll, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll,	// Row 361, used 1 times
	Lm, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Ll, Lu, Ll, Lu, Lu, Ll,	// Row 362, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lm, Sk, Sk, Lu, Ll, Lu, Ll, Cn,	// Row 363, used 1 times
	Lu, Ll, Lu, Ll, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 364, used 1 times
	Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Ll, Lu, Cn, Cn, Cn, Cn, Cn,	// Row 365, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Lm, Lm, Ll, Lo, Lo, Lo, Lo, Lo,	// Row 366, used 1 times
	Lo, Lo, Mn, Lo, Lo, Lo, Mn, Lo, Lo, Lo, Lo, Mn, Lo, Lo, Lo, Lo,	// Row 367, used 1 times
	Lo, Lo, Lo, Mc, Mc, Mn, Mn, Mc, So, So, So, So, Cn, Cn, Cn, Cn,	// Row 368, used 1 times
	No, No, No, No, No, No, So, So, Sc, So, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 369, used 1 times
	Lo, Lo, Lo, Lo, Po, Po, Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 370, used 1 times
	Mc, Mc, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 371, used 1 times
	Lo, Lo, Lo, Lo, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc,	// Row 372, used 1 times
	Mc, Mc, Mc, Mc, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Po, Po,	// Row 373, used 1 times
	Mn, Mn, Lo, Lo, Lo, Lo, Lo, Lo, Po, Po, Po, Lo, Cn, Cn, Cn, Cn,	// Row 374, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Po, Po,	// Row 375, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 376, used 1 times
	Mn, Mn, Mc, Mc, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Po,	// Row 377, used 1 times
	Lo, Lo, Lo, Mn, Mc, Mc, Mn, Mn, Mn, Mn, Mc, Mc, Mn, Mc, Mc, Mc,	// Row 378, used 1 times
	Mc, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Po, Cn, Lm,	// Row 379, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Cn, Cn, Cn, Cn, Po, Po,	// Row 380, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Mn, Mn, Mc,	// Row 381, used 1 times
	Mc, Mn, Mn, Mc, Mc, Mn, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 382, used 1 times
	Lo, Lo, Lo, Mn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mc, Cn, Cn,	// Row 383, used 1 times
	Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Cn, Cn, Po, Po, Po, Po,	// Row 384, used 1 times
	Lm, Lo, Lo, Lo, Lo, Lo, Lo, So, So, So, Lo, Mc, Cn, Cn, Cn, Cn,	// Row 385, used 1 times
	Mn, Lo, Mn, Mn, Mn, Lo, Lo, Mn, Mn, Lo, Lo, Lo, Lo, Lo, Mn, Mn,	// Row 386, used 1 times
	Lo, Mn, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 387, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Lo, Lo, Lm, Po, Po,	// Row 388, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mc, Mn, Mn, Mc, Mc,	// Row 389, used 1 times
	Po, Po, Lo, Lm, Lm, Mc, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 390, used 1 times
	Cn, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Cn,	// Row 391, used 1 times
	Cn, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 392, used 1 times
	Lo, Lo, Lo, Mc, Mc, Mn, Mc, Mc, Mn, Mc, Mc, Po, Mc, Mn, Cn, Cn,	// Row 393, used 1 times
	Cn, Cn, Cn, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 394, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Lo, Lo, Lo, Lo, Lo,	// Row 395, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Co,	// Row 396, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 397, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 398, used 1 times
	Cn, Cn, Cn, Ll, Ll, Ll, Ll, Ll, Cn, Cn, Cn, Cn, Cn, Lo, Mn, Lo,	// Row 399, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Sm, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 400, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Cn,	// Row 401, used 1 times
	Lo, Lo, Cn, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 402, used 1 times
	Lo, Lo, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk, Sk,	// Row 403, used 1 times
	Sk, Sk, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 404, used 1 times
	Cn, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 405, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Ps, Pe,	// Row 406, used 1 times
	Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 407, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Sc, So, Cn, Cn,	// Row 408, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Ps, Pe, Po, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 409, used 1 times
	Po, Pd, Pd, Pc, Pc, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Ps, Pe, Ps,	// Row 410, used 1 times
	Pe, Ps, Pe, Ps, Pe, Po, Po, Ps, Pe, Po, Po, Po, Po, Pc, Pc, Pc,	// Row 411, used 1 times
	Po, Po, Po, Cn, Po, Po, Po, Po, Pd, Ps, Pe, Ps, Pe, Ps, Pe, Po,	// Row 412, used 1 times
	Po, Po, Sm, Pd, Sm, Sm, Sm, Cn, Po, Sc, Po, Po, Cn, Cn, Cn, Cn,	// Row 413, used 1 times
	Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 414, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cf,	// Row 415, used 1 times
	Cn, Po, Po, Po, Sc, Po, Po, Po, Ps, Pe, Po, Sm, Po, Pd, Po, Po,	// Row 416, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ps, Sm, Pe, Sm, Ps,	// Row 417, used 1 times
	Pe, Po, Ps, Pe, Po, Po, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 418, used 1 times
	Lm, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 419, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lm, Lm,	// Row 420, used 1 times
	Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 421, used 1 times
	Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Lo, Lo, Lo, Cn, Cn, Cn,	// Row 422, used 1 times
	Sc, Sc, Sm, Sk, So, Sc, Sc, Cn, So, Sm, Sm, Sm, Sm, So, So, Cn,	// Row 423, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cf, Cf, Cf, So, So, Cn, Cn,	// Row 424, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo,	// Row 425, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Cn, Lo,	// Row 426, used 1 times
	Po, Po, Po, Cn, Cn, Cn, Cn, No, No, No, No, No, No, No, No, No,	// Row 427, used 1 times
	No, No, No, No, Cn, Cn, Cn, So, So, So, So, So, So, So, So, So,	// Row 428, used 1 times
	Nl, Nl, Nl, Nl, Nl, No, No, No, No, So, So, So, So, So, So, So,	// Row 429, used 1 times
	So, So, So, So, So, So, So, So, So, So, No, Cn, Cn, Cn, Cn, Cn,	// Row 430, used 1 times
	So, So, So, So, So, So, So, So, So, So, So, So, So, Mn, Cn, Cn,	// Row 431, used 1 times
	No, No, No, No, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 432, used 1 times
	Lo, Nl, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Nl, Cn, Cn, Cn, Cn, Cn,	// Row 433, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Po,	// Row 434, used 1 times
	Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 435, used 1 times
	Po, Nl, Nl, Nl, Nl, Nl, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 436, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 437, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 438, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Cn, Cn, Cn, Lo, Cn, Cn, Lo,	// Row 439, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Cn, Po, No, No, No, No, No, No, No, No,	// Row 440, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, No, No, No, No, No, No, Cn, Cn, Cn, Po,	// Row 441, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Po,	// Row 442, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Lo, Lo,	// Row 443, used 1 times
	Lo, Mn, Mn, Mn, Cn, Mn, Mn, Cn, Cn, Cn, Cn, Cn, Mn, Mn, Mn, Mn,	// Row 444, used 1 times
	Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 445, used 1 times
	Lo, Lo, Lo, Lo, Cn, Cn, Cn, Cn, Mn, Mn, Mn, Cn, Cn, Cn, Cn, Mn,	// Row 446, used 1 times
	No, No, No, No, No, No, No, No, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 447, used 1 times
	Po, Po, Po, Po, Po, Po, Po, Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 448, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, No, No, Po,	// Row 449, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, Cn, Po, Po, Po, Po, Po, Po, Po,	// Row 450, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Cn, Cn, No, No, No, No, No, No, No, No,	// Row 451, used 1 times
	Lo, Lo, Lo, Cn, Cn, Cn, Cn, Cn, No, No, No, No, No, No, No, No,	// Row 452, used 1 times
	No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, Cn,	// Row 453, used 1 times
	Mc, Mn, Mc, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 454, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn,	// Row 455, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mn, Po, Po, Po, Po, Po, Po, Po, Cn, Cn,	// Row 456, used 1 times
	Cn, Cn, No, No, No, No, No, No, No, No, No, No, No, No, No, No,	// Row 457, used 1 times
	No, No, No, No, No, No, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd,	// Row 458, used 1 times
	Mc, Mc, Mc, Mn, Mn, Mn, Mn, Mc, Mc, Mn, Mn, Po, Po, Cf, Po, Po,	// Row 459, used 1 times
	Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 460, used 1 times
	Mn, Mn, Mn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 461, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mn, Mn, Mn, Mn, Mc, Mn, Mn, Mn,	// Row 462, used 1 times
	Mn, Mn, Mn, Mn, Mn, Cn, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd, Nd,	// Row 463, used 1 times
	Lo, Lo, Lo, Mc, Mc, Mc, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mn, Mc,	// Row 464, used 1 times
	Mc, Lo, Lo, Lo, Lo, Po, Po, Po, Po, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 465, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Mn, Mc, Mn, Mc, Mc,	// Row 466, used 1 times
	Mn, Mn, Mn, Mn, Mn, Mn, Mc, Mn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 467, used 1 times
	Nl, Nl, Nl, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 468, used 1 times
	Lo, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc,	// Row 469, used 1 times
	Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Mc, Cn,	// Row 470, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Mn,	// Row 471, used 1 times
	Mn, Mn, Mn, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm, Lm,	// Row 472, used 1 times
	Lo, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 473, used 1 times
	So, So, So, So, So, So, So, Cn, Cn, So, So, So, So, So, So, So,	// Row 474, used 1 times
	So, So, So, So, So, Mc, Mc, Mn, Mn, Mn, So, So, So, Mc, Mc, Mc,	// Row 475, used 1 times
	Mc, Mc, Mc, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Cf, Mn, Mn, Mn, Mn, Mn,	// Row 476, used 1 times
	Mn, Mn, Mn, So, So, Mn, Mn, Mn, Mn, Mn, Mn, Mn, So, So, So, So,	// Row 477, used 1 times
	So, So, So, So, So, So, So, So, So, So, Mn, Mn, Mn, Mn, So, So,	// Row 478, used 1 times
	So, So, Mn, Mn, Mn, So, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 479, used 1 times
	No, No, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 480, used 1 times
	Ll, Ll, Ll, Ll, Ll, Cn, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 481, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Cn, Lu, Lu,	// Row 482, used 1 times
	Cn, Cn, Lu, Cn, Cn, Lu, Lu, Cn, Cn, Lu, Lu, Lu, Lu, Cn, Lu, Lu,	// Row 483, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Ll, Ll, Ll, Ll, Cn, Ll, Cn, Ll, Ll, Ll,	// Row 484, used 1 times
	Ll, Ll, Ll, Ll, Cn, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 485, used 1 times
	Ll, Ll, Ll, Ll, Lu, Lu, Cn, Lu, Lu, Lu, Lu, Cn, Cn, Lu, Lu, Lu,	// Row 486, used 1 times
	Lu, Lu, Lu, Lu, Lu, Cn, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Cn, Ll, Ll,	// Row 487, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Lu, Cn, Lu, Lu, Lu, Lu, Cn,	// Row 488, used 1 times
	Lu, Lu, Lu, Lu, Lu, Cn, Lu, Cn, Cn, Cn, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 489, used 1 times
	Lu, Cn, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 490, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Cn, Cn, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 491, used 1 times
	Lu, Sm, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 492, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Sm, Ll, Ll, Ll, Ll,	// Row 493, used 1 times
	Ll, Ll, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 494, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Sm, Ll, Ll, Ll, Ll,	// Row 495, used 1 times
	Ll, Ll, Ll, Ll, Ll, Sm, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Lu, Lu, Lu,	// Row 496, used 1 times
	Lu, Lu, Lu, Lu, Lu, Sm, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 497, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Sm,	// Row 498, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu,	// Row 499, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Sm,	// Row 500, used 1 times
	Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Ll, Sm, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 501, used 1 times
	Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Lu, Sm, Ll, Ll, Ll, Ll, Ll, Ll,	// Row 502, used 1 times
	Ll, Ll, Ll, Sm, Ll, Ll, Ll, Ll, Ll, Ll, Lu, Ll, Cn, Cn, Nd, Nd,	// Row 503, used 1 times
	Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 504, used 1 times
	Cn, Lo, Lo, Cn, Lo, Cn, Cn, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Lo, Lo,	// Row 505, used 1 times
	Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Cn, Lo, Cn, Lo, Cn, Cn, Cn, Cn,	// Row 506, used 1 times
	Cn, Cn, Lo, Cn, Cn, Cn, Cn, Lo, Cn, Lo, Cn, Lo, Cn, Lo, Lo, Lo,	// Row 507, used 1 times
	Cn, Lo, Lo, Cn, Lo, Cn, Cn, Lo, Cn, Lo, Cn, Lo, Cn, Lo, Cn, Lo,	// Row 508, used 1 times
	Cn, Lo, Lo, Cn, Lo, Cn, Cn, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo,	// Row 509, used 1 times
	Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Cn, Lo, Cn,	// Row 510, used 1 times
	Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo,	// Row 511, used 1 times
	Cn, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo, Cn, Lo, Lo, Lo, Lo, Lo,	// Row 512, used 1 times
	Sm, Sm, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 513, used 1 times
	Cn, So, So, So, So, So, So, So, So, So, So, So, So, So, So, Cn,	// Row 514, used 1 times
	No, No, No, No, No, No, No, No, No, No, No, Cn, Cn, Cn, Cn, Cn,	// Row 515, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, So, So, So, So, So, So, So, So, So, So,	// Row 516, used 1 times
	So, So, So, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 517, used 1 times
	So, So, So, So, So, So, So, So, So, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 518, used 1 times
	So, So, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 519, used 1 times
	So, So, So, So, So, So, Cn, So, So, So, So, So, So, So, So, So,	// Row 520, used 1 times
	So, So, So, So, So, So, So, So, So, So, So, So, So, Cn, Cn, Cn,	// Row 521, used 1 times
	So, So, So, So, So, Cn, So, So, So, So, So, Cn, Cn, Cn, Cn, Cn,	// Row 522, used 1 times
	So, Cn, So, So, So, So, So, So, So, So, So, So, So, So, So, So,	// Row 523, used 1 times
	So, So, So, So, So, So, So, So, Cn, So, So, So, So, Cn, Cn, Cn,	// Row 524, used 1 times
	So, So, So, So, So, So, So, So, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 525, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, So, So, So, So, So,	// Row 526, used 1 times
	So, Cn, Cn, Cn, Cn, So, So, So, So, So, So, So, So, So, So, So,	// Row 527, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 528, used 1 times
	Cn, Cn, Cn, Cn, Lo, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 529, used 1 times
	Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Lo, Cn, Cn,	// Row 530, used 1 times
	Cn, Cf, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn, Cn,	// Row 531, used 1 times
};

// The paragraphs (sets of code points) in the Basic Multilingual Plane.
// Each value is an index to a row of the general-category data above.
const UInt16 Unicode_GeneralCategoryBmpLookup[4096] = {
	23,23,76,44,45,46,47,77,23,23,78,79,7,80,6,81,
	4,4,4,82,83,4,4,84,85,86,87,88,89,90,4,91,
	4,4,4,92,93,6,6,6,6,94,6,14,95,96,97,48,
	5,5,5,5,5,5,5,98,99,100,101,6,102,103,4,104,
	7,7,7,6,6,6,4,4,105,4,4,4,106,4,4,4,
	4,4,107,108,7,109,110,6,111,112,5,113,114,1,28,115,
	116,117,1,1,118,5,119,120,1,1,1,1,1,121,122,123,
	124,125,1,5,126,1,1,1,1,1,127,128,24,1,129,130,
	1,131,132,133,1,134,0,0,0,0,135,0,0,0,136,137,
	49,1,1,138,139,140,141,142,50,29,15,143,144,145,16,146,
	147,29,15,148,149,150,51,151,152,153,15,154,155,11,16,156,
	50,29,15,157,158,159,16,160,161,162,163,164,165,166,51,167,
	168,30,15,169,170,171,16,172,52,30,15,173,174,175,16,176,
	52,30,1,177,178,179,16,180,181,182,1,183,184,185,0,186,
	31,1,1,187,188,189,0,0,190,191,192,193,194,195,0,0,
	196,197,198,199,200,1,19,201,202,203,5,204,205,206,0,0,
	1,1,207,208,53,209,210,211,212,213,7,7,214,1,1,215,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,54,216,1,1,54,1,1,217,55,56,1,1,
	1,55,1,1,1,218,219,220,1,57,1,1,1,1,1,32,
	58,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,221,1,222,223,1,1,1,1,224,225,
	59,226,1,227,1,228,59,229,1,1,1,230,231,232,9,233,
	234,9,1,1,235,1,1,60,1,1,236,1,1,1,1,237,
	1,19,238,239,240,1,12,32,1,1,25,61,241,242,2,2,
	1,243,1,1,1,244,245,246,9,9,247,0,0,0,0,0,
	248,1,1,249,250,53,251,252,33,1,253,24,1,1,254,255,
	1,1,256,257,258,24,1,62,0,0,0,0,259,260,261,262,
	6,6,263,14,14,14,264,265,6,266,14,14,5,5,63,267,
	4,4,4,4,4,4,4,4,4,268,4,4,4,4,4,4,
	17,64,17,17,64,269,17,270,34,34,34,271,272,273,274,275,
	276,277,278,279,280,281,282,283,284,285,286,287,0,288,289,290,
	291,292,293,294,295,10,8,8,296,297,298,2,299,300,2,301,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
	302,2,303,2,2,2,2,304,2,305,3,306,2,307,308,13,
	2,2,35,0,36,0,10,10,10,309,2,2,2,2,310,10,
	2,2,2,2,2,2,2,2,2,2,2,311,312,2,2,313,
	2,2,2,2,2,2,314,2,2,2,2,2,2,2,2,2,
	37,2,2,2,2,2,315,316,10,317,2,2,318,3,319,3,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	3,3,3,3,3,3,3,3,320,321,3,3,3,322,3,323,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
	2,2,2,3,324,57,0,0,0,0,0,0,0,0,0,0,
	7,7,325,6,6,326,327,328,4,4,4,4,4,4,329,330,
	6,6,331,1,1,1,332,333,1,334,20,20,20,20,5,5,
	335,336,337,338,0,0,0,0,2,339,2,2,2,2,2,13,
	2,2,2,2,2,2,2,2,2,2,2,2,2,38,0,26,
	340,341,342,343,31,1,1,1,1,344,58,1,1,1,1,345,
	346,1,12,31,1,1,1,1,21,347,1,28,2,2,13,1,
	2,22,65,2,348,66,2,2,65,2,2,66,2,2,2,22,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,349,2,2,2,2,
	11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,350,0,0,0,
	1,351,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,19,2,2,2,35,1,1,62,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	352,1,353,0,4,4,354,355,4,356,1,1,1,1,357,358,
	48,359,360,361,4,4,4,362,363,364,365,0,0,0,0,366,
	367,1,368,369,1,1,1,370,371,1,1,372,373,9,5,374,
	24,1,375,1,376,377,1,19,49,1,1,378,379,380,0,0,
	1,1,381,382,383,384,1,385,1,1,1,386,387,388,389,390,
	391,392,20,0,0,0,0,0,0,0,0,0,1,1,393,9,
	11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,394,1,395,1,1,25,
	39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,40,39,0,0,0,0,0,0,40,
	39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40,
	41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,396,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,12,1,1,1,1,1,1,397,0,0,
	398,399,400,401,402,1,1,1,1,1,1,403,404,405,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,406,0,1,1,1,1,407,1,1,60,0,0,408,
	5,409,63,410,411,412,413,414,1,1,1,1,1,1,1,415,
	416,44,45,46,47,417,418,419,1,420,1,21,421,422,423,424,
};

// All assigned paragraphs above the BMP, sorted for efficient binary search.
// First value is paragraph ID (starting code point = (id + 4096) << 4).
// Second value is an index into a row of the general-category data above.
const Unicode_ExtendedTuple Unicode_GeneralCategoryExtendedLookup[575] = {
	{ 0,425 },
	{ 1,1 },
	{ 2,56 },
	{ 3,426 },
	{ 4,12 },
	{ 5,12 },
	{ 8,1 },
	{ 9,1 },
	{ 10,1 },
	{ 11,1 },
	{ 12,1 },
	{ 13,1 },
	{ 14,1 },
	{ 15,28 },
	{ 16,427 },
	{ 17,10 },
	{ 18,10 },
	{ 19,428 },
	{ 20,8 },
	{ 21,8 },
	{ 22,8 },
	{ 23,429 },
	{ 24,430 },
	{ 25,26 },
	{ 29,2 },
	{ 30,2 },
	{ 31,431 },
	{ 40,1 },
	{ 41,19 },
	{ 42,1 },
	{ 43,1 },
	{ 44,1 },
	{ 45,11 },
	{ 48,1 },
	{ 49,21 },
	{ 50,432 },
	{ 51,1 },
	{ 52,433 },
	{ 56,1 },
	{ 57,434 },
	{ 58,1 },
	{ 59,1 },
	{ 60,435 },
	{ 61,436 },
	{ 64,7 },
	{ 65,7 },
	{ 66,437 },
	{ 67,6 },
	{ 68,6 },
	{ 69,1 },
	{ 70,1 },
	{ 71,1 },
	{ 72,1 },
	{ 73,12 },
	{ 74,9 },
	{ 128,438 },
	{ 129,1 },
	{ 130,1 },
	{ 131,439 },
	{ 132,1 },
	{ 133,440 },
	{ 144,1 },
	{ 145,441 },
	{ 146,1 },
	{ 147,442 },
	{ 152,1 },
	{ 153,1 },
	{ 154,1 },
	{ 155,443 },
	{ 160,444 },
	{ 161,445 },
	{ 162,1 },
	{ 163,446 },
	{ 164,447 },
	{ 165,448 },
	{ 166,1 },
	{ 167,449 },
	{ 176,1 },
	{ 177,1 },
	{ 178,1 },
	{ 179,450 },
	{ 180,1 },
	{ 181,451 },
	{ 182,1 },
	{ 183,452 },
	{ 192,1 },
	{ 193,1 },
	{ 194,1 },
	{ 195,1 },
	{ 196,42 },
	{ 230,10 },
	{ 231,453 },
	{ 256,454 },
	{ 257,1 },
	{ 258,1 },
	{ 259,455 },
	{ 260,456 },
	{ 261,457 },
	{ 262,458 },
	{ 264,33 },
	{ 265,1 },
	{ 266,1 },
	{ 267,459 },
	{ 268,460 },
	{ 269,1 },
	{ 270,42 },
	{ 271,9 },
	{ 272,461 },
	{ 273,1 },
	{ 274,462 },
	{ 275,463 },
	{ 276,67 },
	{ 280,33 },
	{ 281,1 },
	{ 282,1 },
	{ 283,464 },
	{ 284,465 },
	{ 285,9 },
	{ 360,1 },
	{ 361,1 },
	{ 362,466 },
	{ 363,467 },
	{ 364,9 },
	{ 512,1 },
	{ 513,1 },
	{ 514,1 },
	{ 515,1 },
	{ 516,1 },
	{ 517,1 },
	{ 518,1 },
	{ 519,1 },
	{ 520,1 },
	{ 521,1 },
	{ 522,1 },
	{ 523,1 },
	{ 524,1 },
	{ 525,1 },
	{ 526,1 },
	{ 527,1 },
	{ 528,1 },
	{ 529,1 },
	{ 530,1 },
	{ 531,1 },
	{ 532,1 },
	{ 533,1 },
	{ 534,1 },
	{ 535,1 },
	{ 536,1 },
	{ 537,1 },
	{ 538,1 },
	{ 539,1 },
	{ 540,1 },
	{ 541,1 },
	{ 542,1 },
	{ 543,1 },
	{ 544,1 },
	{ 545,1 },
	{ 546,1 },
	{ 547,1 },
	{ 548,1 },
	{ 549,1 },
	{ 550,1 },
	{ 551,1 },
	{ 552,1 },
	{ 553,1 },
	{ 554,1 },
	{ 555,1 },
	{ 556,1 },
	{ 557,1 },
	{ 558,1 },
	{ 559,1 },
	{ 560,1 },
	{ 561,1 },
	{ 562,1 },
	{ 563,1 },
	{ 564,1 },
	{ 565,1 },
	{ 566,21 },
	{ 576,8 },
	{ 577,8 },
	{ 578,8 },
	{ 579,8 },
	{ 580,8 },
	{ 581,8 },
	{ 582,468 },
	{ 583,67 },
	{ 768,1 },
	{ 769,1 },
	{ 770,1 },
	{ 771,1 },
	{ 772,1 },
	{ 773,1 },
	{ 774,1 },
	{ 775,1 },
	{ 776,1 },
	{ 777,1 },
	{ 778,1 },
	{ 779,1 },
	{ 780,1 },
	{ 781,1 },
	{ 782,1 },
	{ 783,1 },
	{ 784,1 },
	{ 785,1 },
	{ 786,1 },
	{ 787,1 },
	{ 788,1 },
	{ 789,1 },
	{ 790,1 },
	{ 791,1 },
	{ 792,1 },
	{ 793,1 },
	{ 794,1 },
	{ 795,1 },
	{ 796,1 },
	{ 797,1 },
	{ 798,1 },
	{ 799,1 },
	{ 800,1 },
	{ 801,1 },
	{ 802,1 },
	{ 803,1 },
	{ 804,1 },
	{ 805,1 },
	{ 806,1 },
	{ 807,1 },
	{ 808,1 },
	{ 809,1 },
	{ 810,1 },
	{ 811,1 },
	{ 812,1 },
	{ 813,1 },
	{ 814,1 },
	{ 815,1 },
	{ 816,1 },
	{ 817,1 },
	{ 818,1 },
	{ 819,1 },
	{ 820,1 },
	{ 821,1 },
	{ 822,1 },
	{ 823,1 },
	{ 824,1 },
	{ 825,1 },
	{ 826,1 },
	{ 827,1 },
	{ 828,1 },
	{ 829,1 },
	{ 830,1 },
	{ 831,1 },
	{ 832,1 },
	{ 833,1 },
	{ 834,21 },
	{ 1664,1 },
	{ 1665,1 },
	{ 1666,1 },
	{ 1667,1 },
	{ 1668,1 },
	{ 1669,1 },
	{ 1670,1 },
	{ 1671,1 },
	{ 1672,1 },
	{ 1673,1 },
	{ 1674,1 },
	{ 1675,1 },
	{ 1676,1 },
	{ 1677,1 },
	{ 1678,1 },
	{ 1679,1 },
	{ 1680,1 },
	{ 1681,1 },
	{ 1682,1 },
	{ 1683,1 },
	{ 1684,1 },
	{ 1685,1 },
	{ 1686,1 },
	{ 1687,1 },
	{ 1688,1 },
	{ 1689,1 },
	{ 1690,1 },
	{ 1691,1 },
	{ 1692,1 },
	{ 1693,1 },
	{ 1694,1 },
	{ 1695,1 },
	{ 1696,1 },
	{ 1697,1 },
	{ 1698,1 },
	{ 1699,42 },
	{ 1776,1 },
	{ 1777,1 },
	{ 1778,1 },
	{ 1779,1 },
	{ 1780,32 },
	{ 1781,469 },
	{ 1782,61 },
	{ 1783,470 },
	{ 1784,471 },
	{ 1785,472 },
	{ 2816,473 },
	{ 3328,2 },
	{ 3329,2 },
	{ 3330,2 },
	{ 3331,2 },
	{ 3332,2 },
	{ 3333,2 },
	{ 3334,2 },
	{ 3335,2 },
	{ 3336,2 },
	{ 3337,2 },
	{ 3338,2 },
	{ 3339,2 },
	{ 3340,2 },
	{ 3341,2 },
	{ 3342,2 },
	{ 3343,38 },
	{ 3344,2 },
	{ 3345,2 },
	{ 3346,474 },
	{ 3347,2 },
	{ 3348,2 },
	{ 3349,2 },
	{ 3350,475 },
	{ 3351,476 },
	{ 3352,477 },
	{ 3353,2 },
	{ 3354,478 },
	{ 3355,2 },
	{ 3356,2 },
	{ 3357,68 },
	{ 3360,2 },
	{ 3361,2 },
	{ 3362,2 },
	{ 3363,2 },
	{ 3364,479 },
	{ 3376,2 },
	{ 3377,2 },
	{ 3378,2 },
	{ 3379,2 },
	{ 3380,2 },
	{ 3381,35 },
	{ 3382,10 },
	{ 3383,480 },
	{ 3392,7 },
	{ 3393,27 },
	{ 3394,6 },
	{ 3395,69 },
	{ 3396,70 },
	{ 3397,481 },
	{ 3398,17 },
	{ 3399,7 },
	{ 3400,71 },
	{ 3401,482 },
	{ 3402,483 },
	{ 3403,484 },
	{ 3404,485 },
	{ 3405,7 },
	{ 3406,27 },
	{ 3407,6 },
	{ 3408,486 },
	{ 3409,487 },
	{ 3410,6 },
	{ 3411,488 },
	{ 3412,489 },
	{ 3413,490 },
	{ 3414,72 },
	{ 3415,7 },
	{ 3416,73 },
	{ 3417,6 },
	{ 3418,7 },
	{ 3419,27 },
	{ 3420,6 },
	{ 3421,69 },
	{ 3422,70 },
	{ 3423,6 },
	{ 3424,17 },
	{ 3425,7 },
	{ 3426,71 },
	{ 3427,72 },
	{ 3428,7 },
	{ 3429,73 },
	{ 3430,6 },
	{ 3431,7 },
	{ 3432,27 },
	{ 3433,6 },
	{ 3434,491 },
	{ 3435,7 },
	{ 3436,492 },
	{ 3437,493 },
	{ 3438,494 },
	{ 3439,495 },
	{ 3440,6 },
	{ 3441,496 },
	{ 3442,7 },
	{ 3443,497 },
	{ 3444,498 },
	{ 3445,499 },
	{ 3446,500 },
	{ 3447,6 },
	{ 3448,501 },
	{ 3449,7 },
	{ 3450,502 },
	{ 3451,6 },
	{ 3452,503 },
	{ 3453,43 },
	{ 3454,43 },
	{ 3455,43 },
	{ 3808,504 },
	{ 3809,1 },
	{ 3810,505 },
	{ 3811,506 },
	{ 3812,507 },
	{ 3813,508 },
	{ 3814,509 },
	{ 3815,510 },
	{ 3816,511 },
	{ 3817,25 },
	{ 3818,512 },
	{ 3819,25 },
	{ 3823,513 },
	{ 3840,2 },
	{ 3841,2 },
	{ 3842,26 },
	{ 3843,2 },
	{ 3844,2 },
	{ 3845,2 },
	{ 3846,2 },
	{ 3847,2 },
	{ 3848,2 },
	{ 3849,13 },
	{ 3850,22 },
	{ 3851,514 },
	{ 3852,37 },
	{ 3853,37 },
	{ 3856,515 },
	{ 3857,2 },
	{ 3858,22 },
	{ 3859,2 },
	{ 3860,2 },
	{ 3861,2 },
	{ 3862,26 },
	{ 3863,2 },
	{ 3864,2 },
	{ 3865,36 },
	{ 3870,516 },
	{ 3871,2 },
	{ 3872,517 },
	{ 3873,2 },
	{ 3874,2 },
	{ 3875,36 },
	{ 3876,518 },
	{ 3877,519 },
	{ 3888,2 },
	{ 3889,2 },
	{ 3890,74 },
	{ 3891,520 },
	{ 3892,2 },
	{ 3893,2 },
	{ 3894,2 },
	{ 3895,521 },
	{ 3896,2 },
	{ 3897,13 },
	{ 3898,2 },
	{ 3899,2 },
	{ 3900,522 },
	{ 3902,2 },
	{ 3903,74 },
	{ 3904,2 },
	{ 3905,2 },
	{ 3906,2 },
	{ 3907,22 },
	{ 3908,523 },
	{ 3909,2 },
	{ 3910,2 },
	{ 3911,2 },
	{ 3912,2 },
	{ 3913,2 },
	{ 3914,2 },
	{ 3915,2 },
	{ 3916,2 },
	{ 3917,2 },
	{ 3918,2 },
	{ 3919,524 },
	{ 3920,2 },
	{ 3921,2 },
	{ 3922,2 },
	{ 3923,68 },
	{ 3924,13 },
	{ 3925,2 },
	{ 3926,525 },
	{ 3935,526 },
	{ 3936,2 },
	{ 3937,2 },
	{ 3938,2 },
	{ 3939,2 },
	{ 3940,527 },
	{ 3944,2 },
	{ 3945,2 },
	{ 3946,2 },
	{ 3947,2 },
	{ 3948,38 },
	{ 3952,2 },
	{ 3953,2 },
	{ 3954,2 },
	{ 3955,2 },
	{ 3956,2 },
	{ 3957,2 },
	{ 3958,2 },
	{ 3959,13 },
	{ 4096,11 },
	{ 6765,528 },
	{ 6768,11 },
	{ 7027,529 },
	{ 7028,11 },
	{ 7041,530 },
	{ 8064,1 },
	{ 8065,1 },
	{ 8066,1 },
	{ 8067,1 },
	{ 8068,1 },
	{ 8069,1 },
	{ 8070,1 },
	{ 8071,1 },
	{ 8072,1 },
	{ 8073,1 },
	{ 8074,1 },
	{ 8075,1 },
	{ 8076,1 },
	{ 8077,1 },
	{ 8078,1 },
	{ 8079,1 },
	{ 8080,1 },
	{ 8081,1 },
	{ 8082,1 },
	{ 8083,1 },
	{ 8084,1 },
	{ 8085,1 },
	{ 8086,1 },
	{ 8087,1 },
	{ 8088,1 },
	{ 8089,1 },
	{ 8090,1 },
	{ 8091,1 },
	{ 8092,1 },
	{ 8093,1 },
	{ 8094,1 },
	{ 8095,1 },
	{ 8096,1 },
	{ 8097,12 },
	{ 53248,531 },
	{ 53250,18 },
	{ 53251,18 },
	{ 53252,18 },
	{ 53253,18 },
	{ 53254,18 },
	{ 53255,18 },
	{ 53264,5 },
	{ 53265,5 },
	{ 53266,5 },
	{ 53267,5 },
	{ 53268,5 },
	{ 53269,5 },
	{ 53270,5 },
	{ 53271,5 },
	{ 53272,5 },
	{ 53273,5 },
	{ 53274,5 },
	{ 53275,5 },
	{ 53276,5 },
	{ 53277,5 },
	{ 53278,5 },
	{ 57344,41 },
	{ 61439,75 },
	{ 61440,41 },
	{ 65535,75 },
};

const Int Unicode_GeneralCategoryExtendedLookupCount = 575;

/// <summary>
/// Given a Unicode code point known to be > U+FFFF, this uses an efficient binary search
/// (with embedded fast linear search) to look up its General Category assignment.
/// 
/// Note: While a general binary search runs in O(lg n) time, this implementation will
/// always run in O(1) time because of the limited dataset to test against (but note that
/// O(1) is NOT the same as cryptographically-secure constant time; the execution time will
/// be variable, but it will still be within O(1)).  For current datasets, this implementation
/// will test the code-point against at most ~16 values before finding the correct answer.
/// </summary>
/// <param name="codePoint">A Unicode code point that must be higher than U+FFFF.</param>
/// <returns>The General Category assignment for that code point, or 0 if it is an unknown code point (or <= U+FFFF).</returns>
Byte Uni_GetGeneralCategoryExtended(UInt32 codePoint)
{
	Int paragraphId = (codePoint - 0x10000) >> 4;
	Int start = 0;
	Int end = Unicode_GeneralCategoryExtendedLookupCount;
	const Unicode_ExtendedTuple *tuples;

	// Use binary search until we get to a smallish range.  For the current Unicode dataset,
	// this will loop at most seven times.
	while (start + 8 < end)
	{
		Int midpt = (start + end) >> 1;
		UInt16 midptValue = Unicode_GeneralCategoryExtendedLookup[midpt].paragraphId;
		if (paragraphId == midptValue)
		{
			return Unicode_GeneralCategoryData[Unicode_GeneralCategoryExtendedLookup[midpt].offset + (codePoint & 0xF)];
		}
		else if (paragraphId < midptValue)
		{
			end = midpt;
		}
		else
		{
			start = midpt + 1;
		}
	}

#define TRY_AT(index) \
	if (paragraphId == tuples[index].paragraphId) \
		return Unicode_GeneralCategoryData[tuples[index].offset + (codePoint & 0xF)]

	// Use an unrolled linear search (via computed goto) when the range gets small,
	// since the binary reduction gets very expensive for small ranges.  This will also
	// test about eight values.
	tuples = Unicode_GeneralCategoryExtendedLookup + start;
	switch (end - start) {
		case 8: TRY_AT(7);
		case 7: TRY_AT(6);
		case 6: TRY_AT(5);
		case 5: TRY_AT(4);
		case 4: TRY_AT(3);
		case 3: TRY_AT(2);
		case 2: TRY_AT(1);
		case 1: TRY_AT(0);
		case 0:
		default: return 0;
	}
}

