//---------------------------------------------------------------------------------------
//  Smile Programming Language Interpreter
//  Copyright 2004-2019 Sean Werkema
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//---------------------------------------------------------------------------------------

//--------------------------------------------------------------
// WARNING: This file was generated automatically. Do not edit!
//
// The contents of this file are aggregated from data files
// provided by the Unicode Consortium, www.unicode.org.
//--------------------------------------------------------------

#include <smile/internal/unicode.h>

#define NO_MATCH	(-1)

#define ONE_POINT	(1 << 24)
#define TWO_POINTS	(2 << 24)
#define THREE_POINTS	(3 << 24)
#define FOUR_POINTS	(4 << 24)

Int32 Unicode_Compose(Int32 a, Int32 b, Int32 c, Int32 d)
{
	switch (a) {
	case 0x3C:
		return b == 0x338 ? (0x226E | TWO_POINTS) : NO_MATCH;
	case 0x3D:
		return b == 0x338 ? (0x2260 | TWO_POINTS) : NO_MATCH;
	case 0x3E:
		return b == 0x338 ? (0x226F | TWO_POINTS) : NO_MATCH;
	case 0x41:
		switch (b) {
		case 0x300: return (0xC0 | TWO_POINTS);
		case 0x301: return (0xC1 | TWO_POINTS);
		case 0x302:
			switch (c) {
			case 0x300: return (0x1EA6 | THREE_POINTS);
			case 0x301: return (0x1EA4 | THREE_POINTS);
			case 0x303: return (0x1EAA | THREE_POINTS);
			case 0x309: return (0x1EA8 | THREE_POINTS);
			default: return (0xC2 | TWO_POINTS);
			}
		case 0x303: return (0xC3 | TWO_POINTS);
		case 0x304: return (0x100 | TWO_POINTS);
		case 0x306:
			switch (c) {
			case 0x300: return (0x1EB0 | THREE_POINTS);
			case 0x301: return (0x1EAE | THREE_POINTS);
			case 0x303: return (0x1EB4 | THREE_POINTS);
			case 0x309: return (0x1EB2 | THREE_POINTS);
			default: return (0x102 | TWO_POINTS);
			}
		case 0x307:
			return c == 0x304 ? (0x1E0 | THREE_POINTS) : (0x226 | TWO_POINTS);
		case 0x308:
			return c == 0x304 ? (0x1DE | THREE_POINTS) : (0xC4 | TWO_POINTS);
		case 0x309: return (0x1EA2 | TWO_POINTS);
		case 0x30A:
			return c == 0x301 ? (0x1FA | THREE_POINTS) : (0x212B | TWO_POINTS);
		case 0x30C: return (0x1CD | TWO_POINTS);
		case 0x30F: return (0x200 | TWO_POINTS);
		case 0x311: return (0x202 | TWO_POINTS);
		case 0x323:
			return c == 0x302 ? (0x1EAC | THREE_POINTS)
				: c == 0x306 ? (0x1EB6 | THREE_POINTS)
				: (0x1EA0 | TWO_POINTS);
		case 0x325: return (0x1E00 | TWO_POINTS);
		case 0x328: return (0x104 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x42:
		switch (b) {
		case 0x307: return (0x1E02 | TWO_POINTS);
		case 0x323: return (0x1E04 | TWO_POINTS);
		case 0x331: return (0x1E06 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x43:
		switch (b) {
		case 0x301: return (0x106 | TWO_POINTS);
		case 0x302: return (0x108 | TWO_POINTS);
		case 0x307: return (0x10A | TWO_POINTS);
		case 0x30C: return (0x10C | TWO_POINTS);
		case 0x327:
			return c == 0x301 ? (0x1E08 | THREE_POINTS) : (0xC7 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x44:
		switch (b) {
		case 0x307: return (0x1E0A | TWO_POINTS);
		case 0x30C: return (0x10E | TWO_POINTS);
		case 0x323: return (0x1E0C | TWO_POINTS);
		case 0x327: return (0x1E10 | TWO_POINTS);
		case 0x32D: return (0x1E12 | TWO_POINTS);
		case 0x331: return (0x1E0E | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x45:
		switch (b) {
		case 0x300: return (0xC8 | TWO_POINTS);
		case 0x301: return (0xC9 | TWO_POINTS);
		case 0x302:
			switch (c) {
			case 0x300: return (0x1EC0 | THREE_POINTS);
			case 0x301: return (0x1EBE | THREE_POINTS);
			case 0x303: return (0x1EC4 | THREE_POINTS);
			case 0x309: return (0x1EC2 | THREE_POINTS);
			default: return (0xCA | TWO_POINTS);
			}
		case 0x303: return (0x1EBC | TWO_POINTS);
		case 0x304:
			return c == 0x300 ? (0x1E14 | THREE_POINTS)
				: c == 0x301 ? (0x1E16 | THREE_POINTS)
				: (0x112 | TWO_POINTS);
		case 0x306: return (0x114 | TWO_POINTS);
		case 0x307: return (0x116 | TWO_POINTS);
		case 0x308: return (0xCB | TWO_POINTS);
		case 0x309: return (0x1EBA | TWO_POINTS);
		case 0x30C: return (0x11A | TWO_POINTS);
		case 0x30F: return (0x204 | TWO_POINTS);
		case 0x311: return (0x206 | TWO_POINTS);
		case 0x323:
			return c == 0x302 ? (0x1EC6 | THREE_POINTS) : (0x1EB8 | TWO_POINTS);
		case 0x327:
			return c == 0x306 ? (0x1E1C | THREE_POINTS) : (0x228 | TWO_POINTS);
		case 0x328: return (0x118 | TWO_POINTS);
		case 0x32D: return (0x1E18 | TWO_POINTS);
		case 0x330: return (0x1E1A | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x46:
		return b == 0x307 ? (0x1E1E | TWO_POINTS) : NO_MATCH;
	case 0x47:
		switch (b) {
		case 0x301: return (0x1F4 | TWO_POINTS);
		case 0x302: return (0x11C | TWO_POINTS);
		case 0x304: return (0x1E20 | TWO_POINTS);
		case 0x306: return (0x11E | TWO_POINTS);
		case 0x307: return (0x120 | TWO_POINTS);
		case 0x30C: return (0x1E6 | TWO_POINTS);
		case 0x327: return (0x122 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x48:
		switch (b) {
		case 0x302: return (0x124 | TWO_POINTS);
		case 0x307: return (0x1E22 | TWO_POINTS);
		case 0x308: return (0x1E26 | TWO_POINTS);
		case 0x30C: return (0x21E | TWO_POINTS);
		case 0x323: return (0x1E24 | TWO_POINTS);
		case 0x327: return (0x1E28 | TWO_POINTS);
		case 0x32E: return (0x1E2A | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x49:
		switch (b) {
		case 0x300: return (0xCC | TWO_POINTS);
		case 0x301: return (0xCD | TWO_POINTS);
		case 0x302: return (0xCE | TWO_POINTS);
		case 0x303: return (0x128 | TWO_POINTS);
		case 0x304: return (0x12A | TWO_POINTS);
		case 0x306: return (0x12C | TWO_POINTS);
		case 0x307: return (0x130 | TWO_POINTS);
		case 0x308:
			return c == 0x301 ? (0x1E2E | THREE_POINTS) : (0xCF | TWO_POINTS);
		case 0x309: return (0x1EC8 | TWO_POINTS);
		case 0x30C: return (0x1CF | TWO_POINTS);
		case 0x30F: return (0x208 | TWO_POINTS);
		case 0x311: return (0x20A | TWO_POINTS);
		case 0x323: return (0x1ECA | TWO_POINTS);
		case 0x328: return (0x12E | TWO_POINTS);
		case 0x330: return (0x1E2C | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x4A:
		return b == 0x302 ? (0x134 | TWO_POINTS) : NO_MATCH;
	case 0x4B:
		switch (b) {
		case 0x301: return (0x1E30 | TWO_POINTS);
		case 0x30C: return (0x1E8 | TWO_POINTS);
		case 0x323: return (0x1E32 | TWO_POINTS);
		case 0x327: return (0x136 | TWO_POINTS);
		case 0x331: return (0x1E34 | TWO_POINTS);
		default: return (0x212A | ONE_POINT);
		}
	case 0x4C:
		switch (b) {
		case 0x301: return (0x139 | TWO_POINTS);
		case 0x30C: return (0x13D | TWO_POINTS);
		case 0x323:
			return c == 0x304 ? (0x1E38 | THREE_POINTS) : (0x1E36 | TWO_POINTS);
		case 0x327: return (0x13B | TWO_POINTS);
		case 0x32D: return (0x1E3C | TWO_POINTS);
		case 0x331: return (0x1E3A | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x4D:
		switch (b) {
		case 0x301: return (0x1E3E | TWO_POINTS);
		case 0x307: return (0x1E40 | TWO_POINTS);
		case 0x323: return (0x1E42 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x4E:
		switch (b) {
		case 0x300: return (0x1F8 | TWO_POINTS);
		case 0x301: return (0x143 | TWO_POINTS);
		case 0x303: return (0xD1 | TWO_POINTS);
		case 0x307: return (0x1E44 | TWO_POINTS);
		case 0x30C: return (0x147 | TWO_POINTS);
		case 0x323: return (0x1E46 | TWO_POINTS);
		case 0x327: return (0x145 | TWO_POINTS);
		case 0x32D: return (0x1E4A | TWO_POINTS);
		case 0x331: return (0x1E48 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x4F:
		switch (b) {
		case 0x300: return (0xD2 | TWO_POINTS);
		case 0x301: return (0xD3 | TWO_POINTS);
		case 0x302:
			switch (c) {
			case 0x300: return (0x1ED2 | THREE_POINTS);
			case 0x301: return (0x1ED0 | THREE_POINTS);
			case 0x303: return (0x1ED6 | THREE_POINTS);
			case 0x309: return (0x1ED4 | THREE_POINTS);
			default: return (0xD4 | TWO_POINTS);
			}
		case 0x303:
			switch (c) {
			case 0x301: return (0x1E4C | THREE_POINTS);
			case 0x304: return (0x22C | THREE_POINTS);
			case 0x308: return (0x1E4E | THREE_POINTS);
			default: return (0xD5 | TWO_POINTS);
			}
		case 0x304:
			return c == 0x300 ? (0x1E50 | THREE_POINTS)
				: c == 0x301 ? (0x1E52 | THREE_POINTS)
				: (0x14C | TWO_POINTS);
		case 0x306: return (0x14E | TWO_POINTS);
		case 0x307:
			return c == 0x304 ? (0x230 | THREE_POINTS) : (0x22E | TWO_POINTS);
		case 0x308:
			return c == 0x304 ? (0x22A | THREE_POINTS) : (0xD6 | TWO_POINTS);
		case 0x309: return (0x1ECE | TWO_POINTS);
		case 0x30B: return (0x150 | TWO_POINTS);
		case 0x30C: return (0x1D1 | TWO_POINTS);
		case 0x30F: return (0x20C | TWO_POINTS);
		case 0x311: return (0x20E | TWO_POINTS);
		case 0x31B:
			switch (c) {
			case 0x300: return (0x1EDC | THREE_POINTS);
			case 0x301: return (0x1EDA | THREE_POINTS);
			case 0x303: return (0x1EE0 | THREE_POINTS);
			case 0x309: return (0x1EDE | THREE_POINTS);
			case 0x323: return (0x1EE2 | THREE_POINTS);
			default: return (0x1A0 | TWO_POINTS);
			}
		case 0x323:
			return c == 0x302 ? (0x1ED8 | THREE_POINTS) : (0x1ECC | TWO_POINTS);
		case 0x328:
			return c == 0x304 ? (0x1EC | THREE_POINTS) : (0x1EA | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x50:
		return b == 0x301 ? (0x1E54 | TWO_POINTS)
			: b == 0x307 ? (0x1E56 | TWO_POINTS)
			: NO_MATCH;
	case 0x52:
		switch (b) {
		case 0x301: return (0x154 | TWO_POINTS);
		case 0x307: return (0x1E58 | TWO_POINTS);
		case 0x30C: return (0x158 | TWO_POINTS);
		case 0x30F: return (0x210 | TWO_POINTS);
		case 0x311: return (0x212 | TWO_POINTS);
		case 0x323:
			return c == 0x304 ? (0x1E5C | THREE_POINTS) : (0x1E5A | TWO_POINTS);
		case 0x327: return (0x156 | TWO_POINTS);
		case 0x331: return (0x1E5E | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x53:
		switch (b) {
		case 0x301:
			return c == 0x307 ? (0x1E64 | THREE_POINTS) : (0x15A | TWO_POINTS);
		case 0x302: return (0x15C | TWO_POINTS);
		case 0x307: return (0x1E60 | TWO_POINTS);
		case 0x30C:
			return c == 0x307 ? (0x1E66 | THREE_POINTS) : (0x160 | TWO_POINTS);
		case 0x323:
			return c == 0x307 ? (0x1E68 | THREE_POINTS) : (0x1E62 | TWO_POINTS);
		case 0x326: return (0x218 | TWO_POINTS);
		case 0x327: return (0x15E | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x54:
		switch (b) {
		case 0x307: return (0x1E6A | TWO_POINTS);
		case 0x30C: return (0x164 | TWO_POINTS);
		case 0x323: return (0x1E6C | TWO_POINTS);
		case 0x326: return (0x21A | TWO_POINTS);
		case 0x327: return (0x162 | TWO_POINTS);
		case 0x32D: return (0x1E70 | TWO_POINTS);
		case 0x331: return (0x1E6E | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x55:
		switch (b) {
		case 0x300: return (0xD9 | TWO_POINTS);
		case 0x301: return (0xDA | TWO_POINTS);
		case 0x302: return (0xDB | TWO_POINTS);
		case 0x303:
			return c == 0x301 ? (0x1E78 | THREE_POINTS) : (0x168 | TWO_POINTS);
		case 0x304:
			return c == 0x308 ? (0x1E7A | THREE_POINTS) : (0x16A | TWO_POINTS);
		case 0x306: return (0x16C | TWO_POINTS);
		case 0x308:
			switch (c) {
			case 0x300: return (0x1DB | THREE_POINTS);
			case 0x301: return (0x1D7 | THREE_POINTS);
			case 0x304: return (0x1D5 | THREE_POINTS);
			case 0x30C: return (0x1D9 | THREE_POINTS);
			default: return (0xDC | TWO_POINTS);
			}
		case 0x309: return (0x1EE6 | TWO_POINTS);
		case 0x30A: return (0x16E | TWO_POINTS);
		case 0x30B: return (0x170 | TWO_POINTS);
		case 0x30C: return (0x1D3 | TWO_POINTS);
		case 0x30F: return (0x214 | TWO_POINTS);
		case 0x311: return (0x216 | TWO_POINTS);
		case 0x31B:
			switch (c) {
			case 0x300: return (0x1EEA | THREE_POINTS);
			case 0x301: return (0x1EE8 | THREE_POINTS);
			case 0x303: return (0x1EEE | THREE_POINTS);
			case 0x309: return (0x1EEC | THREE_POINTS);
			case 0x323: return (0x1EF0 | THREE_POINTS);
			default: return (0x1AF | TWO_POINTS);
			}
		case 0x323: return (0x1EE4 | TWO_POINTS);
		case 0x324: return (0x1E72 | TWO_POINTS);
		case 0x328: return (0x172 | TWO_POINTS);
		case 0x32D: return (0x1E76 | TWO_POINTS);
		case 0x330: return (0x1E74 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x56:
		return b == 0x303 ? (0x1E7C | TWO_POINTS)
			: b == 0x323 ? (0x1E7E | TWO_POINTS)
			: NO_MATCH;
	case 0x57:
		switch (b) {
		case 0x300: return (0x1E80 | TWO_POINTS);
		case 0x301: return (0x1E82 | TWO_POINTS);
		case 0x302: return (0x174 | TWO_POINTS);
		case 0x307: return (0x1E86 | TWO_POINTS);
		case 0x308: return (0x1E84 | TWO_POINTS);
		case 0x323: return (0x1E88 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x58:
		return b == 0x307 ? (0x1E8A | TWO_POINTS)
			: b == 0x308 ? (0x1E8C | TWO_POINTS)
			: NO_MATCH;
	case 0x59:
		switch (b) {
		case 0x300: return (0x1EF2 | TWO_POINTS);
		case 0x301: return (0xDD | TWO_POINTS);
		case 0x302: return (0x176 | TWO_POINTS);
		case 0x303: return (0x1EF8 | TWO_POINTS);
		case 0x304: return (0x232 | TWO_POINTS);
		case 0x307: return (0x1E8E | TWO_POINTS);
		case 0x308: return (0x178 | TWO_POINTS);
		case 0x309: return (0x1EF6 | TWO_POINTS);
		case 0x323: return (0x1EF4 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x5A:
		switch (b) {
		case 0x301: return (0x179 | TWO_POINTS);
		case 0x302: return (0x1E90 | TWO_POINTS);
		case 0x307: return (0x17B | TWO_POINTS);
		case 0x30C: return (0x17D | TWO_POINTS);
		case 0x323: return (0x1E92 | TWO_POINTS);
		case 0x331: return (0x1E94 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x61:
		switch (b) {
		case 0x300: return (0xE0 | TWO_POINTS);
		case 0x301: return (0xE1 | TWO_POINTS);
		case 0x302:
			switch (c) {
			case 0x300: return (0x1EA7 | THREE_POINTS);
			case 0x301: return (0x1EA5 | THREE_POINTS);
			case 0x303: return (0x1EAB | THREE_POINTS);
			case 0x309: return (0x1EA9 | THREE_POINTS);
			default: return (0xE2 | TWO_POINTS);
			}
		case 0x303: return (0xE3 | TWO_POINTS);
		case 0x304: return (0x101 | TWO_POINTS);
		case 0x306:
			switch (c) {
			case 0x300: return (0x1EB1 | THREE_POINTS);
			case 0x301: return (0x1EAF | THREE_POINTS);
			case 0x303: return (0x1EB5 | THREE_POINTS);
			case 0x309: return (0x1EB3 | THREE_POINTS);
			default: return (0x103 | TWO_POINTS);
			}
		case 0x307:
			return c == 0x304 ? (0x1E1 | THREE_POINTS) : (0x227 | TWO_POINTS);
		case 0x308:
			return c == 0x304 ? (0x1DF | THREE_POINTS) : (0xE4 | TWO_POINTS);
		case 0x309: return (0x1EA3 | TWO_POINTS);
		case 0x30A:
			return c == 0x301 ? (0x1FB | THREE_POINTS) : (0xE5 | TWO_POINTS);
		case 0x30C: return (0x1CE | TWO_POINTS);
		case 0x30F: return (0x201 | TWO_POINTS);
		case 0x311: return (0x203 | TWO_POINTS);
		case 0x323:
			return c == 0x302 ? (0x1EAD | THREE_POINTS)
				: c == 0x306 ? (0x1EB7 | THREE_POINTS)
				: (0x1EA1 | TWO_POINTS);
		case 0x325: return (0x1E01 | TWO_POINTS);
		case 0x328: return (0x105 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x62:
		switch (b) {
		case 0x307: return (0x1E03 | TWO_POINTS);
		case 0x323: return (0x1E05 | TWO_POINTS);
		case 0x331: return (0x1E07 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x63:
		switch (b) {
		case 0x301: return (0x107 | TWO_POINTS);
		case 0x302: return (0x109 | TWO_POINTS);
		case 0x307: return (0x10B | TWO_POINTS);
		case 0x30C: return (0x10D | TWO_POINTS);
		case 0x327:
			return c == 0x301 ? (0x1E09 | THREE_POINTS) : (0xE7 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x64:
		switch (b) {
		case 0x307: return (0x1E0B | TWO_POINTS);
		case 0x30C: return (0x10F | TWO_POINTS);
		case 0x323: return (0x1E0D | TWO_POINTS);
		case 0x327: return (0x1E11 | TWO_POINTS);
		case 0x32D: return (0x1E13 | TWO_POINTS);
		case 0x331: return (0x1E0F | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x65:
		switch (b) {
		case 0x300: return (0xE8 | TWO_POINTS);
		case 0x301: return (0xE9 | TWO_POINTS);
		case 0x302:
			switch (c) {
			case 0x300: return (0x1EC1 | THREE_POINTS);
			case 0x301: return (0x1EBF | THREE_POINTS);
			case 0x303: return (0x1EC5 | THREE_POINTS);
			case 0x309: return (0x1EC3 | THREE_POINTS);
			default: return (0xEA | TWO_POINTS);
			}
		case 0x303: return (0x1EBD | TWO_POINTS);
		case 0x304:
			return c == 0x300 ? (0x1E15 | THREE_POINTS)
				: c == 0x301 ? (0x1E17 | THREE_POINTS)
				: (0x113 | TWO_POINTS);
		case 0x306: return (0x115 | TWO_POINTS);
		case 0x307: return (0x117 | TWO_POINTS);
		case 0x308: return (0xEB | TWO_POINTS);
		case 0x309: return (0x1EBB | TWO_POINTS);
		case 0x30C: return (0x11B | TWO_POINTS);
		case 0x30F: return (0x205 | TWO_POINTS);
		case 0x311: return (0x207 | TWO_POINTS);
		case 0x323:
			return c == 0x302 ? (0x1EC7 | THREE_POINTS) : (0x1EB9 | TWO_POINTS);
		case 0x327:
			return c == 0x306 ? (0x1E1D | THREE_POINTS) : (0x229 | TWO_POINTS);
		case 0x328: return (0x119 | TWO_POINTS);
		case 0x32D: return (0x1E19 | TWO_POINTS);
		case 0x330: return (0x1E1B | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x66:
		return b == 0x307 ? (0x1E1F | TWO_POINTS) : NO_MATCH;
	case 0x67:
		switch (b) {
		case 0x301: return (0x1F5 | TWO_POINTS);
		case 0x302: return (0x11D | TWO_POINTS);
		case 0x304: return (0x1E21 | TWO_POINTS);
		case 0x306: return (0x11F | TWO_POINTS);
		case 0x307: return (0x121 | TWO_POINTS);
		case 0x30C: return (0x1E7 | TWO_POINTS);
		case 0x327: return (0x123 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x68:
		switch (b) {
		case 0x302: return (0x125 | TWO_POINTS);
		case 0x307: return (0x1E23 | TWO_POINTS);
		case 0x308: return (0x1E27 | TWO_POINTS);
		case 0x30C: return (0x21F | TWO_POINTS);
		case 0x323: return (0x1E25 | TWO_POINTS);
		case 0x327: return (0x1E29 | TWO_POINTS);
		case 0x32E: return (0x1E2B | TWO_POINTS);
		case 0x331: return (0x1E96 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x69:
		switch (b) {
		case 0x300: return (0xEC | TWO_POINTS);
		case 0x301: return (0xED | TWO_POINTS);
		case 0x302: return (0xEE | TWO_POINTS);
		case 0x303: return (0x129 | TWO_POINTS);
		case 0x304: return (0x12B | TWO_POINTS);
		case 0x306: return (0x12D | TWO_POINTS);
		case 0x308:
			return c == 0x301 ? (0x1E2F | THREE_POINTS) : (0xEF | TWO_POINTS);
		case 0x309: return (0x1EC9 | TWO_POINTS);
		case 0x30C: return (0x1D0 | TWO_POINTS);
		case 0x30F: return (0x209 | TWO_POINTS);
		case 0x311: return (0x20B | TWO_POINTS);
		case 0x323: return (0x1ECB | TWO_POINTS);
		case 0x328: return (0x12F | TWO_POINTS);
		case 0x330: return (0x1E2D | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x6A:
		return b == 0x302 ? (0x135 | TWO_POINTS)
			: b == 0x30C ? (0x1F0 | TWO_POINTS)
			: NO_MATCH;
	case 0x6B:
		switch (b) {
		case 0x301: return (0x1E31 | TWO_POINTS);
		case 0x30C: return (0x1E9 | TWO_POINTS);
		case 0x323: return (0x1E33 | TWO_POINTS);
		case 0x327: return (0x137 | TWO_POINTS);
		case 0x331: return (0x1E35 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x6C:
		switch (b) {
		case 0x301: return (0x13A | TWO_POINTS);
		case 0x30C: return (0x13E | TWO_POINTS);
		case 0x323:
			return c == 0x304 ? (0x1E39 | THREE_POINTS) : (0x1E37 | TWO_POINTS);
		case 0x327: return (0x13C | TWO_POINTS);
		case 0x32D: return (0x1E3D | TWO_POINTS);
		case 0x331: return (0x1E3B | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x6D:
		switch (b) {
		case 0x301: return (0x1E3F | TWO_POINTS);
		case 0x307: return (0x1E41 | TWO_POINTS);
		case 0x323: return (0x1E43 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x6E:
		switch (b) {
		case 0x300: return (0x1F9 | TWO_POINTS);
		case 0x301: return (0x144 | TWO_POINTS);
		case 0x303: return (0xF1 | TWO_POINTS);
		case 0x307: return (0x1E45 | TWO_POINTS);
		case 0x30C: return (0x148 | TWO_POINTS);
		case 0x323: return (0x1E47 | TWO_POINTS);
		case 0x327: return (0x146 | TWO_POINTS);
		case 0x32D: return (0x1E4B | TWO_POINTS);
		case 0x331: return (0x1E49 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x6F:
		switch (b) {
		case 0x300: return (0xF2 | TWO_POINTS);
		case 0x301: return (0xF3 | TWO_POINTS);
		case 0x302:
			switch (c) {
			case 0x300: return (0x1ED3 | THREE_POINTS);
			case 0x301: return (0x1ED1 | THREE_POINTS);
			case 0x303: return (0x1ED7 | THREE_POINTS);
			case 0x309: return (0x1ED5 | THREE_POINTS);
			default: return (0xF4 | TWO_POINTS);
			}
		case 0x303:
			switch (c) {
			case 0x301: return (0x1E4D | THREE_POINTS);
			case 0x304: return (0x22D | THREE_POINTS);
			case 0x308: return (0x1E4F | THREE_POINTS);
			default: return (0xF5 | TWO_POINTS);
			}
		case 0x304:
			return c == 0x300 ? (0x1E51 | THREE_POINTS)
				: c == 0x301 ? (0x1E53 | THREE_POINTS)
				: (0x14D | TWO_POINTS);
		case 0x306: return (0x14F | TWO_POINTS);
		case 0x307:
			return c == 0x304 ? (0x231 | THREE_POINTS) : (0x22F | TWO_POINTS);
		case 0x308:
			return c == 0x304 ? (0x22B | THREE_POINTS) : (0xF6 | TWO_POINTS);
		case 0x309: return (0x1ECF | TWO_POINTS);
		case 0x30B: return (0x151 | TWO_POINTS);
		case 0x30C: return (0x1D2 | TWO_POINTS);
		case 0x30F: return (0x20D | TWO_POINTS);
		case 0x311: return (0x20F | TWO_POINTS);
		case 0x31B:
			switch (c) {
			case 0x300: return (0x1EDD | THREE_POINTS);
			case 0x301: return (0x1EDB | THREE_POINTS);
			case 0x303: return (0x1EE1 | THREE_POINTS);
			case 0x309: return (0x1EDF | THREE_POINTS);
			case 0x323: return (0x1EE3 | THREE_POINTS);
			default: return (0x1A1 | TWO_POINTS);
			}
		case 0x323:
			return c == 0x302 ? (0x1ED9 | THREE_POINTS) : (0x1ECD | TWO_POINTS);
		case 0x328:
			return c == 0x304 ? (0x1ED | THREE_POINTS) : (0x1EB | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x70:
		return b == 0x301 ? (0x1E55 | TWO_POINTS)
			: b == 0x307 ? (0x1E57 | TWO_POINTS)
			: NO_MATCH;
	case 0x72:
		switch (b) {
		case 0x301: return (0x155 | TWO_POINTS);
		case 0x307: return (0x1E59 | TWO_POINTS);
		case 0x30C: return (0x159 | TWO_POINTS);
		case 0x30F: return (0x211 | TWO_POINTS);
		case 0x311: return (0x213 | TWO_POINTS);
		case 0x323:
			return c == 0x304 ? (0x1E5D | THREE_POINTS) : (0x1E5B | TWO_POINTS);
		case 0x327: return (0x157 | TWO_POINTS);
		case 0x331: return (0x1E5F | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x73:
		switch (b) {
		case 0x301:
			return c == 0x307 ? (0x1E65 | THREE_POINTS) : (0x15B | TWO_POINTS);
		case 0x302: return (0x15D | TWO_POINTS);
		case 0x307: return (0x1E61 | TWO_POINTS);
		case 0x30C:
			return c == 0x307 ? (0x1E67 | THREE_POINTS) : (0x161 | TWO_POINTS);
		case 0x323:
			return c == 0x307 ? (0x1E69 | THREE_POINTS) : (0x1E63 | TWO_POINTS);
		case 0x326: return (0x219 | TWO_POINTS);
		case 0x327: return (0x15F | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x74:
		switch (b) {
		case 0x307: return (0x1E6B | TWO_POINTS);
		case 0x308: return (0x1E97 | TWO_POINTS);
		case 0x30C: return (0x165 | TWO_POINTS);
		case 0x323: return (0x1E6D | TWO_POINTS);
		case 0x326: return (0x21B | TWO_POINTS);
		case 0x327: return (0x163 | TWO_POINTS);
		case 0x32D: return (0x1E71 | TWO_POINTS);
		case 0x331: return (0x1E6F | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x75:
		switch (b) {
		case 0x300: return (0xF9 | TWO_POINTS);
		case 0x301: return (0xFA | TWO_POINTS);
		case 0x302: return (0xFB | TWO_POINTS);
		case 0x303:
			return c == 0x301 ? (0x1E79 | THREE_POINTS) : (0x169 | TWO_POINTS);
		case 0x304:
			return c == 0x308 ? (0x1E7B | THREE_POINTS) : (0x16B | TWO_POINTS);
		case 0x306: return (0x16D | TWO_POINTS);
		case 0x308:
			switch (c) {
			case 0x300: return (0x1DC | THREE_POINTS);
			case 0x301: return (0x1D8 | THREE_POINTS);
			case 0x304: return (0x1D6 | THREE_POINTS);
			case 0x30C: return (0x1DA | THREE_POINTS);
			default: return (0xFC | TWO_POINTS);
			}
		case 0x309: return (0x1EE7 | TWO_POINTS);
		case 0x30A: return (0x16F | TWO_POINTS);
		case 0x30B: return (0x171 | TWO_POINTS);
		case 0x30C: return (0x1D4 | TWO_POINTS);
		case 0x30F: return (0x215 | TWO_POINTS);
		case 0x311: return (0x217 | TWO_POINTS);
		case 0x31B:
			switch (c) {
			case 0x300: return (0x1EEB | THREE_POINTS);
			case 0x301: return (0x1EE9 | THREE_POINTS);
			case 0x303: return (0x1EEF | THREE_POINTS);
			case 0x309: return (0x1EED | THREE_POINTS);
			case 0x323: return (0x1EF1 | THREE_POINTS);
			default: return (0x1B0 | TWO_POINTS);
			}
		case 0x323: return (0x1EE5 | TWO_POINTS);
		case 0x324: return (0x1E73 | TWO_POINTS);
		case 0x328: return (0x173 | TWO_POINTS);
		case 0x32D: return (0x1E77 | TWO_POINTS);
		case 0x330: return (0x1E75 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x76:
		return b == 0x303 ? (0x1E7D | TWO_POINTS)
			: b == 0x323 ? (0x1E7F | TWO_POINTS)
			: NO_MATCH;
	case 0x77:
		switch (b) {
		case 0x300: return (0x1E81 | TWO_POINTS);
		case 0x301: return (0x1E83 | TWO_POINTS);
		case 0x302: return (0x175 | TWO_POINTS);
		case 0x307: return (0x1E87 | TWO_POINTS);
		case 0x308: return (0x1E85 | TWO_POINTS);
		case 0x30A: return (0x1E98 | TWO_POINTS);
		case 0x323: return (0x1E89 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x78:
		return b == 0x307 ? (0x1E8B | TWO_POINTS)
			: b == 0x308 ? (0x1E8D | TWO_POINTS)
			: NO_MATCH;
	case 0x79:
		switch (b) {
		case 0x300: return (0x1EF3 | TWO_POINTS);
		case 0x301: return (0xFD | TWO_POINTS);
		case 0x302: return (0x177 | TWO_POINTS);
		case 0x303: return (0x1EF9 | TWO_POINTS);
		case 0x304: return (0x233 | TWO_POINTS);
		case 0x307: return (0x1E8F | TWO_POINTS);
		case 0x308: return (0xFF | TWO_POINTS);
		case 0x309: return (0x1EF7 | TWO_POINTS);
		case 0x30A: return (0x1E99 | TWO_POINTS);
		case 0x323: return (0x1EF5 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x7A:
		switch (b) {
		case 0x301: return (0x17A | TWO_POINTS);
		case 0x302: return (0x1E91 | TWO_POINTS);
		case 0x307: return (0x17C | TWO_POINTS);
		case 0x30C: return (0x17E | TWO_POINTS);
		case 0x323: return (0x1E93 | TWO_POINTS);
		case 0x331: return (0x1E95 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0xA8:
		switch (b) {
		case 0x300: return (0x1FED | TWO_POINTS);
		case 0x301: return (0x1FEE | TWO_POINTS);
		case 0x342: return (0x1FC1 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0xC6:
		return b == 0x304 ? (0x1E2 | TWO_POINTS)
			: b == 0x301 ? (0x1FC | TWO_POINTS)
			: NO_MATCH;
	case 0xD8:
		return b == 0x301 ? (0x1FE | TWO_POINTS) : NO_MATCH;
	case 0xE6:
		return b == 0x304 ? (0x1E3 | TWO_POINTS)
			: b == 0x301 ? (0x1FD | TWO_POINTS)
			: NO_MATCH;
	case 0xF8:
		return b == 0x301 ? (0x1FF | TWO_POINTS) : NO_MATCH;
	case 0x17F:
		return b == 0x307 ? (0x1E9B | TWO_POINTS) : NO_MATCH;
	case 0x1B7:
		return b == 0x30C ? (0x1EE | TWO_POINTS) : NO_MATCH;
	case 0x292:
		return b == 0x30C ? (0x1EF | TWO_POINTS) : NO_MATCH;
	case 0x308:
		return b == 0x301 ? (0x344 | TWO_POINTS) : NO_MATCH;
	case 0x391:
		switch (b) {
		case 0x300: return (0x1FBA | TWO_POINTS);
		case 0x301: return (0x1FBB | TWO_POINTS);
		case 0x304: return (0x1FB9 | TWO_POINTS);
		case 0x306: return (0x1FB8 | TWO_POINTS);
		case 0x313:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1F8A | FOUR_POINTS) : (0x1F0A | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1F8C | FOUR_POINTS) : (0x1F0C | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1F8E | FOUR_POINTS) : (0x1F0E | THREE_POINTS);
			case 0x345: return (0x1F88 | THREE_POINTS);
			default: return (0x1F08 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1F8B | FOUR_POINTS) : (0x1F0B | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1F8D | FOUR_POINTS) : (0x1F0D | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1F8F | FOUR_POINTS) : (0x1F0F | THREE_POINTS);
			case 0x345: return (0x1F89 | THREE_POINTS);
			default: return (0x1F09 | TWO_POINTS);
			}
		case 0x345: return (0x1FBC | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x395:
		switch (b) {
		case 0x300: return (0x1FC8 | TWO_POINTS);
		case 0x301: return (0x1FC9 | TWO_POINTS);
		case 0x313:
			return c == 0x300 ? (0x1F1A | THREE_POINTS)
				: c == 0x301 ? (0x1F1C | THREE_POINTS)
				: (0x1F18 | TWO_POINTS);
		case 0x314:
			return c == 0x300 ? (0x1F1B | THREE_POINTS)
				: c == 0x301 ? (0x1F1D | THREE_POINTS)
				: (0x1F19 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x397:
		switch (b) {
		case 0x300: return (0x1FCA | TWO_POINTS);
		case 0x301: return (0x1FCB | TWO_POINTS);
		case 0x313:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1F9A | FOUR_POINTS) : (0x1F2A | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1F9C | FOUR_POINTS) : (0x1F2C | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1F9E | FOUR_POINTS) : (0x1F2E | THREE_POINTS);
			case 0x345: return (0x1F98 | THREE_POINTS);
			default: return (0x1F28 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1F9B | FOUR_POINTS) : (0x1F2B | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1F9D | FOUR_POINTS) : (0x1F2D | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1F9F | FOUR_POINTS) : (0x1F2F | THREE_POINTS);
			case 0x345: return (0x1F99 | THREE_POINTS);
			default: return (0x1F29 | TWO_POINTS);
			}
		case 0x345: return (0x1FCC | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x399:
		switch (b) {
		case 0x300: return (0x1FDA | TWO_POINTS);
		case 0x301: return (0x1FDB | TWO_POINTS);
		case 0x304: return (0x1FD9 | TWO_POINTS);
		case 0x306: return (0x1FD8 | TWO_POINTS);
		case 0x308: return (0x3AA | TWO_POINTS);
		case 0x313:
			switch (c) {
			case 0x300: return (0x1F3A | THREE_POINTS);
			case 0x301: return (0x1F3C | THREE_POINTS);
			case 0x342: return (0x1F3E | THREE_POINTS);
			default: return (0x1F38 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300: return (0x1F3B | THREE_POINTS);
			case 0x301: return (0x1F3D | THREE_POINTS);
			case 0x342: return (0x1F3F | THREE_POINTS);
			default: return (0x1F39 | TWO_POINTS);
			}
		default: return NO_MATCH;
		}
	case 0x39F:
		switch (b) {
		case 0x300: return (0x1FF8 | TWO_POINTS);
		case 0x301: return (0x1FF9 | TWO_POINTS);
		case 0x313:
			return c == 0x300 ? (0x1F4A | THREE_POINTS)
				: c == 0x301 ? (0x1F4C | THREE_POINTS)
				: (0x1F48 | TWO_POINTS);
		case 0x314:
			return c == 0x300 ? (0x1F4B | THREE_POINTS)
				: c == 0x301 ? (0x1F4D | THREE_POINTS)
				: (0x1F49 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x3A1:
		return b == 0x314 ? (0x1FEC | TWO_POINTS) : NO_MATCH;
	case 0x3A5:
		switch (b) {
		case 0x300: return (0x1FEA | TWO_POINTS);
		case 0x301: return (0x1FEB | TWO_POINTS);
		case 0x304: return (0x1FE9 | TWO_POINTS);
		case 0x306: return (0x1FE8 | TWO_POINTS);
		case 0x308: return (0x3AB | TWO_POINTS);
		case 0x314:
			switch (c) {
			case 0x300: return (0x1F5B | THREE_POINTS);
			case 0x301: return (0x1F5D | THREE_POINTS);
			case 0x342: return (0x1F5F | THREE_POINTS);
			default: return (0x1F59 | TWO_POINTS);
			}
		default: return NO_MATCH;
		}
	case 0x3A9:
		switch (b) {
		case 0x300: return (0x1FFA | TWO_POINTS);
		case 0x301: return (0x1FFB | TWO_POINTS);
		case 0x313:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1FAA | FOUR_POINTS) : (0x1F6A | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1FAC | FOUR_POINTS) : (0x1F6C | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1FAE | FOUR_POINTS) : (0x1F6E | THREE_POINTS);
			case 0x345: return (0x1FA8 | THREE_POINTS);
			default: return (0x1F68 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1FAB | FOUR_POINTS) : (0x1F6B | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1FAD | FOUR_POINTS) : (0x1F6D | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1FAF | FOUR_POINTS) : (0x1F6F | THREE_POINTS);
			case 0x345: return (0x1FA9 | THREE_POINTS);
			default: return (0x1F69 | TWO_POINTS);
			}
		case 0x345: return (0x1FFC | TWO_POINTS);
		default: return (0x2126 | ONE_POINT);
		}
	case 0x3B1:
		switch (b) {
		case 0x300:
			return c == 0x345 ? (0x1FB2 | THREE_POINTS) : (0x1F70 | TWO_POINTS);
		case 0x301:
			return c == 0x345 ? (0x1FB4 | THREE_POINTS) : (0x1F71 | TWO_POINTS);
		case 0x304: return (0x1FB1 | TWO_POINTS);
		case 0x306: return (0x1FB0 | TWO_POINTS);
		case 0x313:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1F82 | FOUR_POINTS) : (0x1F02 | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1F84 | FOUR_POINTS) : (0x1F04 | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1F86 | FOUR_POINTS) : (0x1F06 | THREE_POINTS);
			case 0x345: return (0x1F80 | THREE_POINTS);
			default: return (0x1F00 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1F83 | FOUR_POINTS) : (0x1F03 | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1F85 | FOUR_POINTS) : (0x1F05 | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1F87 | FOUR_POINTS) : (0x1F07 | THREE_POINTS);
			case 0x345: return (0x1F81 | THREE_POINTS);
			default: return (0x1F01 | TWO_POINTS);
			}
		case 0x342:
			return c == 0x345 ? (0x1FB7 | THREE_POINTS) : (0x1FB6 | TWO_POINTS);
		case 0x345: return (0x1FB3 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x3B5:
		switch (b) {
		case 0x300: return (0x1F72 | TWO_POINTS);
		case 0x301: return (0x1F73 | TWO_POINTS);
		case 0x313:
			return c == 0x300 ? (0x1F12 | THREE_POINTS)
				: c == 0x301 ? (0x1F14 | THREE_POINTS)
				: (0x1F10 | TWO_POINTS);
		case 0x314:
			return c == 0x300 ? (0x1F13 | THREE_POINTS)
				: c == 0x301 ? (0x1F15 | THREE_POINTS)
				: (0x1F11 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x3B7:
		switch (b) {
		case 0x300:
			return c == 0x345 ? (0x1FC2 | THREE_POINTS) : (0x1F74 | TWO_POINTS);
		case 0x301:
			return c == 0x345 ? (0x1FC4 | THREE_POINTS) : (0x1F75 | TWO_POINTS);
		case 0x313:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1F92 | FOUR_POINTS) : (0x1F22 | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1F94 | FOUR_POINTS) : (0x1F24 | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1F96 | FOUR_POINTS) : (0x1F26 | THREE_POINTS);
			case 0x345: return (0x1F90 | THREE_POINTS);
			default: return (0x1F20 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1F93 | FOUR_POINTS) : (0x1F23 | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1F95 | FOUR_POINTS) : (0x1F25 | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1F97 | FOUR_POINTS) : (0x1F27 | THREE_POINTS);
			case 0x345: return (0x1F91 | THREE_POINTS);
			default: return (0x1F21 | TWO_POINTS);
			}
		case 0x342:
			return c == 0x345 ? (0x1FC7 | THREE_POINTS) : (0x1FC6 | TWO_POINTS);
		case 0x345: return (0x1FC3 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x3B9:
		switch (b) {
		case 0x300: return (0x1F76 | TWO_POINTS);
		case 0x301: return (0x1F77 | TWO_POINTS);
		case 0x304: return (0x1FD1 | TWO_POINTS);
		case 0x306: return (0x1FD0 | TWO_POINTS);
		case 0x308:
			switch (c) {
			case 0x300: return (0x1FD2 | THREE_POINTS);
			case 0x301: return (0x1FD3 | THREE_POINTS);
			case 0x342: return (0x1FD7 | THREE_POINTS);
			default: return (0x3CA | TWO_POINTS);
			}
		case 0x313:
			switch (c) {
			case 0x300: return (0x1F32 | THREE_POINTS);
			case 0x301: return (0x1F34 | THREE_POINTS);
			case 0x342: return (0x1F36 | THREE_POINTS);
			default: return (0x1F30 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300: return (0x1F33 | THREE_POINTS);
			case 0x301: return (0x1F35 | THREE_POINTS);
			case 0x342: return (0x1F37 | THREE_POINTS);
			default: return (0x1F31 | TWO_POINTS);
			}
		case 0x342: return (0x1FD6 | TWO_POINTS);
		default: return (0x1FBE | ONE_POINT);
		}
	case 0x3BF:
		switch (b) {
		case 0x300: return (0x1F78 | TWO_POINTS);
		case 0x301: return (0x1F79 | TWO_POINTS);
		case 0x313:
			return c == 0x300 ? (0x1F42 | THREE_POINTS)
				: c == 0x301 ? (0x1F44 | THREE_POINTS)
				: (0x1F40 | TWO_POINTS);
		case 0x314:
			return c == 0x300 ? (0x1F43 | THREE_POINTS)
				: c == 0x301 ? (0x1F45 | THREE_POINTS)
				: (0x1F41 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x3C1:
		return b == 0x313 ? (0x1FE4 | TWO_POINTS)
			: b == 0x314 ? (0x1FE5 | TWO_POINTS)
			: NO_MATCH;
	case 0x3C5:
		switch (b) {
		case 0x300: return (0x1F7A | TWO_POINTS);
		case 0x301: return (0x1F7B | TWO_POINTS);
		case 0x304: return (0x1FE1 | TWO_POINTS);
		case 0x306: return (0x1FE0 | TWO_POINTS);
		case 0x308:
			switch (c) {
			case 0x300: return (0x1FE2 | THREE_POINTS);
			case 0x301: return (0x1FE3 | THREE_POINTS);
			case 0x342: return (0x1FE7 | THREE_POINTS);
			default: return (0x3CB | TWO_POINTS);
			}
		case 0x313:
			switch (c) {
			case 0x300: return (0x1F52 | THREE_POINTS);
			case 0x301: return (0x1F54 | THREE_POINTS);
			case 0x342: return (0x1F56 | THREE_POINTS);
			default: return (0x1F50 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300: return (0x1F53 | THREE_POINTS);
			case 0x301: return (0x1F55 | THREE_POINTS);
			case 0x342: return (0x1F57 | THREE_POINTS);
			default: return (0x1F51 | TWO_POINTS);
			}
		case 0x342: return (0x1FE6 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x3C9:
		switch (b) {
		case 0x300:
			return c == 0x345 ? (0x1FF2 | THREE_POINTS) : (0x1F7C | TWO_POINTS);
		case 0x301:
			return c == 0x345 ? (0x1FF4 | THREE_POINTS) : (0x1F7D | TWO_POINTS);
		case 0x313:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1FA2 | FOUR_POINTS) : (0x1F62 | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1FA4 | FOUR_POINTS) : (0x1F64 | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1FA6 | FOUR_POINTS) : (0x1F66 | THREE_POINTS);
			case 0x345: return (0x1FA0 | THREE_POINTS);
			default: return (0x1F60 | TWO_POINTS);
			}
		case 0x314:
			switch (c) {
			case 0x300:
				return d == 0x345 ? (0x1FA3 | FOUR_POINTS) : (0x1F63 | THREE_POINTS);
			case 0x301:
				return d == 0x345 ? (0x1FA5 | FOUR_POINTS) : (0x1F65 | THREE_POINTS);
			case 0x342:
				return d == 0x345 ? (0x1FA7 | FOUR_POINTS) : (0x1F67 | THREE_POINTS);
			case 0x345: return (0x1FA1 | THREE_POINTS);
			default: return (0x1F61 | TWO_POINTS);
			}
		case 0x342:
			return c == 0x345 ? (0x1FF7 | THREE_POINTS) : (0x1FF6 | TWO_POINTS);
		case 0x345: return (0x1FF3 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x3D2:
		return b == 0x301 ? (0x3D3 | TWO_POINTS)
			: b == 0x308 ? (0x3D4 | TWO_POINTS)
			: NO_MATCH;
	case 0x406:
		return b == 0x308 ? (0x407 | TWO_POINTS) : NO_MATCH;
	case 0x410:
		return b == 0x306 ? (0x4D0 | TWO_POINTS)
			: b == 0x308 ? (0x4D2 | TWO_POINTS)
			: NO_MATCH;
	case 0x413:
		return b == 0x301 ? (0x403 | TWO_POINTS) : NO_MATCH;
	case 0x415:
		switch (b) {
		case 0x300: return (0x400 | TWO_POINTS);
		case 0x306: return (0x4D6 | TWO_POINTS);
		case 0x308: return (0x401 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x416:
		return b == 0x306 ? (0x4C1 | TWO_POINTS)
			: b == 0x308 ? (0x4DC | TWO_POINTS)
			: NO_MATCH;
	case 0x417:
		return b == 0x308 ? (0x4DE | TWO_POINTS) : NO_MATCH;
	case 0x418:
		switch (b) {
		case 0x300: return (0x40D | TWO_POINTS);
		case 0x304: return (0x4E2 | TWO_POINTS);
		case 0x306: return (0x419 | TWO_POINTS);
		case 0x308: return (0x4E4 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x41A:
		return b == 0x301 ? (0x40C | TWO_POINTS) : NO_MATCH;
	case 0x41E:
		return b == 0x308 ? (0x4E6 | TWO_POINTS) : NO_MATCH;
	case 0x423:
		switch (b) {
		case 0x304: return (0x4EE | TWO_POINTS);
		case 0x306: return (0x40E | TWO_POINTS);
		case 0x308: return (0x4F0 | TWO_POINTS);
		case 0x30B: return (0x4F2 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x427:
		return b == 0x308 ? (0x4F4 | TWO_POINTS) : NO_MATCH;
	case 0x42B:
		return b == 0x308 ? (0x4F8 | TWO_POINTS) : NO_MATCH;
	case 0x42D:
		return b == 0x308 ? (0x4EC | TWO_POINTS) : NO_MATCH;
	case 0x430:
		return b == 0x306 ? (0x4D1 | TWO_POINTS)
			: b == 0x308 ? (0x4D3 | TWO_POINTS)
			: NO_MATCH;
	case 0x433:
		return b == 0x301 ? (0x453 | TWO_POINTS) : NO_MATCH;
	case 0x435:
		switch (b) {
		case 0x300: return (0x450 | TWO_POINTS);
		case 0x306: return (0x4D7 | TWO_POINTS);
		case 0x308: return (0x451 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x436:
		return b == 0x306 ? (0x4C2 | TWO_POINTS)
			: b == 0x308 ? (0x4DD | TWO_POINTS)
			: NO_MATCH;
	case 0x437:
		return b == 0x308 ? (0x4DF | TWO_POINTS) : NO_MATCH;
	case 0x438:
		switch (b) {
		case 0x300: return (0x45D | TWO_POINTS);
		case 0x304: return (0x4E3 | TWO_POINTS);
		case 0x306: return (0x439 | TWO_POINTS);
		case 0x308: return (0x4E5 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x43A:
		return b == 0x301 ? (0x45C | TWO_POINTS) : NO_MATCH;
	case 0x43E:
		return b == 0x308 ? (0x4E7 | TWO_POINTS) : NO_MATCH;
	case 0x443:
		switch (b) {
		case 0x304: return (0x4EF | TWO_POINTS);
		case 0x306: return (0x45E | TWO_POINTS);
		case 0x308: return (0x4F1 | TWO_POINTS);
		case 0x30B: return (0x4F3 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x447:
		return b == 0x308 ? (0x4F5 | TWO_POINTS) : NO_MATCH;
	case 0x44B:
		return b == 0x308 ? (0x4F9 | TWO_POINTS) : NO_MATCH;
	case 0x44D:
		return b == 0x308 ? (0x4ED | TWO_POINTS) : NO_MATCH;
	case 0x456:
		return b == 0x308 ? (0x457 | TWO_POINTS) : NO_MATCH;
	case 0x474:
		return b == 0x30F ? (0x476 | TWO_POINTS) : NO_MATCH;
	case 0x475:
		return b == 0x30F ? (0x477 | TWO_POINTS) : NO_MATCH;
	case 0x4D8:
		return b == 0x308 ? (0x4DA | TWO_POINTS) : NO_MATCH;
	case 0x4D9:
		return b == 0x308 ? (0x4DB | TWO_POINTS) : NO_MATCH;
	case 0x4E8:
		return b == 0x308 ? (0x4EA | TWO_POINTS) : NO_MATCH;
	case 0x4E9:
		return b == 0x308 ? (0x4EB | TWO_POINTS) : NO_MATCH;
	case 0x5D0:
		switch (b) {
		case 0x5B7: return (0xFB2E | TWO_POINTS);
		case 0x5B8: return (0xFB2F | TWO_POINTS);
		case 0x5BC: return (0xFB30 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x5D1:
		return b == 0x5BC ? (0xFB31 | TWO_POINTS)
			: b == 0x5BF ? (0xFB4C | TWO_POINTS)
			: NO_MATCH;
	case 0x5D2:
		return b == 0x5BC ? (0xFB32 | TWO_POINTS) : NO_MATCH;
	case 0x5D3:
		return b == 0x5BC ? (0xFB33 | TWO_POINTS) : NO_MATCH;
	case 0x5D4:
		return b == 0x5BC ? (0xFB34 | TWO_POINTS) : NO_MATCH;
	case 0x5D5:
		return b == 0x5BC ? (0xFB35 | TWO_POINTS)
			: b == 0x5B9 ? (0xFB4B | TWO_POINTS)
			: NO_MATCH;
	case 0x5D6:
		return b == 0x5BC ? (0xFB36 | TWO_POINTS) : NO_MATCH;
	case 0x5D8:
		return b == 0x5BC ? (0xFB38 | TWO_POINTS) : NO_MATCH;
	case 0x5D9:
		return b == 0x5B4 ? (0xFB1D | TWO_POINTS)
			: b == 0x5BC ? (0xFB39 | TWO_POINTS)
			: NO_MATCH;
	case 0x5DA:
		return b == 0x5BC ? (0xFB3A | TWO_POINTS) : NO_MATCH;
	case 0x5DB:
		return b == 0x5BC ? (0xFB3B | TWO_POINTS)
			: b == 0x5BF ? (0xFB4D | TWO_POINTS)
			: NO_MATCH;
	case 0x5DC:
		return b == 0x5BC ? (0xFB3C | TWO_POINTS) : NO_MATCH;
	case 0x5DE:
		return b == 0x5BC ? (0xFB3E | TWO_POINTS) : NO_MATCH;
	case 0x5E0:
		return b == 0x5BC ? (0xFB40 | TWO_POINTS) : NO_MATCH;
	case 0x5E1:
		return b == 0x5BC ? (0xFB41 | TWO_POINTS) : NO_MATCH;
	case 0x5E3:
		return b == 0x5BC ? (0xFB43 | TWO_POINTS) : NO_MATCH;
	case 0x5E4:
		return b == 0x5BC ? (0xFB44 | TWO_POINTS)
			: b == 0x5BF ? (0xFB4E | TWO_POINTS)
			: NO_MATCH;
	case 0x5E6:
		return b == 0x5BC ? (0xFB46 | TWO_POINTS) : NO_MATCH;
	case 0x5E7:
		return b == 0x5BC ? (0xFB47 | TWO_POINTS) : NO_MATCH;
	case 0x5E8:
		return b == 0x5BC ? (0xFB48 | TWO_POINTS) : NO_MATCH;
	case 0x5E9:
		switch (b) {
		case 0x5BC:
			return c == 0x5C1 ? (0xFB2C | THREE_POINTS)
				: c == 0x5C2 ? (0xFB2D | THREE_POINTS)
				: (0xFB49 | TWO_POINTS);
		case 0x5C1: return (0xFB2A | TWO_POINTS);
		case 0x5C2: return (0xFB2B | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x5EA:
		return b == 0x5BC ? (0xFB4A | TWO_POINTS) : NO_MATCH;
	case 0x5F2:
		return b == 0x5B7 ? (0xFB1F | TWO_POINTS) : NO_MATCH;
	case 0x627:
		switch (b) {
		case 0x653: return (0x622 | TWO_POINTS);
		case 0x654: return (0x623 | TWO_POINTS);
		case 0x655: return (0x625 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x648:
		return b == 0x654 ? (0x624 | TWO_POINTS) : NO_MATCH;
	case 0x64A:
		return b == 0x654 ? (0x626 | TWO_POINTS) : NO_MATCH;
	case 0x6C1:
		return b == 0x654 ? (0x6C2 | TWO_POINTS) : NO_MATCH;
	case 0x6D2:
		return b == 0x654 ? (0x6D3 | TWO_POINTS) : NO_MATCH;
	case 0x6D5:
		return b == 0x654 ? (0x6C0 | TWO_POINTS) : NO_MATCH;
	case 0x915:
		return b == 0x93C ? (0x958 | TWO_POINTS) : NO_MATCH;
	case 0x916:
		return b == 0x93C ? (0x959 | TWO_POINTS) : NO_MATCH;
	case 0x917:
		return b == 0x93C ? (0x95A | TWO_POINTS) : NO_MATCH;
	case 0x91C:
		return b == 0x93C ? (0x95B | TWO_POINTS) : NO_MATCH;
	case 0x921:
		return b == 0x93C ? (0x95C | TWO_POINTS) : NO_MATCH;
	case 0x922:
		return b == 0x93C ? (0x95D | TWO_POINTS) : NO_MATCH;
	case 0x928:
		return b == 0x93C ? (0x929 | TWO_POINTS) : NO_MATCH;
	case 0x92B:
		return b == 0x93C ? (0x95E | TWO_POINTS) : NO_MATCH;
	case 0x92F:
		return b == 0x93C ? (0x95F | TWO_POINTS) : NO_MATCH;
	case 0x930:
		return b == 0x93C ? (0x931 | TWO_POINTS) : NO_MATCH;
	case 0x933:
		return b == 0x93C ? (0x934 | TWO_POINTS) : NO_MATCH;
	case 0x9A1:
		return b == 0x9BC ? (0x9DC | TWO_POINTS) : NO_MATCH;
	case 0x9A2:
		return b == 0x9BC ? (0x9DD | TWO_POINTS) : NO_MATCH;
	case 0x9AF:
		return b == 0x9BC ? (0x9DF | TWO_POINTS) : NO_MATCH;
	case 0x9C7:
		return b == 0x9BE ? (0x9CB | TWO_POINTS)
			: b == 0x9D7 ? (0x9CC | TWO_POINTS)
			: NO_MATCH;
	case 0xA16:
		return b == 0xA3C ? (0xA59 | TWO_POINTS) : NO_MATCH;
	case 0xA17:
		return b == 0xA3C ? (0xA5A | TWO_POINTS) : NO_MATCH;
	case 0xA1C:
		return b == 0xA3C ? (0xA5B | TWO_POINTS) : NO_MATCH;
	case 0xA2B:
		return b == 0xA3C ? (0xA5E | TWO_POINTS) : NO_MATCH;
	case 0xA32:
		return b == 0xA3C ? (0xA33 | TWO_POINTS) : NO_MATCH;
	case 0xA38:
		return b == 0xA3C ? (0xA36 | TWO_POINTS) : NO_MATCH;
	case 0xB21:
		return b == 0xB3C ? (0xB5C | TWO_POINTS) : NO_MATCH;
	case 0xB22:
		return b == 0xB3C ? (0xB5D | TWO_POINTS) : NO_MATCH;
	case 0xB47:
		switch (b) {
		case 0xB3E: return (0xB4B | TWO_POINTS);
		case 0xB56: return (0xB48 | TWO_POINTS);
		case 0xB57: return (0xB4C | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0xB92:
		return b == 0xBD7 ? (0xB94 | TWO_POINTS) : NO_MATCH;
	case 0xBC6:
		return b == 0xBBE ? (0xBCA | TWO_POINTS)
			: b == 0xBD7 ? (0xBCC | TWO_POINTS)
			: NO_MATCH;
	case 0xBC7:
		return b == 0xBBE ? (0xBCB | TWO_POINTS) : NO_MATCH;
	case 0xC46:
		return b == 0xC56 ? (0xC48 | TWO_POINTS) : NO_MATCH;
	case 0xCBF:
		return b == 0xCD5 ? (0xCC0 | TWO_POINTS) : NO_MATCH;
	case 0xCC6:
		switch (b) {
		case 0xCC2:
			return c == 0xCD5 ? (0xCCB | THREE_POINTS) : (0xCCA | TWO_POINTS);
		case 0xCD5: return (0xCC7 | TWO_POINTS);
		case 0xCD6: return (0xCC8 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0xD46:
		return b == 0xD3E ? (0xD4A | TWO_POINTS)
			: b == 0xD57 ? (0xD4C | TWO_POINTS)
			: NO_MATCH;
	case 0xD47:
		return b == 0xD3E ? (0xD4B | TWO_POINTS) : NO_MATCH;
	case 0xDD9:
		switch (b) {
		case 0xDCA: return (0xDDA | TWO_POINTS);
		case 0xDCF:
			return c == 0xDCA ? (0xDDD | THREE_POINTS) : (0xDDC | TWO_POINTS);
		case 0xDDF: return (0xDDE | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0xF40:
		return b == 0xFB5 ? (0xF69 | TWO_POINTS) : NO_MATCH;
	case 0xF42:
		return b == 0xFB7 ? (0xF43 | TWO_POINTS) : NO_MATCH;
	case 0xF4C:
		return b == 0xFB7 ? (0xF4D | TWO_POINTS) : NO_MATCH;
	case 0xF51:
		return b == 0xFB7 ? (0xF52 | TWO_POINTS) : NO_MATCH;
	case 0xF56:
		return b == 0xFB7 ? (0xF57 | TWO_POINTS) : NO_MATCH;
	case 0xF5B:
		return b == 0xFB7 ? (0xF5C | TWO_POINTS) : NO_MATCH;
	case 0xF71:
		switch (b) {
		case 0xF72: return (0xF73 | TWO_POINTS);
		case 0xF74: return (0xF75 | TWO_POINTS);
		case 0xF80: return (0xF81 | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0xF90:
		return b == 0xFB5 ? (0xFB9 | TWO_POINTS) : NO_MATCH;
	case 0xF92:
		return b == 0xFB7 ? (0xF93 | TWO_POINTS) : NO_MATCH;
	case 0xF9C:
		return b == 0xFB7 ? (0xF9D | TWO_POINTS) : NO_MATCH;
	case 0xFA1:
		return b == 0xFB7 ? (0xFA2 | TWO_POINTS) : NO_MATCH;
	case 0xFA6:
		return b == 0xFB7 ? (0xFA7 | TWO_POINTS) : NO_MATCH;
	case 0xFAB:
		return b == 0xFB7 ? (0xFAC | TWO_POINTS) : NO_MATCH;
	case 0xFB2:
		return b == 0xF80 ? (0xF76 | TWO_POINTS) : NO_MATCH;
	case 0xFB3:
		return b == 0xF80 ? (0xF78 | TWO_POINTS) : NO_MATCH;
	case 0x1025:
		return b == 0x102E ? (0x1026 | TWO_POINTS) : NO_MATCH;
	case 0x1B05:
		return b == 0x1B35 ? (0x1B06 | TWO_POINTS) : NO_MATCH;
	case 0x1B07:
		return b == 0x1B35 ? (0x1B08 | TWO_POINTS) : NO_MATCH;
	case 0x1B09:
		return b == 0x1B35 ? (0x1B0A | TWO_POINTS) : NO_MATCH;
	case 0x1B0B:
		return b == 0x1B35 ? (0x1B0C | TWO_POINTS) : NO_MATCH;
	case 0x1B0D:
		return b == 0x1B35 ? (0x1B0E | TWO_POINTS) : NO_MATCH;
	case 0x1B11:
		return b == 0x1B35 ? (0x1B12 | TWO_POINTS) : NO_MATCH;
	case 0x1B3A:
		return b == 0x1B35 ? (0x1B3B | TWO_POINTS) : NO_MATCH;
	case 0x1B3C:
		return b == 0x1B35 ? (0x1B3D | TWO_POINTS) : NO_MATCH;
	case 0x1B3E:
		return b == 0x1B35 ? (0x1B40 | TWO_POINTS) : NO_MATCH;
	case 0x1B3F:
		return b == 0x1B35 ? (0x1B41 | TWO_POINTS) : NO_MATCH;
	case 0x1B42:
		return b == 0x1B35 ? (0x1B43 | TWO_POINTS) : NO_MATCH;
	case 0x1FBF:
		switch (b) {
		case 0x300: return (0x1FCD | TWO_POINTS);
		case 0x301: return (0x1FCE | TWO_POINTS);
		case 0x342: return (0x1FCF | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x1FFE:
		switch (b) {
		case 0x300: return (0x1FDD | TWO_POINTS);
		case 0x301: return (0x1FDE | TWO_POINTS);
		case 0x342: return (0x1FDF | TWO_POINTS);
		default: return NO_MATCH;
		}
	case 0x2190:
		return b == 0x338 ? (0x219A | TWO_POINTS) : NO_MATCH;
	case 0x2192:
		return b == 0x338 ? (0x219B | TWO_POINTS) : NO_MATCH;
	case 0x2194:
		return b == 0x338 ? (0x21AE | TWO_POINTS) : NO_MATCH;
	case 0x21D0:
		return b == 0x338 ? (0x21CD | TWO_POINTS) : NO_MATCH;
	case 0x21D2:
		return b == 0x338 ? (0x21CF | TWO_POINTS) : NO_MATCH;
	case 0x21D4:
		return b == 0x338 ? (0x21CE | TWO_POINTS) : NO_MATCH;
	case 0x2203:
		return b == 0x338 ? (0x2204 | TWO_POINTS) : NO_MATCH;
	case 0x2208:
		return b == 0x338 ? (0x2209 | TWO_POINTS) : NO_MATCH;
	case 0x220B:
		return b == 0x338 ? (0x220C | TWO_POINTS) : NO_MATCH;
	case 0x2223:
		return b == 0x338 ? (0x2224 | TWO_POINTS) : NO_MATCH;
	case 0x2225:
		return b == 0x338 ? (0x2226 | TWO_POINTS) : NO_MATCH;
	case 0x223C:
		return b == 0x338 ? (0x2241 | TWO_POINTS) : NO_MATCH;
	case 0x2243:
		return b == 0x338 ? (0x2244 | TWO_POINTS) : NO_MATCH;
	case 0x2245:
		return b == 0x338 ? (0x2247 | TWO_POINTS) : NO_MATCH;
	case 0x2248:
		return b == 0x338 ? (0x2249 | TWO_POINTS) : NO_MATCH;
	case 0x224D:
		return b == 0x338 ? (0x226D | TWO_POINTS) : NO_MATCH;
	case 0x2261:
		return b == 0x338 ? (0x2262 | TWO_POINTS) : NO_MATCH;
	case 0x2264:
		return b == 0x338 ? (0x2270 | TWO_POINTS) : NO_MATCH;
	case 0x2265:
		return b == 0x338 ? (0x2271 | TWO_POINTS) : NO_MATCH;
	case 0x2272:
		return b == 0x338 ? (0x2274 | TWO_POINTS) : NO_MATCH;
	case 0x2273:
		return b == 0x338 ? (0x2275 | TWO_POINTS) : NO_MATCH;
	case 0x2276:
		return b == 0x338 ? (0x2278 | TWO_POINTS) : NO_MATCH;
	case 0x2277:
		return b == 0x338 ? (0x2279 | TWO_POINTS) : NO_MATCH;
	case 0x227A:
		return b == 0x338 ? (0x2280 | TWO_POINTS) : NO_MATCH;
	case 0x227B:
		return b == 0x338 ? (0x2281 | TWO_POINTS) : NO_MATCH;
	case 0x227C:
		return b == 0x338 ? (0x22E0 | TWO_POINTS) : NO_MATCH;
	case 0x227D:
		return b == 0x338 ? (0x22E1 | TWO_POINTS) : NO_MATCH;
	case 0x2282:
		return b == 0x338 ? (0x2284 | TWO_POINTS) : NO_MATCH;
	case 0x2283:
		return b == 0x338 ? (0x2285 | TWO_POINTS) : NO_MATCH;
	case 0x2286:
		return b == 0x338 ? (0x2288 | TWO_POINTS) : NO_MATCH;
	case 0x2287:
		return b == 0x338 ? (0x2289 | TWO_POINTS) : NO_MATCH;
	case 0x2291:
		return b == 0x338 ? (0x22E2 | TWO_POINTS) : NO_MATCH;
	case 0x2292:
		return b == 0x338 ? (0x22E3 | TWO_POINTS) : NO_MATCH;
	case 0x22A2:
		return b == 0x338 ? (0x22AC | TWO_POINTS) : NO_MATCH;
	case 0x22A8:
		return b == 0x338 ? (0x22AD | TWO_POINTS) : NO_MATCH;
	case 0x22A9:
		return b == 0x338 ? (0x22AE | TWO_POINTS) : NO_MATCH;
	case 0x22AB:
		return b == 0x338 ? (0x22AF | TWO_POINTS) : NO_MATCH;
	case 0x22B2:
		return b == 0x338 ? (0x22EA | TWO_POINTS) : NO_MATCH;
	case 0x22B3:
		return b == 0x338 ? (0x22EB | TWO_POINTS) : NO_MATCH;
	case 0x22B4:
		return b == 0x338 ? (0x22EC | TWO_POINTS) : NO_MATCH;
	case 0x22B5:
		return b == 0x338 ? (0x22ED | TWO_POINTS) : NO_MATCH;
	case 0x2ADD:
		return b == 0x338 ? (0x2ADC | TWO_POINTS) : NO_MATCH;
	case 0x3046:
		return b == 0x3099 ? (0x3094 | TWO_POINTS) : NO_MATCH;
	case 0x304B:
		return b == 0x3099 ? (0x304C | TWO_POINTS) : NO_MATCH;
	case 0x304D:
		return b == 0x3099 ? (0x304E | TWO_POINTS) : NO_MATCH;
	case 0x304F:
		return b == 0x3099 ? (0x3050 | TWO_POINTS) : NO_MATCH;
	case 0x3051:
		return b == 0x3099 ? (0x3052 | TWO_POINTS) : NO_MATCH;
	case 0x3053:
		return b == 0x3099 ? (0x3054 | TWO_POINTS) : NO_MATCH;
	case 0x3055:
		return b == 0x3099 ? (0x3056 | TWO_POINTS) : NO_MATCH;
	case 0x3057:
		return b == 0x3099 ? (0x3058 | TWO_POINTS) : NO_MATCH;
	case 0x3059:
		return b == 0x3099 ? (0x305A | TWO_POINTS) : NO_MATCH;
	case 0x305B:
		return b == 0x3099 ? (0x305C | TWO_POINTS) : NO_MATCH;
	case 0x305D:
		return b == 0x3099 ? (0x305E | TWO_POINTS) : NO_MATCH;
	case 0x305F:
		return b == 0x3099 ? (0x3060 | TWO_POINTS) : NO_MATCH;
	case 0x3061:
		return b == 0x3099 ? (0x3062 | TWO_POINTS) : NO_MATCH;
	case 0x3064:
		return b == 0x3099 ? (0x3065 | TWO_POINTS) : NO_MATCH;
	case 0x3066:
		return b == 0x3099 ? (0x3067 | TWO_POINTS) : NO_MATCH;
	case 0x3068:
		return b == 0x3099 ? (0x3069 | TWO_POINTS) : NO_MATCH;
	case 0x306F:
		return b == 0x3099 ? (0x3070 | TWO_POINTS)
			: b == 0x309A ? (0x3071 | TWO_POINTS)
			: NO_MATCH;
	case 0x3072:
		return b == 0x3099 ? (0x3073 | TWO_POINTS)
			: b == 0x309A ? (0x3074 | TWO_POINTS)
			: NO_MATCH;
	case 0x3075:
		return b == 0x3099 ? (0x3076 | TWO_POINTS)
			: b == 0x309A ? (0x3077 | TWO_POINTS)
			: NO_MATCH;
	case 0x3078:
		return b == 0x3099 ? (0x3079 | TWO_POINTS)
			: b == 0x309A ? (0x307A | TWO_POINTS)
			: NO_MATCH;
	case 0x307B:
		return b == 0x3099 ? (0x307C | TWO_POINTS)
			: b == 0x309A ? (0x307D | TWO_POINTS)
			: NO_MATCH;
	case 0x309D:
		return b == 0x3099 ? (0x309E | TWO_POINTS) : NO_MATCH;
	case 0x30A6:
		return b == 0x3099 ? (0x30F4 | TWO_POINTS) : NO_MATCH;
	case 0x30AB:
		return b == 0x3099 ? (0x30AC | TWO_POINTS) : NO_MATCH;
	case 0x30AD:
		return b == 0x3099 ? (0x30AE | TWO_POINTS) : NO_MATCH;
	case 0x30AF:
		return b == 0x3099 ? (0x30B0 | TWO_POINTS) : NO_MATCH;
	case 0x30B1:
		return b == 0x3099 ? (0x30B2 | TWO_POINTS) : NO_MATCH;
	case 0x30B3:
		return b == 0x3099 ? (0x30B4 | TWO_POINTS) : NO_MATCH;
	case 0x30B5:
		return b == 0x3099 ? (0x30B6 | TWO_POINTS) : NO_MATCH;
	case 0x30B7:
		return b == 0x3099 ? (0x30B8 | TWO_POINTS) : NO_MATCH;
	case 0x30B9:
		return b == 0x3099 ? (0x30BA | TWO_POINTS) : NO_MATCH;
	case 0x30BB:
		return b == 0x3099 ? (0x30BC | TWO_POINTS) : NO_MATCH;
	case 0x30BD:
		return b == 0x3099 ? (0x30BE | TWO_POINTS) : NO_MATCH;
	case 0x30BF:
		return b == 0x3099 ? (0x30C0 | TWO_POINTS) : NO_MATCH;
	case 0x30C1:
		return b == 0x3099 ? (0x30C2 | TWO_POINTS) : NO_MATCH;
	case 0x30C4:
		return b == 0x3099 ? (0x30C5 | TWO_POINTS) : NO_MATCH;
	case 0x30C6:
		return b == 0x3099 ? (0x30C7 | TWO_POINTS) : NO_MATCH;
	case 0x30C8:
		return b == 0x3099 ? (0x30C9 | TWO_POINTS) : NO_MATCH;
	case 0x30CF:
		return b == 0x3099 ? (0x30D0 | TWO_POINTS)
			: b == 0x309A ? (0x30D1 | TWO_POINTS)
			: NO_MATCH;
	case 0x30D2:
		return b == 0x3099 ? (0x30D3 | TWO_POINTS)
			: b == 0x309A ? (0x30D4 | TWO_POINTS)
			: NO_MATCH;
	case 0x30D5:
		return b == 0x3099 ? (0x30D6 | TWO_POINTS)
			: b == 0x309A ? (0x30D7 | TWO_POINTS)
			: NO_MATCH;
	case 0x30D8:
		return b == 0x3099 ? (0x30D9 | TWO_POINTS)
			: b == 0x309A ? (0x30DA | TWO_POINTS)
			: NO_MATCH;
	case 0x30DB:
		return b == 0x3099 ? (0x30DC | TWO_POINTS)
			: b == 0x309A ? (0x30DD | TWO_POINTS)
			: NO_MATCH;
	case 0x30EF:
		return b == 0x3099 ? (0x30F7 | TWO_POINTS) : NO_MATCH;
	case 0x30F0:
		return b == 0x3099 ? (0x30F8 | TWO_POINTS) : NO_MATCH;
	case 0x30F1:
		return b == 0x3099 ? (0x30F9 | TWO_POINTS) : NO_MATCH;
	case 0x30F2:
		return b == 0x3099 ? (0x30FA | TWO_POINTS) : NO_MATCH;
	case 0x30FD:
		return b == 0x3099 ? (0x30FE | TWO_POINTS) : NO_MATCH;
	case 0x11099:
		return b == 0x110BA ? (0x1109A | TWO_POINTS) : NO_MATCH;
	case 0x1109B:
		return b == 0x110BA ? (0x1109C | TWO_POINTS) : NO_MATCH;
	case 0x110A5:
		return b == 0x110BA ? (0x110AB | TWO_POINTS) : NO_MATCH;
	case 0x11131:
		return b == 0x11127 ? (0x1112E | TWO_POINTS) : NO_MATCH;
	case 0x11132:
		return b == 0x11127 ? (0x1112F | TWO_POINTS) : NO_MATCH;
	case 0x1D157:
		return b == 0x1D165 ? (0x1D15E | TWO_POINTS) : NO_MATCH;
	case 0x1D158:
		return b == 0x1D165 ? (0x1D15F | TWO_POINTS) : NO_MATCH;
	case 0x1D1B9:
		return b == 0x1D165 ? (0x1D1BB | TWO_POINTS) : NO_MATCH;
	case 0x1D1BA:
		return b == 0x1D165 ? (0x1D1BC | TWO_POINTS) : NO_MATCH;
	default: return NO_MATCH;
	}
}
