//-----------------------------------------------------
// THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT!
//
// bootstrap.c:  Smile source code, compiled to byte-
// code, and embedded within optimized C, designed to
// run at startup to add functions and methods to the
// "global" namespace, all written in Smile itself.
//
// THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT!
//-----------------------------------------------------

#include <smile/smiletypes/smileobject.h>
#include <smile/smiletypes/smileuserobject.h>
#include <smile/smiletypes/smilelist.h>
#include <smile/smiletypes/smilebool.h>
#include <smile/smiletypes/text/smilesymbol.h>
#include <smile/smiletypes/numeric/smilebyte.h>
#include <smile/smiletypes/numeric/smileinteger16.h>
#include <smile/smiletypes/numeric/smileinteger32.h>
#include <smile/smiletypes/numeric/smileinteger64.h>
#include <smile/smiletypes/range/smileinteger64range.h>
#include <smile/smiletypes/smilefunction.h>
#include <smile/eval/compiler.h>
#include <smile/internal/staticstring.h>

SMILE_IGNORE_UNUSED_VARIABLES

//-----------------------------------------------------------------------------
// Data declarations

//--- String declarations ---

STATIC_STRING(_str_Float32, "Float32");
STATIC_STRING(_str_double, "double");
STATIC_STRING(_str_self, "self");
STATIC_STRING(_str__2A, "*");
STATIC_STRING(_str_half, "half");
STATIC_STRING(_str_Float64, "Float64");
STATIC_STRING(_str_IntegerBase, "IntegerBase");
STATIC_STRING(_str__3C_3C, "<<");
STATIC_STRING(_str__3E_3E, ">>");
STATIC_STRING(_str_Real32, "Real32");
STATIC_STRING(_str_Real64, "Real64");
STATIC_STRING(_str_test_2Esm, "test.sm");

//--- Symbol declarations ---

static Int32 _sym_Float32;
static Int32 _sym_double;
static Int32 _sym_self;
static Int32 _sym__2A;
static Int32 _sym_half;
static Int32 _sym_Float64;
static Int32 _sym_IntegerBase;
static Int32 _sym__3C_3C;
static Int32 _sym__3E_3E;
static Int32 _sym_Real32;
static Int32 _sym_Real64;

//--- SmileSymbol declarations ---

static struct SmileSymbolInt _smileSym_self;

//--- Other data declarations ---

static struct SmileListInt _list_0;
static struct SmileFunctionInt _fn_0;
static struct SmileListInt _list_1;
static struct SmileFunctionInt _fn_1;
static struct SmileListInt _list_2;
static struct SmileFunctionInt _fn_2;
static struct SmileListInt _list_3;
static struct SmileFunctionInt _fn_3;
static struct SmileListInt _list_4;
static struct SmileFunctionInt _fn_4;
static struct SmileListInt _list_5;
static struct SmileFunctionInt _fn_5;
static struct SmileListInt _list_6;
static struct SmileFunctionInt _fn_6;
static struct SmileListInt _list_7;
static struct SmileFunctionInt _fn_7;
static struct SmileListInt _list_8;
static struct SmileFunctionInt _fn_8;
static struct SmileListInt _list_9;
static struct SmileFunctionInt _fn_9;

//-----------------------------------------------------------------------------
// UserFunction declarations 

static struct UserFunctionInfoStruct _ufn_0;
static struct UserFunctionInfoStruct _ufn_1;
static struct UserFunctionInfoStruct _ufn_2;
static struct UserFunctionInfoStruct _ufn_3;
static struct UserFunctionInfoStruct _ufn_4;
static struct UserFunctionInfoStruct _ufn_5;
static struct UserFunctionInfoStruct _ufn_6;
static struct UserFunctionInfoStruct _ufn_7;
static struct UserFunctionInfoStruct _ufn_8;
static struct UserFunctionInfoStruct _ufn_9;

//-----------------------------------------------------------------------------
// Compiler data tables

static String _compiledTables_Strings[1] = {
	NULL,
};
static struct CompiledSourceLocationStruct _compiledTables_SrcLocs[31] = {
	{ NULL, 0, 0, 0 },
	{ ((String)&_str_test_2EsmStruct), 17, 12, 0 },
	{ ((String)&_str_test_2EsmStruct), 29, 12, 0 },
	{ ((String)&_str_test_2EsmStruct), 17, 12, 0 },
	{ ((String)&_str_test_2EsmStruct), 15, 11, 0 },
	{ ((String)&_str_test_2EsmStruct), 27, 11, 0 },
	{ ((String)&_str_test_2EsmStruct), 15, 11, 0 },
	{ ((String)&_str_test_2EsmStruct), 17, 15, 0 },
	{ ((String)&_str_test_2EsmStruct), 29, 15, 0 },
	{ ((String)&_str_test_2EsmStruct), 17, 15, 0 },
	{ ((String)&_str_test_2EsmStruct), 15, 14, 0 },
	{ ((String)&_str_test_2EsmStruct), 27, 14, 0 },
	{ ((String)&_str_test_2EsmStruct), 15, 14, 0 },
	{ ((String)&_str_test_2EsmStruct), 21, 3, 0 },
	{ ((String)&_str_test_2EsmStruct), 33, 3, 0 },
	{ ((String)&_str_test_2EsmStruct), 21, 3, 0 },
	{ ((String)&_str_test_2EsmStruct), 19, 2, 0 },
	{ ((String)&_str_test_2EsmStruct), 31, 2, 0 },
	{ ((String)&_str_test_2EsmStruct), 19, 2, 0 },
	{ ((String)&_str_test_2EsmStruct), 16, 6, 0 },
	{ ((String)&_str_test_2EsmStruct), 28, 6, 0 },
	{ ((String)&_str_test_2EsmStruct), 16, 6, 0 },
	{ ((String)&_str_test_2EsmStruct), 14, 5, 0 },
	{ ((String)&_str_test_2EsmStruct), 26, 5, 0 },
	{ ((String)&_str_test_2EsmStruct), 14, 5, 0 },
	{ ((String)&_str_test_2EsmStruct), 16, 9, 0 },
	{ ((String)&_str_test_2EsmStruct), 28, 9, 0 },
	{ ((String)&_str_test_2EsmStruct), 16, 9, 0 },
	{ ((String)&_str_test_2EsmStruct), 14, 8, 0 },
	{ ((String)&_str_test_2EsmStruct), 26, 8, 0 },
	{ ((String)&_str_test_2EsmStruct), 14, 8, 0 },
};
static UserFunctionInfo _compiledTables_Fns[10] = {
	((UserFunctionInfo)&_ufn_0),
	((UserFunctionInfo)&_ufn_1),
	((UserFunctionInfo)&_ufn_2),
	((UserFunctionInfo)&_ufn_3),
	((UserFunctionInfo)&_ufn_4),
	((UserFunctionInfo)&_ufn_5),
	((UserFunctionInfo)&_ufn_6),
	((UserFunctionInfo)&_ufn_7),
	((UserFunctionInfo)&_ufn_8),
	((UserFunctionInfo)&_ufn_9),
};
static SmileObject _compiledTables_Objs[1] = {
	NULL,
};
static TillContinuationInfo _compiledTables_Tills[1] = {
	NULL,
};
static struct CompiledTablesStruct _compiledTables = {
	NULL, NULL,
	_compiledTables_Strings, 0, 0, NULL,
	_compiledTables_Fns, 10, 10,
	_compiledTables_Objs, 0, 0,
	_compiledTables_Tills, 0, 0,
	_compiledTables_SrcLocs, 31, 31
};

//-----------------------------------------------------------------------------
// ByteCode segments

static struct ByteCodeStruct _bc_0[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x2A, { 0 }, 0, { 0x40000000 } },
	{ 0x99, { 0 }, 0, { 0x39 } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_0 = { &_compiledTables, _bc_0, 4, 4 };
static struct ByteCodeStruct _bc_1[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x2A, { 0 }, 0, { 0x3F000000 } },
	{ 0x99, { 0 }, 0, { 0x39 } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_1 = { &_compiledTables, _bc_1, 4, 4 };
static struct ByteCodeStruct _bc_2[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x2B, { 0 }, 0, { 0x4000000000000000LLU } },
	{ 0x99, { 0 }, 0, { 0x39 } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_2 = { &_compiledTables, _bc_2, 4, 4 };
static struct ByteCodeStruct _bc_3[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x2B, { 0 }, 0, { 0x3FE0000000000000LLU } },
	{ 0x99, { 0 }, 0, { 0x39 } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_3 = { &_compiledTables, _bc_3, 4, 4 };
static struct ByteCodeStruct _bc_4[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x1B, { 0 }, 0, { 0x1 } },
	{ 0x99, { 0 }, 0, { 0x4A } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_4 = { &_compiledTables, _bc_4, 4, 4 };
static struct ByteCodeStruct _bc_5[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x1B, { 0 }, 0, { 0x1 } },
	{ 0x99, { 0 }, 0, { 0x4B } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_5 = { &_compiledTables, _bc_5, 4, 4 };
static struct ByteCodeStruct _bc_6[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x22, { 0 }, 0, { 0x32800002 } },
	{ 0x99, { 0 }, 0, { 0x39 } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_6 = { &_compiledTables, _bc_6, 4, 4 };
static struct ByteCodeStruct _bc_7[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x22, { 0 }, 0, { 0x32000005 } },
	{ 0x99, { 0 }, 0, { 0x39 } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_7 = { &_compiledTables, _bc_7, 4, 4 };
static struct ByteCodeStruct _bc_8[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x23, { 0 }, 0, { 0x31C0000000000002LLU } },
	{ 0x99, { 0 }, 0, { 0x39 } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_8 = { &_compiledTables, _bc_8, 4, 4 };
static struct ByteCodeStruct _bc_9[] = {
	{ 0x40, { 0 }, 0, { 0x0 } },
	{ 0x23, { 0 }, 0, { 0x31A0000000000005LLU } },
	{ 0x99, { 0 }, 0, { 0x39 } },
	{ 0xBB, { 0 }, 0, { 0x0 } },
};
static struct ByteCodeSegmentStruct _bcs_9 = { &_compiledTables, _bc_9, 4, 4 };

//-----------------------------------------------------------------------------
// Symbol registrations

static void SetupSymbols(SymbolTable symbolTable)
{
	_sym_Float32 = SymbolTable_GetSymbol(symbolTable, ((String)&_str_Float32Struct));
	_sym_double = SymbolTable_GetSymbol(symbolTable, ((String)&_str_doubleStruct));
	_sym_self = SymbolTable_GetSymbol(symbolTable, ((String)&_str_selfStruct));
	_sym__2A = SymbolTable_GetSymbol(symbolTable, ((String)&_str__2AStruct));
	_sym_half = SymbolTable_GetSymbol(symbolTable, ((String)&_str_halfStruct));
	_sym_Float64 = SymbolTable_GetSymbol(symbolTable, ((String)&_str_Float64Struct));
	_sym_IntegerBase = SymbolTable_GetSymbol(symbolTable, ((String)&_str_IntegerBaseStruct));
	_sym__3C_3C = SymbolTable_GetSymbol(symbolTable, ((String)&_str__3C_3CStruct));
	_sym__3E_3E = SymbolTable_GetSymbol(symbolTable, ((String)&_str__3E_3EStruct));
	_sym_Real32 = SymbolTable_GetSymbol(symbolTable, ((String)&_str_Real32Struct));
	_sym_Real64 = SymbolTable_GetSymbol(symbolTable, ((String)&_str_Real64Struct));

	SmileSymbol_Init(((SmileSymbol)&_smileSym_self), _sym_self);
}

//-----------------------------------------------------------------------------
// Bytecode fixups

static void FixupBytecode(void)
{
	_bc_0[2].u.symbol = _sym__2A;
	_bc_1[2].u.symbol = _sym__2A;
	_bc_2[2].u.symbol = _sym__2A;
	_bc_3[2].u.symbol = _sym__2A;
	_bc_4[2].u.symbol = _sym__3C_3C;
	_bc_5[2].u.symbol = _sym__3E_3E;
	_bc_6[2].u.symbol = _sym__2A;
	_bc_7[2].u.symbol = _sym__2A;
	_bc_8[2].u.symbol = _sym__2A;
	_bc_9[2].u.symbol = _sym__2A;
}

//-----------------------------------------------------------------------------
// Raw-data bootstrapping

static void SetupData(Closure globalClosure)
{
	ClosureInfo ci;

	SmileList_Init(((SmileList)&_list_0), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_0.parent = NULL;
	_ufn_0.argList = ((SmileList)&_list_0);
	_ufn_0.position = NULL;
	_ufn_0.body = NullObject;
	_ufn_0.byteCodeSegment = ((ByteCodeSegment)&_bcs_0);
	ci = (ClosureInfo)&_ufn_0.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_0), ((SmileList)&_list_0), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_0), ((UserFunctionInfo)&_ufn_0), globalClosure);

	SmileList_Init(((SmileList)&_list_1), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_1.parent = NULL;
	_ufn_1.argList = ((SmileList)&_list_1);
	_ufn_1.position = NULL;
	_ufn_1.body = NullObject;
	_ufn_1.byteCodeSegment = ((ByteCodeSegment)&_bcs_1);
	ci = (ClosureInfo)&_ufn_1.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_1), ((SmileList)&_list_1), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_1), ((UserFunctionInfo)&_ufn_1), globalClosure);

	SmileList_Init(((SmileList)&_list_2), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_2.parent = NULL;
	_ufn_2.argList = ((SmileList)&_list_2);
	_ufn_2.position = NULL;
	_ufn_2.body = NullObject;
	_ufn_2.byteCodeSegment = ((ByteCodeSegment)&_bcs_2);
	ci = (ClosureInfo)&_ufn_2.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_2), ((SmileList)&_list_2), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_2), ((UserFunctionInfo)&_ufn_2), globalClosure);

	SmileList_Init(((SmileList)&_list_3), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_3.parent = NULL;
	_ufn_3.argList = ((SmileList)&_list_3);
	_ufn_3.position = NULL;
	_ufn_3.body = NullObject;
	_ufn_3.byteCodeSegment = ((ByteCodeSegment)&_bcs_3);
	ci = (ClosureInfo)&_ufn_3.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_3), ((SmileList)&_list_3), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_3), ((UserFunctionInfo)&_ufn_3), globalClosure);

	SmileList_Init(((SmileList)&_list_4), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_4.parent = NULL;
	_ufn_4.argList = ((SmileList)&_list_4);
	_ufn_4.position = NULL;
	_ufn_4.body = NullObject;
	_ufn_4.byteCodeSegment = ((ByteCodeSegment)&_bcs_4);
	ci = (ClosureInfo)&_ufn_4.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_4), ((SmileList)&_list_4), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_4), ((UserFunctionInfo)&_ufn_4), globalClosure);

	SmileList_Init(((SmileList)&_list_5), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_5.parent = NULL;
	_ufn_5.argList = ((SmileList)&_list_5);
	_ufn_5.position = NULL;
	_ufn_5.body = NullObject;
	_ufn_5.byteCodeSegment = ((ByteCodeSegment)&_bcs_5);
	ci = (ClosureInfo)&_ufn_5.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_5), ((SmileList)&_list_5), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_5), ((UserFunctionInfo)&_ufn_5), globalClosure);

	SmileList_Init(((SmileList)&_list_6), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_6.parent = NULL;
	_ufn_6.argList = ((SmileList)&_list_6);
	_ufn_6.position = NULL;
	_ufn_6.body = NullObject;
	_ufn_6.byteCodeSegment = ((ByteCodeSegment)&_bcs_6);
	ci = (ClosureInfo)&_ufn_6.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_6), ((SmileList)&_list_6), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_6), ((UserFunctionInfo)&_ufn_6), globalClosure);

	SmileList_Init(((SmileList)&_list_7), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_7.parent = NULL;
	_ufn_7.argList = ((SmileList)&_list_7);
	_ufn_7.position = NULL;
	_ufn_7.body = NullObject;
	_ufn_7.byteCodeSegment = ((ByteCodeSegment)&_bcs_7);
	ci = (ClosureInfo)&_ufn_7.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_7), ((SmileList)&_list_7), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_7), ((UserFunctionInfo)&_ufn_7), globalClosure);

	SmileList_Init(((SmileList)&_list_8), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_8.parent = NULL;
	_ufn_8.argList = ((SmileList)&_list_8);
	_ufn_8.position = NULL;
	_ufn_8.body = NullObject;
	_ufn_8.byteCodeSegment = ((ByteCodeSegment)&_bcs_8);
	ci = (ClosureInfo)&_ufn_8.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_8), ((SmileList)&_list_8), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_8), ((UserFunctionInfo)&_ufn_8), globalClosure);

	SmileList_Init(((SmileList)&_list_9), (SmileObject)((SmileSymbol)&_smileSym_self), (SmileObject)NullObject);

	_ufn_9.parent = NULL;
	_ufn_9.argList = ((SmileList)&_list_9);
	_ufn_9.position = NULL;
	_ufn_9.body = NullObject;
	_ufn_9.byteCodeSegment = ((ByteCodeSegment)&_bcs_9);
	ci = (ClosureInfo)&_ufn_9.closureInfo;
	ci->parent = NULL;
	ci->global = NULL;
	ci->kind = 1;
	ci->numVariables = 1;
	ci->numArgs = 1;
	ci->tempSize = 2;
	ci->variableDictionary = NULL;
	ci->variableNames = NULL;
	UserFunctionInfo_ApplyArgs(((UserFunctionInfo)&_ufn_9), ((SmileList)&_list_9), NULL);

	SmileFunction_InitUserFunction(((SmileFunction)&_fn_9), ((UserFunctionInfo)&_ufn_9), globalClosure);

}

//-----------------------------------------------------------------------------
// Members-and-globals instantiations

static void Setup_Float32(ClosureInfo dest)
{
	Symbol targetSymbol = _sym_Float32;

	SmileObject target = ClosureInfo_GetGlobalVariable(dest, targetSymbol);
	SMILE_VCALL2(target, setProperty, _sym_double, (SmileObject)(((SmileFunction)&_fn_0)));
	SMILE_VCALL2(target, setProperty, _sym_half, (SmileObject)(((SmileFunction)&_fn_1)));
}

static void Setup_Float64(ClosureInfo dest)
{
	Symbol targetSymbol = _sym_Float64;

	SmileObject target = ClosureInfo_GetGlobalVariable(dest, targetSymbol);
	SMILE_VCALL2(target, setProperty, _sym_double, (SmileObject)(((SmileFunction)&_fn_2)));
	SMILE_VCALL2(target, setProperty, _sym_half, (SmileObject)(((SmileFunction)&_fn_3)));
}

static void Setup_IntegerBase(ClosureInfo dest)
{
	Symbol targetSymbol = _sym_IntegerBase;

	SmileObject target = ClosureInfo_GetGlobalVariable(dest, targetSymbol);
	SMILE_VCALL2(target, setProperty, _sym_double, (SmileObject)(((SmileFunction)&_fn_4)));
	SMILE_VCALL2(target, setProperty, _sym_half, (SmileObject)(((SmileFunction)&_fn_5)));
}

static void Setup_Real32(ClosureInfo dest)
{
	Symbol targetSymbol = _sym_Real32;

	SmileObject target = ClosureInfo_GetGlobalVariable(dest, targetSymbol);
	SMILE_VCALL2(target, setProperty, _sym_double, (SmileObject)(((SmileFunction)&_fn_6)));
	SMILE_VCALL2(target, setProperty, _sym_half, (SmileObject)(((SmileFunction)&_fn_7)));
}

static void Setup_Real64(ClosureInfo dest)
{
	Symbol targetSymbol = _sym_Real64;

	SmileObject target = ClosureInfo_GetGlobalVariable(dest, targetSymbol);
	SMILE_VCALL2(target, setProperty, _sym_double, (SmileObject)(((SmileFunction)&_fn_8)));
	SMILE_VCALL2(target, setProperty, _sym_half, (SmileObject)(((SmileFunction)&_fn_9)));
}

//-----------------------------------------------------------------------------
// Bootstrap main

void InitBootstrap(SymbolTable symbolTable, ClosureInfo dest)
{
	Closure globalClosure = Closure_CreateGlobal(dest, NULL);

	SetupSymbols(symbolTable);
	FixupBytecode();
	SetupData(globalClosure);

	Setup_Float32(dest);
	Setup_Float64(dest);
	Setup_IntegerBase(dest);
	Setup_Real32(dest);
	Setup_Real64(dest);
}

