
#----------------------------------------------------------------------------
# Shared configuration file for Make-based builds.
#
# This tries to guess some things, but it generally assumes a GNU toolchain.
# If your build chain isn't modern enough (i.e., generally GNU-tool-compatible),
# odds are good the compile won't work.

#----------------------------------------------------------------------------
# Program options.

# C compiler and linker configuration.
CC = gcc
CFLAGS = -O -g
DEPFLAGS = -MM
LINK = gcc
LINKFLAGS = -O -g
LINKSO = gcc
LINKSOFLAGS = -shared -O -g

# Other build-chain tools.
MAKE = make
AR = ar
RANLIB = ranlib
LD = ld
LDCONFIG = ldconfig

# Names and configuration for common utilities.
RM = rm -f
RM_R = rm -rf
MKDIR_P = mkdir -p
SED = sed
PRINTF = printf

# Output filename extensions.
BIN_EXT =
SO_EXT =

#----------------------------------------------------------------------------
# Installation options.

# Installation tools.
INSTALL = install
INSTALL_PROGRAM = $(INSTALL)
INSTALL_DATA = $(INSTALL) -m 644

# Installation paths.
#
# These paths are intended to be GNU-standards-compatible; see
# https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
# for additional documentation as to what these are and what they do.

prefix = /usr/local

exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
libdir = $(exec_prefix)/lib

includedir = $(prefix)/include
sysconfigdir = $(prefix)/etc
localstatedir = $(prefix)/var

datarootdir = $(prefix)/share
datadir = $(datarootdir)

mandir = $(datarootdir)/man
man1dir = $(mandir)/man1
man1ext = .1

